/**
 * Canonical Streamer Factory brand asset paths (public/).
 * Generated by `node scripts/generate-brand-assets.mjs`.
 */
export const brandAssets = {
  logo: {
    master: "/sflogo.png",
    webp: "/branding/logo/sflogo.webp",
    png512: "/branding/logo/sflogo-512.png",
    png256: "/branding/logo/sflogo-256.png",
    png128: "/branding/logo/sflogo-128.png",
    markSvg: "/branding/logo/sf-mark.svg",
    markRoundedSvg: "/branding/logo/sf-mark-rounded.svg",
    markTransparentSvg: "/branding/logo/sf-mark-transparent.svg",
    markPng: (size: 16 | 32 | 48 | 64 | 96 | 128 | 192 | 512) =>
      `/branding/logo/sf-mark-${size}.png`,
  },
  favicon: {
    ico: "/branding/favicon/favicon.ico",
    png16: "/branding/favicon/favicon-16.png",
    png32: "/branding/favicon/favicon-32.png",
    apple: "/branding/favicon/apple-touch-icon.png",
    mask: "/branding/favicon/mask-icon.svg",
    safariPinned: "/branding/favicon/safari-pinned-tab.svg",
    android192: "/branding/favicon/android-chrome-192x192.png",
    android512: "/branding/favicon/android-chrome-512x512.png",
    pwa192: "/branding/favicon/pwa-192.png",
    pwa512: "/branding/favicon/pwa-512.png",
    browserconfig: "/branding/favicon/browserconfig.xml",
  },
  avatar: {
    default: "/branding/avatars/default-avatar.png",
    defaultSvg: "/branding/avatars/default-avatar.svg",
    default32: "/branding/avatars/default-avatar-32.png",
    default64: "/branding/avatars/default-avatar-64.png",
  },
  emails: {
    logo: "/branding/emails/logo-240.png",
  },
  loading: {
    mark: "/branding/loading/sf-loader.png",
    markSvg: "/branding/loading/sf-loader.svg",
  },
  splash: {
    desktop: "/branding/splash/splash-desktop.webp",
    tablet: "/branding/splash/splash-tablet.webp",
    phone: "/branding/splash/splash-phone.webp",
    pwa: "/branding/splash/splash-pwa.webp",
  },
  backgrounds: {
    mesh: "/branding/backgrounds/gradient-mesh.svg",
    meshWebp: "/branding/backgrounds/gradient-mesh.webp",
    particles: "/branding/backgrounds/particles.svg",
  },
  watermarks: {
    dark: "/branding/watermarks/sf-dark.svg",
    light: "/branding/watermarks/sf-light.svg",
    minimal: "/branding/watermarks/sf-minimal.svg",
  },
  emptyStates: {
    battles: "/branding/empty-states/battles.webp",
    rankings: "/branding/empty-states/rankings.webp",
    notifications: "/branding/empty-states/notifications.webp",
    lessons: "/branding/empty-states/lessons.webp",
    members: "/branding/empty-states/members.webp",
    activity: "/branding/empty-states/activity.webp",
  },
  og: {
    homepage: "/branding/og/homepage.png",
    join: "/branding/og/join.png",
    rankings: "/branding/og/rankings.png",
    members: "/branding/og/members.png",
    streameru: "/branding/og/streameru.png",
    battleHub: "/branding/og/battle-hub.png",
    creatorProfile: "/branding/og/creator-profile.png",
    dashboard: "/branding/og/dashboard.png",
  },
  icons: {
    growth: "/branding/icons/growth.svg",
    training: "/branding/icons/training.svg",
    rankings: "/branding/icons/rankings.svg",
    community: "/branding/icons/community.svg",
    battle: "/branding/icons/battle.svg",
    calendar: "/branding/icons/calendar.svg",
    coach: "/branding/icons/coach.svg",
    notifications: "/branding/icons/notifications.svg",
    creator: "/branding/icons/creator.svg",
    schedule: "/branding/icons/schedule.svg",
    analytics: "/branding/icons/analytics.svg",
    monetization: "/branding/icons/monetization.svg",
    messages: "/branding/icons/messages.svg",
    support: "/branding/icons/support.svg",
    awards: "/branding/icons/awards.svg",
    achievements: "/branding/icons/achievements.svg",
    profile: "/branding/icons/profile.svg",
  },
  badges: {
    verifiedCreator: "/branding/badges/verified-creator.svg",
    topCreator: "/branding/badges/top-creator.svg",
    factoryChampion: "/branding/badges/factory-champion.svg",
    topRecruiter: "/branding/badges/top-recruiter.svg",
    trainer: "/branding/badges/trainer.svg",
    battleMaster: "/branding/badges/battle-master.svg",
    /** Prefer CredentialBadge React component for UI; SVG path for emails/OG. */
    streameruGraduate: "/branding/badges/credentials/streameru-diploma.svg",
    foundingMember: "/branding/badges/founding-member.svg",
    premium: "/branding/badges/premium.svg",
    elite: "/branding/badges/elite.svg",
    gold: "/branding/badges/gold.svg",
    diamond: "/branding/badges/diamond.svg",
    credentials: {
      programCertificate: "/branding/badges/credentials/program-certificate.svg",
      diploma: "/branding/badges/credentials/streameru-diploma.svg",
      managerCollege: "/branding/badges/credentials/manager-college.svg",
      hallOfFameGraduate: "/branding/badges/credentials/hall-of-fame-graduate.svg",
    },
  },
  medals: {
    first: "/branding/medals/1st.svg",
    second: "/branding/medals/2nd.svg",
    third: "/branding/medals/3rd.svg",
    top10: "/branding/medals/top-10.svg",
    top25: "/branding/medals/top-25.svg",
    champion: "/branding/medals/champion.svg",
  },
} as const;

/** Brand palette from the approved master brand board. */
export const brandColors = {
  pink: "#FF2ED1",
  purple: "#A020F0",
  indigo: "#5B3BFF",
  cyan: "#00E5FF",
  navy: "#0B0F1A",
  charcoal: "#1A1F2E",
  white: "#FFFFFF",
} as const;

export type EmptyStateKind = keyof typeof brandAssets.emptyStates;
