/**
 * Lesson Production Briefs — source of truth for what assets would help each lesson.
 * Code-seeded so the admin setup center works before/without DB rows; DB holds upload status.
 */

import type { AssetPriority, AssetType, OwnershipKind } from "@/lib/streameru-media/types";
import { CURRICULUM } from "@/lib/resources/curriculum";

export type BriefAsset = {
  /** Stable key within lesson — used as placeholder_key / reusable seed id suffix */
  key: string;
  assetType: AssetType;
  title: string;
  description: string;
  purpose: string;
  sectionKey: string;
  placement: string;
  captureInstructions: string;
  highlight?: string;
  cropBlur?: string;
  device?: string;
  orientation?: string;
  dimensionsHint?: string;
  caption: string;
  alt: string;
  priority: AssetPriority;
  required: boolean;
  ownership: OwnershipKind;
  privacyWarning?: string;
  reusableKey?: string;
  /** Diagram: Cursor can generate branded SVG */
  cursorCanGenerate?: boolean;
  founderQuestion?: string;
  videoTalkingPoints?: string[];
  estimatedMinutes?: number;
};

export type LessonProductionBrief = {
  lessonSlug: string;
  lessonTitle: string;
  programName: string;
  globalOrder: number;
  assets: BriefAsset[];
};

function brief(
  slug: string,
  assets: BriefAsset[],
): LessonProductionBrief {
  const lesson = CURRICULUM.find((l) => l.slug === slug);
  return {
    lessonSlug: slug,
    lessonTitle: lesson?.title ?? slug,
    programName: lesson?.programName ?? "StreamerU",
    globalOrder: lesson?.globalOrder ?? 0,
    assets,
  };
}

/** Lesson 1 — gold-standard production brief (fully specified). */
const LESSON_1: LessonProductionBrief = brief("start-strong-on-tiktok-live", [
  {
    key: "profile-ready",
    assetType: "screenshot",
    title: "TikTok profile readiness",
    description:
      "TikTok profile showing a clear photo, readable username, and one-sentence bio",
    purpose: "Shows learners what LIVE-ready looks like before their first session",
    sectionKey: "Screenshots",
    placement: "After “Confirm your account is LIVE-ready”",
    captureInstructions:
      "Open TikTok → your profile. Capture a portrait screenshot showing username, profile photo, and bio. Do not begin a LIVE.",
    highlight: "Username, profile photo, and bio",
    cropBlur: "Crop follower counts / likes if distracting; blur DMs or notifications",
    device: "TikTok mobile app",
    orientation: "Portrait phone screenshot",
    dimensionsHint: "Portrait, min 720px wide",
    caption: "A clear profile helps new viewers understand who you are within seconds.",
    alt: "TikTok creator profile with readable username, clear profile photo, and concise bio",
    priority: "helpful",
    required: false,
    ownership: "needs_brad",
    privacyWarning: "Do not show private messages, phone numbers, or sensitive personal data.",
    reusableKey: "tiktok-profile-ready",
    estimatedMinutes: 5,
  },
  {
    key: "phone-eye-level",
    assetType: "photo",
    title: "Phone at eye level with front light",
    description: "Phone propped at eye level with a lamp or window light facing the creator",
    purpose: "Makes the framing + light priority concrete and copyable",
    sectionKey: "Screenshots",
    placement: "After ten-minute setup (audio / light / framing)",
    captureInstructions:
      "Photograph a phone secured at eye level (tripod, shelf, or books). Light should come from in front of the creator, not behind. Optional: a second “wrong” backlight photo for comparison later.",
    highlight: "Eye-level camera + front-facing light",
    device: "Any camera / second phone",
    orientation: "Landscape or portrait OK",
    dimensionsHint: "Min 1200px on long edge",
    caption: "Eye-level framing and front light beat expensive gear aimed the wrong way.",
    alt: "Smartphone mounted at eye level with a lamp lighting the subject from the front",
    priority: "helpful",
    required: false,
    ownership: "needs_brad",
    privacyWarning: "Avoid private rooms, addresses, family photos, or notification banners.",
    reusableKey: "setup-phone-eye-level",
    estimatedMinutes: 10,
  },
  {
    key: "go-live-setup",
    assetType: "screenshot",
    title: "Go LIVE setup screen",
    description: "Go LIVE setup screen with title/topic field highlighted",
    purpose: "Removes first-timer confusion about where title and controls live",
    sectionKey: "Screenshots",
    placement: "After “Build a mental map of the Go LIVE screen”",
    captureInstructions:
      "Open TikTok LIVE setup WITHOUT going live. Capture the pre-broadcast screen. Mentally note title/topic field, camera orientation, and where End will appear. Crop notifications.",
    highlight: "Title/topic field; camera orientation; End control location (if visible pre-live)",
    cropBlur: "Blur username/notifications if needed",
    device: "TikTok mobile app",
    orientation: "Portrait phone screenshot",
    dimensionsHint: "Portrait, min 720px wide",
    caption: "Learn the control categories before you broadcast — layouts change, categories stay.",
    alt: "TikTok Go LIVE setup screen with title or topic field visible before broadcasting",
    priority: "helpful",
    required: false,
    ownership: "needs_brad",
    privacyWarning: "Do not show private account warnings or payment screens.",
    reusableKey: "tiktok-go-live-setup",
    estimatedMinutes: 5,
  },
  {
    key: "live-controls-map",
    assetType: "screenshot",
    title: "Live view control map",
    description: "Live view with chat, viewer count, and end control areas identified",
    purpose: "Completes the mental map once a practice LIVE is safe to capture from a private test",
    sectionKey: "Screenshots",
    placement: "With Go LIVE mental map (optional enhancement)",
    captureInstructions:
      "Only if you can capture a practice LIVE safely. Screenshot in-LIVE UI with chat and viewer count visible. Prefer a private/test account. End promptly.",
    highlight: "Chat feed, viewer count, end control",
    cropBlur: "Blur other users’ usernames in chat",
    device: "TikTok mobile app",
    orientation: "Portrait",
    caption: "Know where chat, viewer count, and End live before nerves hit.",
    alt: "TikTok LIVE interface with chat, viewer count, and end controls indicated",
    priority: "optional",
    required: false,
    ownership: "needs_brad",
    privacyWarning: "Never expose minors or private chat content.",
    reusableKey: "tiktok-live-controls",
    estimatedMinutes: 15,
  },
  {
    key: "live-vs-video",
    assetType: "diagram",
    title: "LIVE versus posted video",
    description:
      "LIVE vs posted video — finished clip on the left, real-time hosted room on the right",
    purpose: "Teaches the core mental model of Lesson 1 in one glance",
    sectionKey: "Diagrams",
    placement: "After “What TikTok LIVE actually is”",
    captureInstructions:
      "Two-panel diagram: left = finished short video (record → edit → post); right = real-time hosted room (talk → interact → stay). Streamer Factory brand colors. No TikTok trademark logos required.",
    caption: "A post is a finished clip. LIVE is a room you host in real time.",
    alt: "Diagram comparing a finished TikTok video to a real-time LIVE hosted room",
    priority: "helpful",
    required: false,
    ownership: "cursor_can_create",
    cursorCanGenerate: true,
    reusableKey: "diagram-live-vs-video",
    estimatedMinutes: 20,
  },
  {
    key: "setup-priority-pyramid",
    assetType: "diagram",
    title: "Setup priority pyramid",
    description:
      "Setup priority pyramid — 1) Audio  2) Light  3) Framing  4) Title + first-minute promise",
    purpose: "Locks the Lesson 1 setup order so gear shopping does not replace basics",
    sectionKey: "Diagrams",
    placement: "After ten-minute setup section",
    captureInstructions:
      "Four-level pyramid or stacked bars, bottom→top: 1 Clear audio 2 Front-facing light 3 Eye-level framing 4 Title + first-minute promise. Note: expensive gear is not on the foundation.",
    caption: "Solve audio, light, and framing before you buy more gear.",
    alt: "Pyramid diagram showing setup priority from audio up through first-minute promise",
    priority: "helpful",
    required: false,
    ownership: "cursor_can_create",
    cursorCanGenerate: true,
    reusableKey: "diagram-setup-priority",
    estimatedMinutes: 20,
  },
  {
    key: "founder-first-live-nerves",
    assetType: "founder_story",
    title: "Founder insight — starting without waiting for perfect",
    description: "Brad experience: waiting for perfect gear/audience delays practice",
    purpose: "Reinforces Reality Check + confidence-first philosophy with verified experience",
    sectionKey: "From Brad's Experience",
    placement: "From Brad's Experience section",
    captureInstructions: "Answer the founder question in 80–120 words. May be paraphrased with approval.",
    founderQuestion:
      "What did waiting for perfect gear or a guaranteed audience cost you early on — and what would you tell a creator staring at an empty Go LIVE screen?",
    caption: "From Brad's experience",
    alt: "",
    priority: "helpful",
    required: false,
    ownership: "brad_must_approve",
    estimatedMinutes: 10,
  },
]);

/** Compact brief builder for remaining curriculum lessons */
function assetsFor(
  items: Array<Omit<BriefAsset, "sectionKey"> & { sectionKey?: string }>,
): BriefAsset[] {
  return items.map((a) => ({
    sectionKey:
      a.sectionKey ??
      (a.assetType === "diagram"
        ? "Diagrams"
        : a.assetType === "founder_story"
          ? "From Brad's Experience"
          : a.assetType === "worksheet" || a.assetType === "checklist"
            ? "Downloads"
            : "Screenshots"),
    ...a,
  }));
}

const REST: LessonProductionBrief[] = [
  brief(
    "your-first-live-structure",
    assetsFor([
      {
        key: "sticky-run-of-show",
        assetType: "photo",
        title: "Sticky-note run-of-show",
        description:
          "Physical sticky-note run-of-show with Open, Seg 1–3, Close and rough timers beside a phone",
        purpose: "Makes the glanceable map tactile so beginners stop improvising under stress",
        placement: "Screenshots — after sticky-note / run sheet method",
        captureInstructions:
          "Photograph a handwritten sticky note listing Open, Seg 1, Seg 2, Seg 3, Close with rough minute ranges, placed beside a phone at eye level. Readable handwriting. No private address visible in background.",
        highlight: "Open / Seg 1–3 / Close labels + timers",
        cropBlur: "Crop unrelated desk clutter; blur any notifications on phone",
        device: "Any camera / second phone",
        orientation: "Landscape or portrait OK",
        dimensionsHint: "Min 1200px on long edge",
        caption: "A sticky note beats a blank mind at minute ten.",
        alt: "Handwritten LIVE run-of-show sticky note beside a smartphone on a stand",
        priority: "helpful",
        required: false,
        ownership: "needs_brad",
        privacyWarning: "Avoid private rooms, family photos, mail, or notification banners.",
        reusableKey: "photo-sticky-run-of-show",
        estimatedMinutes: 8,
      },
      {
        key: "notes-app-run-sheet",
        assetType: "screenshot",
        description: "Notes app LIVE run sheet in large font propped just off camera",
        title: "Notes app run sheet",
        purpose: "Shows a digital alternative to sticky notes for creators who prefer phones",
        placement: "Screenshots section",
        captureInstructions:
          "Open Notes (or similar) with large font: Open, Seg 1–3, Close. Screenshot the note. Optional: photo of phone propped just off the main camera.",
        highlight: "Large readable segment titles",
        cropBlur: "Blur unrelated notes or personal reminders",
        device: "Phone notes app",
        orientation: "Portrait",
        dimensionsHint: "Portrait, min 720px wide",
        caption: "Large-font notes work if you can glance without hiding your face.",
        alt: "Phone notes app showing a LIVE open-segments-close run sheet in large text",
        priority: "helpful",
        required: false,
        ownership: "needs_brad",
        privacyWarning: "Do not show personal calendar, messages, or other app content.",
        reusableKey: "screenshot-notes-run-sheet",
        estimatedMinutes: 5,
      },
      {
        key: "segment-hook-cue-card",
        assetType: "photo",
        title: "Segment hook cue card",
        description: "Example segment hook written as a one-line cue card",
        purpose: "Makes transition hooks concrete and copyable",
        placement: "Screenshots section",
        captureInstructions:
          "Write one transition bridge on a card/sticky: acknowledge → name segment → question. Photograph clearly.",
        caption: "Fifteen-second bridges re-orient late joiners.",
        alt: "Cue card with a one-line LIVE segment transition hook",
        priority: "optional",
        required: false,
        ownership: "needs_brad",
        estimatedMinutes: 5,
      },
      {
        key: "live-flow-timeline",
        assetType: "diagram",
        title: "LIVE Flow Timeline",
        description:
          "LIVE Flow Timeline — Open → Segment 1 → Segment 2 → Segment 3 → Close with minute ranges",
        purpose: "Shows the full framework timing at a glance",
        placement: "Diagrams — after framework teaching",
        captureInstructions:
          "Horizontal timeline ~0–35 minutes with five labeled blocks: Open 3–5, Seg1 8–10, Seg2 8–10, Seg3 8–10, Close 3–5. Streamer Factory brand colors. Cursor may generate SVG; Brad approves before publish.",
        caption: "Soft timers guide rhythm — the goal is always knowing what’s next.",
        alt: "Timeline diagram of a LIVE from open through three segments to close",
        priority: "helpful",
        required: false,
        ownership: "cursor_can_create",
        cursorCanGenerate: true,
        reusableKey: "diagram-live-flow-timeline",
        estimatedMinutes: 20,
      },
      {
        key: "conversation-loop",
        assetType: "diagram",
        title: "Conversation Loop",
        description: "Conversation Loop — Viewer joins → Context → Discussion → Question → Repeat",
        purpose: "Teaches LIVE as a loop, not a one-way lecture",
        placement: "Diagrams",
        captureInstructions:
          "Circular or cyclical flowchart: Viewer joins → Context → Discussion → Question → Repeat. Simple labels. Cursor can generate branded SVG.",
        caption: "When chat is quiet, you still run the loop as the host.",
        alt: "Circular diagram of the LIVE conversation loop from join to question to repeat",
        priority: "helpful",
        required: false,
        ownership: "cursor_can_create",
        cursorCanGenerate: true,
        reusableKey: "diagram-conversation-loop",
        estimatedMinutes: 15,
      },
      {
        key: "dead-chat-recovery",
        assetType: "diagram",
        title: "Dead Chat Recovery Flow",
        description:
          "Dead Chat Recovery Flow — Silence → Rephrase question → A/B choice → Example → Next bullet",
        purpose: "Gives a visible recovery path when conversation dies",
        placement: "Diagrams",
        captureInstructions:
          "Vertical decision flow: Silence detected → Rephrase question → A/B choice → Short example → Next bullet / emergency prompt. Note: never stare at viewer count.",
        caption: "Silence is a cue to host — not a cue to freeze.",
        alt: "Flowchart for recovering from dead chat during a TikTok LIVE",
        priority: "helpful",
        required: false,
        ownership: "cursor_can_create",
        cursorCanGenerate: true,
        reusableKey: "diagram-dead-chat-recovery",
        estimatedMinutes: 15,
      },
      {
        key: "natural-repeat-cycle",
        assetType: "diagram",
        title: "Natural Repeat Cycle",
        description:
          "Natural Repeat Cycle — Late joiner needs topic + current segment + what's next",
        purpose: "Explains why intentional repetition helps retention",
        placement: "Diagrams",
        captureInstructions:
          "Simple three-callout graphic for late joiners: (1) Topic (2) Current segment (3) What’s next. Optional: small “audience keeps changing” note.",
        caption: "Newcomers need repetition — the audience keeps changing.",
        alt: "Diagram showing late joiners need topic, current segment, and what comes next",
        priority: "optional",
        required: false,
        ownership: "cursor_can_create",
        cursorCanGenerate: true,
        reusableKey: "diagram-natural-repeat-cycle",
        estimatedMinutes: 12,
      },
      {
        key: "topic-tree",
        assetType: "diagram",
        title: "Topic Tree",
        description: "Topic tree — one theme branching into three distinct middle segments",
        purpose: "Stops beginners from writing three copies of the same rant",
        placement: "Optional enhancement near Examples",
        captureInstructions:
          "Tree: root = session theme; three branches = Seg 1/2/3 titles (distinct). Cursor can generate.",
        caption: "One theme, three distinct jobs — not one rant in three outfits.",
        alt: "Tree diagram with one LIVE theme branching into three distinct segments",
        priority: "optional",
        required: false,
        ownership: "cursor_can_create",
        cursorCanGenerate: true,
        estimatedMinutes: 12,
      },
      {
        key: "founder-early-structure",
        assetType: "founder_story",
        title: "Founder insight — early LIVE structure",
        description: "Brad: early LIVE structure before a repeatable system",
        purpose: "Verified experience on what unstructured hosting cost — and what fixed it",
        placement: "From Brad's Experience",
        captureInstructions:
          "Ask Brad: What did your early LIVE structure look like before you developed a repeatable system? 80–120 words. May paraphrase with approval. Never invent.",
        founderQuestion:
          "What did your early LIVE structure look like before you developed a repeatable system?",
        caption: "From Brad's experience",
        alt: "",
        priority: "helpful",
        required: false,
        ownership: "brad_must_approve",
        estimatedMinutes: 10,
      },
      {
        key: "founder-ran-out-of-words",
        assetType: "founder_story",
        title: "Founder insight — running out of things to say",
        description: "Brad: mistake that caused completely running out of things to say",
        purpose: "Normalizes the blank-mind moment and points to structure as the fix",
        placement: "From Brad's Experience / Reality Check enhancement",
        captureInstructions:
          "Ask Brad: What mistake caused you to completely run out of things to say on LIVE? What do you wish you had on a sticky note that day?",
        founderQuestion:
          "What mistake caused you to completely run out of things to say — and what would you put on a sticky note now?",
        caption: "From Brad's experience",
        alt: "",
        priority: "helpful",
        required: false,
        ownership: "brad_must_approve",
        estimatedMinutes: 10,
      },
      {
        key: "founder-felt-natural",
        assetType: "founder_story",
        title: "Founder insight — when LIVE felt natural",
        description: "Brad: what finally made LIVE sessions feel natural",
        purpose: "Connects muscle memory to repetition inside a simple framework",
        placement: "From Brad's Experience",
        captureInstructions:
          "Ask Brad: What finally made LIVE sessions feel natural? Emphasize habits over talent. 80–120 words. Approval required.",
        founderQuestion: "What finally made LIVE sessions feel natural?",
        caption: "From Brad's experience",
        alt: "",
        priority: "optional",
        required: false,
        ownership: "brad_must_approve",
        estimatedMinutes: 10,
      },
      {
        key: "structure-walkthrough-video",
        assetType: "video",
        title: "How to fill a LIVE Run Sheet (60–90s)",
        description: "Short teaching video filling open → three segments → close on camera",
        purpose: "Shows the worksheet in motion for visual learners",
        placement: "Optional enhancement near Downloads / Main Lesson",
        captureInstructions:
          "Working title: Fill your LIVE Run Sheet in 90 seconds. Brad on camera recommended. Shot list: (1) blank sheet (2) write three segment titles (3) add one bridge line (4) hold sheet beside camera. Silent captions OK. Do not require TikTok UI.",
        videoTalkingPoints: [
          "Three distinct middle segment titles first",
          "Bridge = acknowledge → name → question",
          "Close = recap + thanks + next tease",
        ],
        caption: "Fill the map before you open the room.",
        alt: "",
        priority: "optional",
        required: false,
        ownership: "needs_brad",
        estimatedMinutes: 45,
      },
    ]),
  ),
  brief(
    "platform-rules-new-live-creators",
    assetsFor([
      {
        key: "guidelines-entry",
        assetType: "screenshot",
        title: "Community Guidelines entry",
        description: "Where creators open LIVE community guidelines in-app",
        purpose: "Points beginners to the real policy surface without claiming thresholds",
        placement: "Screenshots — after risk categories",
        captureInstructions:
          "Screenshot TikTok help/guidelines entry relevant to LIVE. Crop personal account chrome and any strike/appeal screens.",
        highlight: "Community Guidelines / LIVE policy entry point",
        cropBlur: "Crop account-specific notifications or warnings",
        device: "TikTok mobile app",
        orientation: "Portrait phone screenshot",
        dimensionsHint: "Portrait, min 720px wide",
        caption: "Learn categories — specific rules update over time.",
        alt: "TikTok community guidelines entry point on mobile",
        priority: "helpful",
        required: false,
        ownership: "needs_brad",
        privacyWarning: "No personal appeals or strike screens.",
        reusableKey: "tiktok-guidelines-entry",
        estimatedMinutes: 5,
      },
      {
        key: "sound-library-select",
        assetType: "screenshot",
        title: "Sound library selection screen",
        description: "TikTok LIVE sound library or commercial sound library selection screen",
        purpose: "Makes the default sound-sourcing habit concrete and findable",
        placement: "Screenshots — after Music and sound section",
        captureInstructions:
          "Open the platform's built-in or licensed sound library WITHOUT going live. Screenshot the selection screen.",
        highlight: "Sound library entry point",
        device: "TikTok mobile app",
        orientation: "Portrait phone screenshot",
        dimensionsHint: "Portrait, min 720px wide",
        caption: "Default to licensed sound every session — never a special-occasion decision.",
        alt: "TikTok LIVE sound library selection screen",
        priority: "helpful",
        required: false,
        ownership: "needs_brad",
        reusableKey: "tiktok-sound-library",
        estimatedMinutes: 5,
      },
      {
        key: "calm-chat-reminder",
        assetType: "screenshot",
        title: "Calm chat rule reminder",
        description: "Example of a calm, on-screen pinned chat rule or moderator reminder",
        purpose: "Shows what a professional redirect looks like in the room",
        placement: "Screenshots — near Real Creator Scenarios",
        captureInstructions:
          "Screenshot a pinned message or moderator note reminding chat of a norm. Blur other viewers' usernames.",
        highlight: "Pinned rule / redirect message",
        cropBlur: "Blur viewer usernames and any personal chat content",
        device: "TikTok mobile app",
        orientation: "Portrait",
        caption: "A fast, calm redirect protects the room without a lecture.",
        alt: "Pinned chat rule reminder shown during a TikTok LIVE",
        priority: "optional",
        required: false,
        ownership: "needs_brad",
        privacyWarning: "Blur all viewer usernames and chat content.",
        estimatedMinutes: 10,
      },
      {
        key: "risk-buckets",
        assetType: "diagram",
        title: "Seven risk buckets",
        description: "Seven durable risk categories map",
        purpose: "Teaches the mental model from Lesson 3",
        placement: "Diagrams — after risk categories",
        captureInstructions:
          "Seven labeled buckets: safety, minors, harassment, deception, regulated content, IP, sexual content. Streamer Factory brand colors.",
        caption: "Think in categories, not trivia lists.",
        alt: "Diagram of seven livestream risk categories",
        priority: "helpful",
        required: false,
        ownership: "cursor_can_create",
        cursorCanGenerate: true,
        reusableKey: "diagram-risk-buckets",
        estimatedMinutes: 20,
      },
      {
        key: "enforcement-shape",
        assetType: "diagram",
        title: "Enforcement shape flow",
        description: "Detection → review with context → escalating consequences → appeal",
        purpose: "Makes the general enforcement shape memorable without implying specific thresholds",
        placement: "Diagrams — after How enforcement generally works",
        captureInstructions:
          "Four-step horizontal flow: Detection (automated + reports) → Review with context → Escalating consequences → Appeal. No specific numbers or timelines.",
        caption: "Patterns and context matter more than any single moment.",
        alt: "Flow diagram of detection, review, escalation, and appeal",
        priority: "helpful",
        required: false,
        ownership: "cursor_can_create",
        cursorCanGenerate: true,
        reusableKey: "diagram-enforcement-shape",
        estimatedMinutes: 20,
      },
      {
        key: "founder-close-call",
        assetType: "founder_story",
        title: "Founder insight — treating close calls as information",
        description: "Brad: how treating a close call as information (not bad luck) shaped long-term habits",
        purpose: "Reinforces the professional-baseline habit with verified experience",
        placement: "From Brad's Experience",
        captureInstructions:
          "Ask Brad: What is a close call (yours or a creator you've worked with) that changed how you think about platform rules — without naming specific policy numbers? 80–120 words. May paraphrase with approval.",
        founderQuestion:
          "What close call (yours or a creator you've mentored) changed how you personally think about platform-rule habits — and what changed afterward?",
        caption: "From Brad's experience",
        alt: "",
        priority: "helpful",
        required: false,
        ownership: "brad_must_approve",
        estimatedMinutes: 10,
      },
    ]),
  ),
  brief(
    "what-gets-you-banned",
    assetsFor([
      {
        key: "red-line-spectrum",
        assetType: "diagram",
        title: "Red-line vs underperforming content spectrum",
        description: "Underperform (fixable) vs account-ending red-line content",
        purpose: "Separates weak content from ban-risk patterns",
        sectionKey: "Diagrams",
        placement: "Diagrams — after Behaviors that reliably escalate fast",
        captureInstructions:
          "Spectrum graphic: weak/underperforming content (fixable, left) → caution zone (middle) → red-line severe (right, resets progress). Streamer Factory brand colors.",
        caption: "Weak content is fixable. Red lines reset progress.",
        alt: "Spectrum from weak content to account-ending red lines",
        priority: "helpful",
        required: false,
        ownership: "cursor_can_create",
        cursorCanGenerate: true,
        reusableKey: "diagram-red-line-spectrum",
        estimatedMinutes: 20,
      },
      {
        key: "guidelines-severe",
        assetType: "screenshot",
        title: "Community Guidelines severe-violation summary",
        description: "Platform community guidelines summary page highlighting severe-violation categories",
        purpose: "Anchors red-line teaching to a real policy surface",
        sectionKey: "Screenshots",
        placement: "Screenshots — after Behaviors that reliably escalate fast",
        captureInstructions:
          "Screenshot the guidelines summary or severe-violations section of TikTok's Help Center. Crop personal account chrome.",
        highlight: "Severe-violation category headings",
        device: "TikTok mobile app or Help Center",
        orientation: "Portrait or landscape",
        caption: "The categories are public — the point is recognizing them fast, in the moment.",
        alt: "TikTok community guidelines page highlighting severe violation categories",
        priority: "helpful",
        required: false,
        ownership: "needs_brad",
        privacyWarning: "No personal appeals or strike screens.",
        reusableKey: "tiktok-guidelines-severe",
        estimatedMinutes: 5,
      },
      {
        key: "calm-redirect-example",
        assetType: "screenshot",
        title: "Calm on-stream redirect example",
        description: "Example of a calm on-stream redirect message after a risky chat request",
        purpose: "Shows the self-check translated into an actual on-screen moment",
        sectionKey: "Screenshots",
        placement: "Screenshots — near Real Creator Scenarios",
        captureInstructions:
          "Screenshot or re-create a short on-stream redirect caption/overlay (e.g. \"Not doing that one — moving on\"). Blur any real viewer usernames.",
        highlight: "Short, confident redirect phrasing",
        cropBlur: "Blur viewer usernames and chat content",
        device: "TikTok mobile app",
        orientation: "Portrait",
        caption: "Short and confident beats a long explanation every time.",
        alt: "Example of a calm redirect shown during a TikTok LIVE",
        priority: "optional",
        required: false,
        ownership: "needs_brad",
        privacyWarning: "Blur all viewer usernames and chat content.",
        estimatedMinutes: 10,
      },
      {
        key: "founder-joke-defense",
        assetType: "founder_story",
        title: "Founder — jokes are not a defense",
        description: "Experience: watching a risky bit get defended as \"just a joke\"",
        purpose: "Makes the red-line self-check memorable with verified experience",
        sectionKey: "From Brad's Experience",
        placement: "From Brad's Experience",
        captureInstructions:
          "Ask Brad: Have you seen a creator defend a risky bit as \"just a joke\" — and what actually happened? Keep it general, no specific policy numbers. 80–120 words. Approve before publish.",
        founderQuestion:
          "Have you seen a creator or someone you mentored try to defend a risky bit as 'just a joke' — what actually happened, and what would you tell them now?",
        caption: "From Brad's experience",
        alt: "",
        priority: "helpful",
        required: false,
        ownership: "brad_must_approve",
        estimatedMinutes: 10,
      },
    ]),
  ),
  brief(
    "how-to-avoid-violations",
    assetsFor([
      {
        key: "mod-controls",
        assetType: "screenshot",
        title: "Chat moderation controls",
        description: "Moderator management panel in LIVE settings",
        purpose: "Shows self-mod tools beginners can use alone",
        sectionKey: "Screenshots",
        placement: "Screenshots — after Build a moderator bench",
        captureInstructions:
          "Screenshot the moderator management or timeout/block controls without exposing real users' handles.",
        highlight: "Add moderator / timeout / block controls",
        cropBlur: "Blur real usernames",
        device: "TikTok mobile app",
        orientation: "Portrait phone screenshot",
        dimensionsHint: "Portrait, min 720px wide",
        caption: "Systems beat willpower when you are tired.",
        alt: "TikTok LIVE moderation controls for timeout or block",
        priority: "helpful",
        required: false,
        ownership: "needs_brad",
        privacyWarning: "Blur all real usernames.",
        reusableKey: "tiktok-mod-controls",
        estimatedMinutes: 5,
      },
      {
        key: "pinned-chat-rules",
        assetType: "screenshot",
        title: "Pinned chat rules example",
        description: "Pinned chat rules or community guidelines message example",
        purpose: "Shows what a simple, three-to-four rule pin actually looks like",
        sectionKey: "Screenshots",
        placement: "Screenshots — after Set chat norms",
        captureInstructions:
          "Screenshot or re-create a pinned message with 3–4 short chat norms. Blur unrelated chat content.",
        highlight: "Pinned norms message",
        device: "TikTok mobile app",
        orientation: "Portrait",
        caption: "Three or four rules regulars can repeat for you.",
        alt: "Pinned chat rules message example on a livestream",
        priority: "optional",
        required: false,
        ownership: "needs_brad",
        privacyWarning: "Blur unrelated chat content and usernames.",
        estimatedMinutes: 8,
      },
      {
        key: "escalation-ladder",
        assetType: "diagram",
        title: "Solo escalation ladder",
        description: "Redirect → warning → timeout → block ladder",
        purpose: "Gives a decision tree for chaotic chat",
        sectionKey: "Diagrams",
        placement: "Diagrams — after Run a moderation-forward session",
        captureInstructions:
          "Vertical ladder: redirect → warning → timeout → block, with a short calm-tone note at each step. Streamer Factory brand colors.",
        caption: "Decide the ladder before the night gets loud.",
        alt: "Diagram of chat moderation escalation steps from redirect to block",
        priority: "helpful",
        required: false,
        ownership: "cursor_can_create",
        cursorCanGenerate: true,
        reusableKey: "diagram-escalation-ladder",
        estimatedMinutes: 20,
      },
      {
        key: "founder-mod-bench",
        assetType: "founder_story",
        title: "Founder insight — building a moderator bench",
        description: "Brad: what changed after building a real moderator bench vs. going solo",
        purpose: "Reinforces the systems-over-willpower theme with verified experience",
        sectionKey: "From Brad's Experience",
        placement: "From Brad's Experience",
        captureInstructions:
          "Ask Brad: What changed for you (or a creator you've mentored) after building a real moderator bench instead of moderating solo? 80–120 words. Approve before publish.",
        founderQuestion:
          "What changed after you or a creator you mentored built a real moderator bench, compared to moderating solo?",
        caption: "From Brad's experience",
        alt: "",
        priority: "helpful",
        required: false,
        ownership: "brad_must_approve",
        estimatedMinutes: 10,
      },
    ]),
  ),
  brief(
    "long-term-account-safety",
    assetsFor([
      {
        key: "2fa-entry",
        assetType: "screenshot",
        title: "2FA settings entry",
        description: "Account security settings showing two-factor authentication and recovery options",
        purpose: "Turns 'enable 2FA' from abstract advice into a findable screen",
        sectionKey: "Screenshots",
        placement: "Screenshots — after Back up your access before you need it",
        captureInstructions: "Screenshot security/2FA entry. Blur phone numbers/emails.",
        highlight: "Two-factor authentication toggle and recovery method entries",
        cropBlur: "Blur phone numbers and recovery emails",
        device: "TikTok mobile app",
        orientation: "Portrait phone screenshot",
        dimensionsHint: "Portrait, min 720px wide",
        caption: "Boring security beats flashy growth hacks.",
        alt: "Account security settings showing two-factor authentication entry",
        priority: "helpful",
        required: false,
        ownership: "needs_brad",
        privacyWarning: "Blur phone numbers and recovery emails.",
        reusableKey: "tiktok-2fa-entry",
        estimatedMinutes: 5,
      },
      {
        key: "collaborator-access-panel",
        assetType: "screenshot",
        title: "Collaborator access permissions panel",
        description: "Collaborator or manager access permissions panel",
        purpose: "Makes access-sprawl cleanup concrete and findable",
        sectionKey: "Screenshots",
        placement: "Screenshots — after Vet brand deals and collaborations",
        captureInstructions: "Screenshot the collaborator/manager permissions panel. Blur any real names or emails.",
        highlight: "Collaborator list and permission levels",
        cropBlur: "Blur real names, emails, or usernames",
        device: "TikTok mobile app or creator settings",
        orientation: "Portrait or landscape",
        caption: "Access sprawl is a quiet risk that compounds silently.",
        alt: "Collaborator or manager access permissions panel for a creator account",
        priority: "helpful",
        required: false,
        ownership: "needs_brad",
        privacyWarning: "Blur real names, emails, and usernames.",
        estimatedMinutes: 5,
      },
      {
        key: "self-audit-loop",
        assetType: "diagram",
        title: "Monthly self-audit loop",
        description: "Watch clips → check fences → confirm moderators → review brand fit → adjust",
        purpose: "Makes the recurring self-audit habit concrete as a repeatable cycle",
        sectionKey: "Diagrams",
        placement: "Diagrams — after Build a recurring self-audit habit",
        captureInstructions:
          "Circular five-step loop: Watch clips → Check fences → Confirm moderators → Review brand fit → Adjust → back to Watch clips. Streamer Factory brand colors.",
        caption: "Drift is quiet. A dated, repeatable loop is what catches it.",
        alt: "Circular diagram of a monthly creator safety self-audit loop",
        priority: "helpful",
        required: false,
        ownership: "cursor_can_create",
        cursorCanGenerate: true,
        reusableKey: "diagram-self-audit-loop",
        estimatedMinutes: 20,
      },
      {
        key: "founder-still-building",
        assetType: "founder_story",
        title: "Founder insight — why some creators are still building years later",
        description: "Brad: what actually separates creators still building years later from those who stopped",
        purpose: "Anchors the capstone lesson's stewardship theme with verified experience",
        sectionKey: "From Brad's Experience",
        placement: "From Brad's Experience",
        captureInstructions:
          "Ask Brad: In your experience, what actually separates creators still building years later from ones who burned out or lost their account? 80–120 words. Approve before publish.",
        founderQuestion:
          "What actually separates creators still building years later from ones who burned out or lost their account?",
        caption: "From Brad's experience",
        alt: "",
        priority: "helpful",
        required: false,
        ownership: "brad_must_approve",
        estimatedMinutes: 10,
      },
    ]),
  ),
  brief(
    "first-10-tiktok-live-sessions",
    assetsFor([
      {
        key: "energy-curve",
        assetType: "diagram",
        title: "30-minute energy curve",
        description: "Energy dip around minutes 10–20",
        purpose: "Prepares creators for the mid-session lull",
        placement: "Pacing map",
        captureInstructions: "Curve chart with dip marked 10–20 and recovery plan callout.",
        caption: "Plan the dip before it happens.",
        alt: "Graph of energy across a 30-minute LIVE with mid-session dip",
        priority: "helpful",
        required: false,
        ownership: "cursor_can_create",
        cursorCanGenerate: true,
      },
    ]),
  ),
  brief(
    "first-week-of-lives-consistency",
    assetsFor([
      {
        key: "week-calendar",
        assetType: "photo",
        title: "Filled weekly consistency calendar",
        description: "Printed or digital calendar with seven defended windows",
        purpose: "Shows what a defendable week looks like",
        placement: "Downloads / Main Lesson",
        captureInstructions: "Photo or screenshot of a filled week planner with one LIVE window per day.",
        caption: "Defend windows you can keep — not fantasy schedules.",
        alt: "Weekly calendar with seven LIVE session windows marked",
        priority: "optional",
        required: false,
        ownership: "needs_brad",
      },
    ]),
  ),
  brief(
    "common-live-mistakes-new-creators",
    assetsFor([
      {
        key: "trap-fix-cards",
        assetType: "diagram",
        title: "Trap → Fix cards",
        description: "Seven beginner traps with fixes",
        purpose: "Quick reference for the Beginner capstone",
        placement: "Main Lesson",
        captureInstructions: "Card grid: trap name → one-line fix for each of seven traps.",
        caption: "Name the trap before it names you.",
        alt: "Cards listing beginner LIVE mistakes and fixes",
        priority: "helpful",
        required: false,
        ownership: "cursor_can_create",
        cursorCanGenerate: true,
      },
    ]),
  ),
  brief(
    "talking-with-empty-room",
    assetsFor([
      {
        key: "npt-triangle",
        assetType: "diagram",
        title: "Narrate / Plan / Teach triangle",
        description: "N/P/T rotation diagram",
        purpose: "Core empty-room system visual",
        placement: "Main Lesson",
        captureInstructions: "Triangle with Narrate, Plan, Teach vertices and rotation arrows.",
        caption: "Empty is normal — N/P/T keeps you useful.",
        alt: "Triangle diagram for Narrate Plan Teach empty-room rotation",
        priority: "helpful",
        required: false,
        ownership: "cursor_can_create",
        cursorCanGenerate: true,
      },
      {
        key: "prompt-bank-photo",
        assetType: "photo",
        title: "Prompt bank beside camera",
        description: "Written empty-room prompts visible off-camera",
        purpose: "Shows the physical habit of visible prompts",
        placement: "Examples",
        captureInstructions: "Photo of sticky notes or prompt card next to streaming phone.",
        caption: "Prompts beat panic when chat is quiet.",
        alt: "Talking-point prompt cards next to a phone used for livestreaming",
        priority: "optional",
        required: false,
        ownership: "needs_brad",
      },
    ]),
  ),
  brief(
    "hooks-and-first-impressions",
    assetsFor([
      {
        key: "join-timeline",
        assetType: "diagram",
        title: "Join decision timeline 0–10s",
        description: "First seconds stay-or-go timeline",
        purpose: "Makes hook urgency concrete",
        placement: "Main Lesson",
        captureInstructions: "0–10 second timeline with stay/leave decision markers.",
        caption: "Every joiner is first-impression zero.",
        alt: "Timeline of a viewer deciding to stay in the first ten seconds",
        priority: "helpful",
        required: false,
        ownership: "cursor_can_create",
        cursorCanGenerate: true,
      },
    ]),
  ),
  brief(
    "content-loops-repeatable-segments",
    assetsFor([
      {
        key: "hvic-loop",
        assetType: "diagram",
        title: "Hook → Value → Interaction → Callback loop",
        description: "Four-part retention loop",
        purpose: "Architecture visual for retention",
        placement: "Main Lesson",
        captureInstructions: "Circular four-step loop diagram with labels H→V→I→C.",
        caption: "Retention is designed, not hoped for.",
        alt: "Circular diagram of hook value interaction callback retention loop",
        priority: "helpful",
        required: false,
        ownership: "cursor_can_create",
        cursorCanGenerate: true,
      },
    ]),
  ),
  brief(
    "structuring-longer-lives",
    assetsFor([
      {
        key: "four-block-runofshow",
        assetType: "photo",
        title: "Four-block run-of-show written out",
        description: "Handwritten or notes-app four-block plan with rough time ranges (opener, deep, recovery, closer)",
        purpose: "Makes the four-block architecture tactile instead of abstract",
        placement: "Screenshots — after the four-block plan is introduced",
        captureInstructions:
          "Photograph or screenshot a plan listing Opener, Deep, Recovery, Closer with rough minute ranges (e.g. 0–20, 20–50, 50–65, 65–90). Readable handwriting or large notes-app font.",
        highlight: "Four block labels + rough time ranges",
        cropBlur: "Blur any unrelated notes or personal reminders",
        device: "Any camera / phone notes app",
        orientation: "Portrait or landscape OK",
        dimensionsHint: "Min 1200px on long edge",
        caption: "A four-block plan turns ninety minutes into four manageable stretches.",
        alt: "Handwritten four-block run-of-show for a ninety-minute LIVE with time ranges",
        priority: "helpful",
        required: false,
        ownership: "needs_brad",
        privacyWarning: "Avoid private addresses, calendars, or notification banners in frame.",
        reusableKey: "photo-four-block-runofshow",
        estimatedMinutes: 8,
      },
      {
        key: "stretch-goal-list",
        assetType: "screenshot",
        title: "Stretch-goal list attached to a block plan",
        description: "Three pre-written stretch goals kept ready for a block that ends early",
        purpose: "Shows the difference between a prepared bonus and improvised filler",
        placement: "Screenshots — after stretch goal explanation",
        captureInstructions: "Screenshot or photo of three written stretch goals (from the Stretch Goal & Energy Arc Tracker or notes app).",
        highlight: "Three distinct stretch goals",
        device: "Phone notes app or printed worksheet",
        orientation: "Portrait",
        dimensionsHint: "Portrait, min 720px wide",
        caption: "Stretch goals are written before the stream, not invented mid-silence.",
        alt: "List of three pre-written stretch goals for a long LIVE session",
        priority: "helpful",
        required: false,
        ownership: "needs_brad",
        reusableKey: "screenshot-stretch-goal-list",
        estimatedMinutes: 5,
      },
      {
        key: "recovery-block-transition",
        assetType: "screenshot",
        title: "Session timer at the recovery-block transition",
        description: "A stream timer or clock showing the moment a session moves into its recovery block",
        purpose: "Grounds the recovery-block timing concept in something visible",
        placement: "Screenshots section",
        captureInstructions: "Screenshot a stream timer/overlay or phone clock at roughly the 50–65 minute mark of a session, paired with a note of what block starts there.",
        caption: "Knowing exactly when the recovery block starts stops it from turning into unplanned dead air.",
        alt: "Stream timer showing the transition point into a recovery block",
        priority: "optional",
        required: false,
        ownership: "needs_brad",
        estimatedMinutes: 5,
      },
      {
        key: "ninety-minute-energy-arc",
        assetType: "diagram",
        title: "Ninety-minute energy arc",
        description: "Four blocks (opener, deep, recovery, closer) with an intensity curve that rises, dips intentionally, and rises again",
        purpose: "Shows the honest energy arc so learners stop expecting flat peak energy for 90 minutes",
        placement: "Diagrams — after the four-block architecture teaching",
        captureInstructions:
          "Horizontal timeline 0–90 minutes with four labeled blocks and an overlaid energy curve: high at open, sustained through deep, intentional dip through recovery, rise through closer. Streamer Factory brand colors. Cursor may generate SVG; Brad approves before publish.",
        caption: "Long LIVE succeeds on an honest energy arc, not flat willpower.",
        alt: "Ninety-minute LIVE timeline with four structural blocks and an energy curve",
        priority: "helpful",
        required: false,
        ownership: "cursor_can_create",
        cursorCanGenerate: true,
        reusableKey: "diagram-ninety-minute-energy-arc",
        estimatedMinutes: 20,
      },
      {
        key: "stretch-goal-decision-diagram",
        assetType: "diagram",
        title: "Stretch goal decision flow",
        description: "Decision flow: reach the end of a block with time and energy to spare → deploy a prepared bonus, never an improvised one",
        purpose: "Makes the prepared-vs-improvised distinction visible as a simple decision point",
        placement: "Diagrams",
        captureInstructions: "Simple two-branch flow: block ends early + energy remains → deploy prepared stretch goal. Block ends on time → move to next block. Cursor can generate branded SVG.",
        caption: "A block ending early is a decision point, not an emergency.",
        alt: "Decision flow diagram for deploying a prepared stretch goal in a long LIVE",
        priority: "helpful",
        required: false,
        ownership: "cursor_can_create",
        cursorCanGenerate: true,
        reusableKey: "diagram-stretch-goal-decision",
        estimatedMinutes: 15,
      },
      {
        key: "founder-longer-lives-lesson",
        assetType: "founder_story",
        title: "Founder insight — learning to hold a full-length session",
        description: "Brad: a specific long session that taught him blocks beat stubbornness",
        purpose: "Grounds the lesson's durable principle in one verified, specific memory",
        placement: "From Brad's Experience enhancement",
        captureInstructions:
          "Ask Brad: Was there a specific long LIVE where you learned the hard way that raw stamina wasn't enough — what happened, and what did you change afterward? 80–120 words. May paraphrase with approval. Never invent if Brad has no clear memory.",
        founderQuestion:
          "Was there a specific long LIVE where you learned raw stamina wasn't enough to carry ninety minutes — what happened, and what did you change afterward?",
        caption: "From Brad's experience",
        alt: "",
        priority: "helpful",
        required: false,
        ownership: "brad_must_approve",
        estimatedMinutes: 10,
      },
    ]),
  ),
  brief(
    "growth-weekly-system",
    assetsFor([
      {
        key: "next-session-tease-list",
        assetType: "screenshot",
        title: "Notes app listing next-session teases",
        description: "Notes app with three or four specific plans to tease for the next session",
        purpose: "Makes the 'specific tease beats vague sign-off' teaching concrete",
        placement: "Screenshots — after the next-session tease explanation",
        captureInstructions: "Screenshot a notes app or written list of 3–4 specific plans/topics for the next stream (e.g. concrete enough a viewer could repeat one back).",
        highlight: "Specific, concrete plan items — not vague topics",
        device: "Phone notes app",
        orientation: "Portrait",
        dimensionsHint: "Portrait, min 720px wide",
        caption: "A specific tease gives a viewer something to actually anticipate.",
        alt: "Notes app list of specific plans to tease for the next livestream",
        priority: "helpful",
        required: false,
        ownership: "needs_brad",
        reusableKey: "screenshot-next-session-tease-list",
        estimatedMinutes: 5,
      },
      {
        key: "returning-viewer-callout",
        assetType: "screenshot",
        title: "Returning viewer called out by name in chat",
        description: "LIVE chat showing a returning username being recognized by the host",
        purpose: "Shows what recognition looks like in the actual chat feed",
        placement: "Screenshots section",
        captureInstructions: "Screenshot a LIVE chat moment where a returning viewer is welcomed back by username. Blur any unrelated usernames or sensitive comments.",
        cropBlur: "Blur unrelated usernames/comments not part of the example",
        caption: "Recognizing a returning name out loud is free and it works.",
        alt: "TikTok LIVE chat showing a returning viewer recognized by username",
        priority: "helpful",
        required: false,
        ownership: "needs_brad",
        privacyWarning: "Only use usernames with consent or already public; blur unrelated chat.",
        reusableKey: "screenshot-returning-viewer-callout",
        estimatedMinutes: 5,
      },
      {
        key: "weekly-schedule-closing-note",
        assetType: "screenshot",
        title: "Simple weekly schedule shared at close",
        description: "A simple weekly schedule note shared during a closing block",
        purpose: "Shows the schedule habit that anchors the weekly system",
        placement: "Screenshots section",
        captureInstructions: "Screenshot or photo of a simple written weekly schedule (days/times) as it might be shared on-screen or in a caption during closing.",
        caption: "A visible schedule turns 'sometime' into a habit viewers can plan around.",
        alt: "Simple weekly livestream schedule note shared during a closing segment",
        priority: "optional",
        required: false,
        ownership: "needs_brad",
        estimatedMinutes: 5,
      },
      {
        key: "continuity-chain",
        assetType: "diagram",
        title: "Last → This → Next continuity chain",
        description: "Three linked nodes — last stream, this stream, next stream — connected by an explicit callback and tease",
        purpose: "Visual anchor for the Mastery capstone continuity concept",
        placement: "Diagrams — after the continuity chain teaching",
        captureInstructions: "Three linked nodes: Last stream → This stream → Next stream, each labeled with the connecting action (callback / tease). Cursor can generate branded SVG.",
        caption: "Continuity is a chain you build out loud, one session at a time.",
        alt: "Diagram linking last, this, and next livestream for return viewers",
        priority: "helpful",
        required: false,
        ownership: "cursor_can_create",
        cursorCanGenerate: true,
        reusableKey: "diagram-continuity-chain",
        estimatedMinutes: 15,
      },
      {
        key: "founder-repeat-viewer-habit",
        assetType: "founder_story",
        title: "Founder insight — building the return-viewer habit",
        description: "Brad: the moment he noticed continuity, not content quality alone, was driving repeat viewers",
        purpose: "Grounds the continuity-chain principle in one specific, verified memory",
        placement: "From Brad's Experience enhancement",
        captureInstructions:
          "Ask Brad: Was there a moment you noticed a viewer coming back specifically because of something you said last time or teased for next time — what happened? 80–120 words. May paraphrase with approval. Never invent if no clear memory.",
        founderQuestion:
          "Was there a specific moment you noticed a viewer coming back because of a callback or tease you'd made, rather than just the content itself?",
        caption: "From Brad's experience",
        alt: "",
        priority: "helpful",
        required: false,
        ownership: "brad_must_approve",
        estimatedMinutes: 10,
      },
    ]),
  ),
  brief(
    "understanding-battles",
    assetsFor([
      {
        key: "battle-split-screen-ui",
        assetType: "screenshot",
        title: "Live battle split-screen with gift bar and timer",
        description: "A live TikTok battle split-screen view showing the gift bar and round timer",
        purpose: "Shows the format's anatomy before a learner ever enters one",
        placement: "Screenshots — after the battle format is introduced",
        captureInstructions: "Capture a battle UI (yours or public, with permission) showing both rooms, the gift/points bar, and the round timer. Blur unrelated viewer usernames/comments.",
        highlight: "Gift/points bar and round timer",
        cropBlur: "Blur unrelated viewer usernames or comments",
        caption: "A battle is two rooms and a shared scoreboard, nothing more mysterious than that.",
        alt: "TikTok LIVE battle split-screen interface with gift bar and round timer",
        priority: "helpful",
        required: false,
        ownership: "needs_brad",
        privacyWarning: "Only use footage you have rights to or that is already public; blur unrelated viewers.",
        reusableKey: "screenshot-battle-split-screen-ui",
        estimatedMinutes: 8,
      },
      {
        key: "battle-hub-upcoming-list",
        assetType: "screenshot",
        title: "Battle Hub upcoming battles list",
        description: "Battle Hub's upcoming battles list showing scheduled network matchups",
        purpose: "Connects battle theory to the real network tool learners will use later",
        placement: "Screenshots / links",
        captureInstructions: "Screenshot the Battle Hub upcoming-battles list (logged-in admin/member view OK if non-sensitive data is not shown).",
        caption: "Watching a scheduled matchup is the fastest way to see the format in action.",
        alt: "Streamer Factory Battle Hub list of upcoming scheduled battles",
        priority: "optional",
        required: false,
        ownership: "cursor_can_create",
        reusableKey: "screenshot-battle-hub-upcoming",
        estimatedMinutes: 5,
      },
      {
        key: "battle-scoreboard-end-of-round",
        assetType: "screenshot",
        title: "End-of-round scoreboard with final totals",
        description: "An end-of-round scoreboard screen showing final point totals for both hosts",
        purpose: "Shows what a resolved round actually looks like",
        placement: "Screenshots section",
        captureInstructions: "Capture the end-of-round results screen with final point totals for both sides visible. Blur unrelated viewer data.",
        caption: "The scoreboard is the story's ending, not the whole story.",
        alt: "TikTok LIVE battle end-of-round scoreboard with final point totals",
        priority: "optional",
        required: false,
        ownership: "needs_brad",
        estimatedMinutes: 5,
      },
      {
        key: "battle-mechanic-diagram",
        assetType: "diagram",
        title: "Battle mechanic flow",
        description: "Gifts convert to points → points move the bar → timer ends → higher side wins the round",
        purpose: "Demystifies the mechanic in one glance before learners watch a real battle",
        placement: "Diagrams — after mechanic explanation",
        captureInstructions: "Linear flow diagram: Gift sent → converts to points → points move shared bar → round timer ends → higher side wins round. Cursor can generate branded SVG.",
        caption: "Four steps, no mystery: gift, points, bar, timer.",
        alt: "Flow diagram of how gifts become points and decide a TikTok battle round",
        priority: "helpful",
        required: false,
        ownership: "cursor_can_create",
        cursorCanGenerate: true,
        reusableKey: "diagram-battle-mechanic-flow",
        estimatedMinutes: 15,
      },
      {
        key: "battle-viewer-psychology-diagram",
        assetType: "diagram",
        title: "Viewer psychology inside a battle",
        description: "Tribalism, urgency, status, and borrowed trust — all created by the battle format itself",
        purpose: "Explains why battles feel higher-energy than solo LIVEs without crediting any one host's skill alone",
        placement: "Diagrams",
        captureInstructions: "Four-quadrant or four-callout graphic labeled Tribalism, Urgency, Status, Borrowed Trust, each with a one-line explanation. Cursor can generate branded SVG.",
        caption: "The format itself generates energy — that's a tool, not a personal failure if your solo room feels calmer.",
        alt: "Diagram of four psychological effects that make TikTok battles feel high-energy",
        priority: "helpful",
        required: false,
        ownership: "cursor_can_create",
        cursorCanGenerate: true,
        reusableKey: "diagram-battle-viewer-psychology",
        estimatedMinutes: 15,
      },
      {
        key: "founder-first-battle-watched",
        assetType: "founder_story",
        title: "Founder insight — the first battle that changed his view",
        description: "Brad: the first battle he watched or ran that reframed what battles are for",
        purpose: "Grounds the 'scoreboard as story, not the whole story' framing in a verified memory",
        placement: "From Brad's Experience enhancement",
        captureInstructions:
          "Ask Brad: What was the first TikTok battle you watched or took part in that changed how you thought about the format — what surprised you? 80–120 words. May paraphrase with approval. Never invent if no clear memory.",
        founderQuestion:
          "What was the first battle you watched or took part in that changed how you thought about the format — what surprised you?",
        caption: "From Brad's experience",
        alt: "",
        priority: "helpful",
        required: false,
        ownership: "brad_must_approve",
        estimatedMinutes: 10,
      },
    ]),
  ),
  brief(
    "preparing-for-your-first-battle",
    assetsFor([
      {
        key: "battle-hub-scheduler-form",
        assetType: "screenshot",
        title: "Battle Hub scheduler form",
        description: "Battle Hub scheduler form showing date, time, and format fields",
        purpose: "Shows learners exactly what confirming a battle date looks like",
        placement: "Screenshots — after scheduling is introduced",
        captureInstructions: "Screenshot the Battle Hub scheduler form with date, time, and format fields visible and empty or filled with placeholder data (no real partner's private info).",
        caption: "A confirmed date has a form behind it, not just a DM that trails off.",
        alt: "Battle Hub scheduling form with date, time, and format fields",
        priority: "helpful",
        required: false,
        ownership: "needs_brad",
        reusableKey: "screenshot-battle-hub-scheduler",
        estimatedMinutes: 5,
      },
      {
        key: "promo-caption-hashtags",
        assetType: "screenshot",
        title: "Promo video caption with hashtags",
        description: "A promo video caption with three to five relevant hashtags",
        purpose: "Makes the promotion-funnel copy step concrete and copyable",
        placement: "Screenshots section",
        captureInstructions: "Screenshot a short promo video's caption field showing 3–5 relevant hashtags alongside the battle announcement text.",
        caption: "A few relevant hashtags outperform a caption stuffed with unrelated tags.",
        alt: "TikTok video caption announcing a battle with three to five relevant hashtags",
        priority: "helpful",
        required: false,
        ownership: "needs_brad",
        estimatedMinutes: 5,
      },
      {
        key: "story-countdown-reminder",
        assetType: "screenshot",
        title: "Story post with countdown sticker",
        description: "A story post with a countdown sticker reminding viewers of an upcoming LIVE",
        purpose: "Shows the second promotion touchpoint in the funnel",
        placement: "Screenshots section",
        captureInstructions: "Screenshot a story post using a countdown sticker set to the battle's start time.",
        caption: "A countdown sticker does the reminding so you don't have to re-announce manually.",
        alt: "Social media story post with a countdown sticker for an upcoming battle",
        priority: "optional",
        required: false,
        ownership: "needs_brad",
        estimatedMinutes: 5,
      },
      {
        key: "promotion-funnel-diagram",
        assetType: "diagram",
        title: "Four-touchpoint promotion funnel",
        description: "Announcement video, hashtag post, story reminder, optional cross-post — spread across a day",
        purpose: "Gives learners a copyable promotion sequence instead of one panicked last-minute post",
        placement: "Diagrams — after promotion planning",
        captureInstructions: "Horizontal funnel/timeline with four touchpoints across a day: Announcement video → Hashtag post → Story countdown → Optional cross-post. Cursor can generate branded SVG.",
        caption: "Four small touchpoints beat one big scramble the hour before.",
        alt: "Diagram of a four-touchpoint promotion funnel for a first TikTok battle",
        priority: "helpful",
        required: false,
        ownership: "cursor_can_create",
        cursorCanGenerate: true,
        reusableKey: "diagram-promotion-funnel",
        estimatedMinutes: 15,
      },
      {
        key: "prep-checklist-gate-diagram",
        assetType: "diagram",
        title: "Prep checklist gate",
        description: "Account, tech, format, and partner agreement confirmed before any date is promoted",
        purpose: "Makes the prep-before-promotion order explicit so learners don't announce before they're ready",
        placement: "Diagrams",
        captureInstructions: "Gate/checklist diagram with four required checks (Account, Tech, Format, Partner Agreement) that must all pass before a 'Promote' arrow. Cursor can generate branded SVG.",
        caption: "Promotion happens after the checklist passes, not before.",
        alt: "Checklist gate diagram requiring account, tech, format, and partner agreement before promotion",
        priority: "helpful",
        required: false,
        ownership: "cursor_can_create",
        cursorCanGenerate: true,
        reusableKey: "diagram-prep-checklist-gate",
        estimatedMinutes: 15,
      },
      {
        key: "battle-day-checklist-shot",
        assetType: "photo",
        title: "Filled battle day checklist",
        description: "Printed or filled Battle Day Checklist showing partner, tech, and promotion steps checked off",
        purpose: "Models prep discipline as part of the performance, not an afterthought",
        placement: "Downloads",
        captureInstructions: "Photo or screenshot of a filled Battle Day Checklist download with realistic (non-identifying) example entries.",
        caption: "Prep is part of the performance.",
        alt: "Filled paper checklist for battle day preparation",
        priority: "optional",
        required: false,
        ownership: "needs_brad",
        estimatedMinutes: 5,
      },
      {
        key: "founder-first-battle-prep-lesson",
        assetType: "founder_story",
        title: "Founder insight — what he wishes he'd prepped before his first battle",
        description: "Brad: a specific gap in his own first-battle prep and what he'd tell a beginner",
        purpose: "Grounds the prep-before-execution principle in a verified, specific memory",
        placement: "From Brad's Experience enhancement",
        captureInstructions:
          "Ask Brad: What's one thing you wish you had prepared — partner agreement, tech check, or talk track — before your own first battle? What happened because you hadn't? 80–120 words. May paraphrase with approval. Never invent if no clear memory.",
        founderQuestion:
          "What's one thing you wish you had prepared — a partner agreement, a tech check, or a talk track — before your own first battle, and what happened because you hadn't?",
        caption: "From Brad's experience",
        alt: "",
        priority: "helpful",
        required: false,
        ownership: "brad_must_approve",
        estimatedMinutes: 10,
      },
    ]),
  ),
  brief(
    "structure-your-first-battle-week",
    assetsFor([
      {
        key: "hub-schedule",
        assetType: "screenshot",
        title: "Battle Hub schedule confirmation",
        description: "Scheduled battle with time/format visible",
        purpose: "Shows what ‘confirmed’ looks like in Hub",
        placement: "Main Lesson",
        captureInstructions: "Screenshot a scheduled battle card with date/time/format (no private DMs).",
        caption: "Soft maybes are not confirmations.",
        alt: "Battle Hub scheduled battle with date time and format",
        priority: "helpful",
        required: false,
        ownership: "needs_brad",
      },
    ]),
  ),
  brief(
    "improving-battle-performance",
    assetsFor([
      {
        key: "debrief-loop",
        assetType: "diagram",
        title: "Debrief → Drill → Rematch loop",
        description: "Improvement loop diagram",
        purpose: "Teaches iteration culture",
        placement: "Main Lesson",
        captureInstructions: "Three-step loop: Debrief, One fix drill, Rematch.",
        caption: "Iterate or repeat the same loss.",
        alt: "Loop diagram for battle debrief drill and rematch",
        priority: "helpful",
        required: false,
        ownership: "cursor_can_create",
        cursorCanGenerate: true,
      },
    ]),
  ),
  brief(
    "building-battle-partners",
    assetsFor([
      {
        key: "battle-finder",
        assetType: "screenshot",
        title: "Battle Finder",
        description: "Battle Finder partner search UI",
        purpose: "Shows where fit-based outreach starts",
        placement: "Main Lesson",
        captureInstructions: "Screenshot Battle Finder with no private messages visible.",
        caption: "Build a bench — don’t cold-start forever.",
        alt: "Streamer Factory Battle Finder interface",
        priority: "helpful",
        required: false,
        ownership: "needs_brad",
        reusableKey: "sf-battle-finder",
      },
    ]),
  ),
  brief(
    "gifts-goals-momentum",
    assetsFor([
      {
        key: "gift-panel",
        assetType: "screenshot",
        title: "Gift panel overview",
        description: "In-LIVE gift panel (generic)",
        purpose: "Supports gift literacy without focusing on diamond totals",
        placement: "Main Lesson",
        captureInstructions: "Screenshot gift panel from a practice LIVE; blur amounts if needed.",
        caption: "Understand the flow — culture before coercion.",
        alt: "TikTok LIVE gift panel shown during a stream",
        priority: "helpful",
        required: false,
        ownership: "needs_brad",
        privacyWarning: "Do not pressure real gifters into being identified.",
        reusableKey: "tiktok-gift-panel",
      },
      {
        key: "momentum-spectrum",
        assetType: "diagram",
        title: "Momentum vs begging spectrum",
        description: "Healthy momentum language vs guilt",
        purpose: "Ethics visual for monetization opener",
        placement: "Main Lesson",
        captureInstructions: "Spectrum: gratitude/momentum ←→ guilt/begging with example phrases.",
        caption: "Momentum is not begging.",
        alt: "Spectrum contrasting gift momentum language with begging",
        priority: "helpful",
        required: false,
        ownership: "cursor_can_create",
        cursorCanGenerate: true,
      },
    ]),
  ),
  brief(
    "creating-reasons-to-gift",
    assetsFor([
      {
        key: "value-stack",
        assetType: "diagram",
        title: "Value stack across 60 minutes",
        description: "Entertainment / milestone / utility spaced on timeline",
        purpose: "Shows three-category stacking",
        placement: "Diagrams — after Stacking three moments across one session",
        captureInstructions: "60m timeline with three spaced value moments labeled.",
        caption: "Would it hold up without an ask?",
        alt: "Timeline of three value moments across a sixty minute LIVE",
        priority: "helpful",
        required: false,
        ownership: "cursor_can_create",
        cursorCanGenerate: true,
        reusableKey: "diagram-value-stack",
        estimatedMinutes: 20,
      },
      {
        key: "honesty-test-diagram",
        assetType: "diagram",
        title: "The honesty test",
        description: "Would this moment hold up with gifting removed entirely?",
        purpose: "Makes the ethical self-check from this lesson memorable and reusable",
        placement: "Diagrams — after The honesty test for value moments",
        captureInstructions: "Simple two-branch flow: moment survives without an ask (keep) vs. collapses without an ask (rebuild). Streamer Factory brand colors.",
        caption: "Real value moments hold up on their own.",
        alt: "Flowchart testing whether a planned value moment survives without a gifting ask",
        priority: "helpful",
        required: false,
        ownership: "cursor_can_create",
        cursorCanGenerate: true,
        estimatedMinutes: 15,
      },
      {
        key: "founder-value-first",
        assetType: "founder_story",
        title: "Founder insight — building something worth supporting first",
        description: "Brad: what actually fixes a quiet gifting night — value moments, not more asking",
        purpose: "Reinforces the value-first, never-pressure teaching with verified experience",
        placement: "From Brad's Experience",
        captureInstructions:
          "Ask Brad: When you've seen a creator try to fix a quiet gifting night, what actually worked — asking more, or building something worth supporting first? 80–120 words. May paraphrase with approval.",
        founderQuestion:
          "When you've watched a creator try to fix a quiet gifting night, what actually worked — asking more often, or building something worth supporting first?",
        caption: "From Brad's experience",
        alt: "",
        priority: "helpful",
        required: false,
        ownership: "brad_must_approve",
        estimatedMinutes: 10,
      },
    ]),
  ),
  brief(
    "setting-goals-during-lives",
    assetsFor([
      {
        key: "three-checkpoints",
        assetType: "diagram",
        title: "Three-checkpoint timeline",
        description: "Start / mid / close goal frames",
        purpose: "Differentiates this lesson from gift literacy",
        placement: "Diagrams — after Checkpoint three: the closing frame",
        captureInstructions: "Timeline with three checkpoint flags and varied framing notes.",
        caption: "Three checkpoints, three frames — close anyway.",
        alt: "Timeline showing start midpoint and close goal checkpoints",
        priority: "helpful",
        required: false,
        ownership: "cursor_can_create",
        cursorCanGenerate: true,
        reusableKey: "diagram-three-checkpoints",
        estimatedMinutes: 20,
      },
      {
        key: "honest-adjustment-flow",
        assetType: "diagram",
        title: "Honest mid-stream adjustment flow",
        description: "Notice pace is off → announce the change out loud → keep going",
        purpose: "Makes the ethical adjustment habit concrete and repeatable",
        placement: "Diagrams — after Adjusting goals mid-stream, ethically",
        captureInstructions: "Three-step horizontal flow: Notice pace is off → Announce out loud → Keep going. Streamer Factory brand colors.",
        caption: "Say the quiet part out loud, every time.",
        alt: "Flow diagram for honestly announcing a mid-stream goal adjustment",
        priority: "helpful",
        required: false,
        ownership: "cursor_can_create",
        cursorCanGenerate: true,
        estimatedMinutes: 15,
      },
      {
        key: "founder-say-it-out-loud",
        assetType: "founder_story",
        title: "Founder insight — announcing goal changes out loud",
        description: "Brad: the trust difference between announcing a goal adjustment and moving it silently",
        purpose: "Reinforces the honest-adjustment habit with verified experience",
        placement: "From Brad's Experience",
        captureInstructions:
          "Ask Brad: What's the real difference you've seen between a creator who announces a goal change out loud and one who quietly moves the target? 80–120 words. Approve before publish.",
        founderQuestion:
          "What's the real difference you've seen between a creator who announces a mid-stream goal change out loud and one who quietly moves the target?",
        caption: "From Brad's experience",
        alt: "",
        priority: "helpful",
        required: false,
        ownership: "brad_must_approve",
        estimatedMinutes: 10,
      },
    ]),
  ),
  brief(
    "building-income-habits",
    assetsFor([
      {
        key: "weekly-log",
        assetType: "photo",
        title: "Weekly income log example",
        description: "Filled weekly income log (fake/sample numbers OK)",
        purpose: "Makes tracking concrete without obsessive mid-stream checks",
        placement: "Screenshots — after Tracking without obsessing",
        captureInstructions: "Photo of weekly log with sample totals — not a real creator’s private payouts.",
        caption: "Track weekly. Perform daily.",
        alt: "Sample weekly livestream income log worksheet",
        priority: "helpful",
        required: false,
        ownership: "needs_brad",
        privacyWarning: "Use sample numbers; never publish another creator’s private earnings.",
        estimatedMinutes: 10,
      },
      {
        key: "behavior-flywheel",
        assetType: "diagram",
        title: "Behavior → Income flywheel",
        description: "Repeatable behavior producing income identity",
        purpose: "Capstone identity visual",
        placement: "Diagrams — after Building the identity that outlasts any single night",
        captureInstructions: "Flywheel: show up → deliver value → track weekly → same standards either way.",
        caption: "Income is an output of repeatable behavior.",
        alt: "Flywheel diagram linking creator habits to sustainable income",
        priority: "helpful",
        required: false,
        ownership: "cursor_can_create",
        cursorCanGenerate: true,
        reusableKey: "diagram-behavior-flywheel",
        estimatedMinutes: 20,
      },
      {
        key: "founder-talent-vs-habit",
        assetType: "founder_story",
        title: "Founder insight — talent gets noticed, habits build careers",
        description: "Brad: what separated two similarly talented creators a year later",
        purpose: "Reinforces the tracking-and-pacing identity theme with verified experience",
        placement: "From Brad's Experience",
        captureInstructions:
          "Ask Brad: What have you seen separate two similarly talented creators a year apart — one still building, one burned out? 80–120 words. Approve before publish.",
        founderQuestion:
          "What have you seen separate two similarly talented creators a year apart — one still building, one burned out?",
        caption: "From Brad's experience",
        alt: "",
        priority: "helpful",
        required: false,
        ownership: "brad_must_approve",
        estimatedMinutes: 10,
      },
    ]),
  ),
  brief(
    "scaling-consistency",
    assetsFor([
      {
        key: "capacity-gauge",
        assetType: "diagram",
        title: "Capacity vs volume gauge",
        description: "Volume with quality constraint",
        purpose: "Anti-burnout visual",
        placement: "Diagrams — after What 'scaling' actually means here",
        captureInstructions: "Gauge or balance scale: volume vs quality/recovery.",
        caption: "Scale what you can sustain.",
        alt: "Diagram balancing livestream volume against quality and recovery",
        priority: "helpful",
        required: false,
        ownership: "cursor_can_create",
        cursorCanGenerate: true,
        reusableKey: "diagram-capacity-gauge",
        estimatedMinutes: 20,
      },
      {
        key: "weekly-calendar-diagram",
        assetType: "diagram",
        title: "Weekly calendar with recovery days",
        description: "Stacked and single-session days plus two protected recovery days",
        purpose: "Makes a sustainable weekly volume plan concrete",
        placement: "Diagrams — after Recovery as a planned input, not an afterthought",
        captureInstructions: "Seven-day grid with session lengths blocked in and two days marked as recovery. Streamer Factory brand colors.",
        caption: "Recovery is part of the plan, not an afterthought.",
        alt: "Weekly calendar diagram showing streaming days and protected recovery days",
        priority: "helpful",
        required: false,
        ownership: "cursor_can_create",
        cursorCanGenerate: true,
        estimatedMinutes: 15,
      },
      {
        key: "founder-final-lesson",
        assetType: "founder_story",
        title: "Founder insight — the creators still building years later",
        description: "Brad: what separates creators still building a career years later from those who burned out fast",
        purpose: "Closes the published path with verified, honest founder perspective",
        placement: "From Brad's Experience",
        captureInstructions:
          "Ask Brad: Of the creators you've seen scale their volume, what separated the ones still building years later from the ones who burned out fast? 80–120 words. Approve before publish.",
        founderQuestion:
          "Of the creators you've seen scale their streaming volume, what separated the ones still building years later from the ones who burned out fast?",
        caption: "From Brad's experience",
        alt: "",
        priority: "helpful",
        required: false,
        ownership: "brad_must_approve",
        estimatedMinutes: 10,
      },
    ]),
  ),
];

export const LESSON_PRODUCTION_BRIEFS: LessonProductionBrief[] = [LESSON_1, ...REST].sort(
  (a, b) => a.globalOrder - b.globalOrder,
);

export function getBriefForLesson(slug: string): LessonProductionBrief | null {
  return LESSON_PRODUCTION_BRIEFS.find((b) => b.lessonSlug === slug) ?? null;
}

export function listAllBriefAssets(): Array<BriefAsset & { lessonSlug: string; lessonTitle: string }> {
  return LESSON_PRODUCTION_BRIEFS.flatMap((b) =>
    b.assets.map((a) => ({ ...a, lessonSlug: b.lessonSlug, lessonTitle: b.lessonTitle })),
  );
}
