import type { LessonSeoPack } from "@/lib/resources/lesson-seo/types";

export const BRAND_PARTNERSHIPS_MASTERY_LESSON_SEO: LessonSeoPack[] = [
  {
    slug: "understanding-brand-partnerships",
    primaryKeyword: "understanding brand partnerships for creators",
    secondaryKeywords: ["brand partnerships", "creator sponsorship", "EPK", "Professional Brand Partnership Portfolio"],
    metaTitle: "Understanding Brand Partnerships | StreamerU",
    metaDescription: "Learn how brand partnerships work, what brands evaluate, and how to align deals with your values and audience.",
    faqs: [
      { question: "What does this Brand Partnerships lesson teach?", answer: "Understanding Brand Partnerships teaches practical partnership readiness with dated artifacts and a LIVE Mission graded on professional evidence, not deal closure." },
      { question: "Is this legal or contract advice?", answer: "No. It is general creator education. Binding contract, tax, and compliance questions belong with qualified professionals." },
      { question: "Does this replace TikTok Shop or Professional Creator Mastery?", answer: "No. TikTok Shop covers shop mechanics; Professional Creator covers business accounting; this path covers brand partnership readiness and EPK building." },
      { question: "How is the mission graded?", answer: "By completed artifacts and one implemented improvement. Deals closed, gifts, viewers, and rank are not grading targets." },
      { question: "What evidence do I leave with?", answer: "You leave with brand-readiness-checklist, partnership-types-map, brand-safety-values-card and evidence for the Professional Brand Partnership Portfolio." },
    ],
    relatedGuideSlugs: ["creator-support", "brand-deals", "monetization"],
    internalLinks: [
      { label: "StreamerU hub", href: "/streameru" },
      { label: "Next: Building Your Professional Creator Profile", href: "/streameru/building-your-professional-creator-profile" },
      { label: "Professional Creator Mastery", href: "/streameru/programs/professional" },
    ],
    suggestedGlossaryTerms: [
      { title: "Electronic press kit (EPK)", intent: "A structured creator media kit brands use to evaluate fit, stats, and samples." },
      { title: "Brand fit", intent: "How well a brand's audience, values, and category match your content and community." },
    ],
    suggestedDownloads: [
      { title: "brand-readiness-checklist", intent: "Primary partnership artifact." },
      { title: "partnership-types-map", intent: "Planning artifact." },
      { title: "brand-safety-values-card", intent: "Evidence and review artifact." },
    ],
    suggestedBlogSupport: [{ title: "Professional brand partnerships for live creators", intent: "Support sponsorship readiness without hype or hidden ads." }],
  },
  {
    slug: "building-your-professional-creator-profile",
    primaryKeyword: "building your professional creator profile for creators",
    secondaryKeywords: ["brand partnerships", "creator sponsorship", "EPK", "Professional Brand Partnership Portfolio"],
    metaTitle: "Building Your Professional Creator Profile | StreamerU",
    metaDescription: "Craft a professional creator identity—bio, audience overview, and portfolio samples—that brand teams can evaluate quickly.",
    faqs: [
      { question: "What does this Brand Partnerships lesson teach?", answer: "Building Your Professional Creator Profile teaches practical partnership readiness with dated artifacts and a LIVE Mission graded on professional evidence, not deal closure." },
      { question: "Is this legal or contract advice?", answer: "No. It is general creator education. Binding contract, tax, and compliance questions belong with qualified professionals." },
      { question: "Does this replace TikTok Shop or Professional Creator Mastery?", answer: "No. TikTok Shop covers shop mechanics; Professional Creator covers business accounting; this path covers brand partnership readiness and EPK building." },
      { question: "How is the mission graded?", answer: "By completed artifacts and one implemented improvement. Deals closed, gifts, viewers, and rank are not grading targets." },
      { question: "What evidence do I leave with?", answer: "You leave with creator-bio-worksheet, audience-overview-worksheet, portfolio-selection-guide and evidence for the Professional Brand Partnership Portfolio." },
    ],
    relatedGuideSlugs: ["creator-support", "brand-deals", "monetization"],
    internalLinks: [
      { label: "Previous: Understanding Brand Partnerships", href: "/streameru/understanding-brand-partnerships" },
      { label: "Next: Creating an Electronic Press Kit (EPK)", href: "/streameru/creating-an-electronic-press-kit" },
      { label: "Professional Creator Mastery", href: "/streameru/programs/professional" },
    ],
    suggestedGlossaryTerms: [
      { title: "Electronic press kit (EPK)", intent: "A structured creator media kit brands use to evaluate fit, stats, and samples." },
      { title: "Brand fit", intent: "How well a brand's audience, values, and category match your content and community." },
    ],
    suggestedDownloads: [
      { title: "creator-bio-worksheet", intent: "Primary partnership artifact." },
      { title: "audience-overview-worksheet", intent: "Planning artifact." },
      { title: "portfolio-selection-guide", intent: "Evidence and review artifact." },
    ],
    suggestedBlogSupport: [{ title: "Professional brand partnerships for live creators", intent: "Support sponsorship readiness without hype or hidden ads." }],
  },
  {
    slug: "creating-an-electronic-press-kit",
    primaryKeyword: "creating an electronic press kit (epk) for creators",
    secondaryKeywords: ["brand partnerships", "creator sponsorship", "EPK", "Professional Brand Partnership Portfolio"],
    metaTitle: "Creating an Electronic Press Kit (EPK) | StreamerU",
    metaDescription: "Build a complete EPK with every field a brand team expects—bio, stats, demographics, samples, assets, and share link.",
    faqs: [
      { question: "What does this Brand Partnerships lesson teach?", answer: "Creating an Electronic Press Kit (EPK) teaches practical partnership readiness with dated artifacts and a LIVE Mission graded on professional evidence, not deal closure." },
      { question: "Is this legal or contract advice?", answer: "No. It is general creator education. Binding contract, tax, and compliance questions belong with qualified professionals." },
      { question: "Does this replace TikTok Shop or Professional Creator Mastery?", answer: "No. TikTok Shop covers shop mechanics; Professional Creator covers business accounting; this path covers brand partnership readiness and EPK building." },
      { question: "How is the mission graded?", answer: "By completed artifacts and one implemented improvement. Deals closed, gifts, viewers, and rank are not grading targets." },
      { question: "What evidence do I leave with?", answer: "You leave with epk-field-worksheet, media-kit-layout-checklist, epk-assets-inventory and evidence for the Professional Brand Partnership Portfolio." },
    ],
    relatedGuideSlugs: ["creator-support", "brand-deals", "monetization"],
    internalLinks: [
      { label: "Previous: Building Your Professional Creator Profile", href: "/streameru/building-your-professional-creator-profile" },
      { label: "Next: Finding Brands That Fit Your Audience", href: "/streameru/finding-brands-that-fit-your-audience" },
      { label: "Professional Creator Mastery", href: "/streameru/programs/professional" },
    ],
    suggestedGlossaryTerms: [
      { title: "Electronic press kit (EPK)", intent: "A structured creator media kit brands use to evaluate fit, stats, and samples." },
      { title: "Brand fit", intent: "How well a brand's audience, values, and category match your content and community." },
    ],
    suggestedDownloads: [
      { title: "epk-field-worksheet", intent: "Primary partnership artifact." },
      { title: "media-kit-layout-checklist", intent: "Planning artifact." },
      { title: "epk-assets-inventory", intent: "Evidence and review artifact." },
    ],
    suggestedBlogSupport: [{ title: "Professional brand partnerships for live creators", intent: "Support sponsorship readiness without hype or hidden ads." }],
  },
  {
    slug: "finding-brands-that-fit-your-audience",
    primaryKeyword: "finding brands that fit your audience for creators",
    secondaryKeywords: ["brand partnerships", "creator sponsorship", "EPK", "Professional Brand Partnership Portfolio"],
    metaTitle: "Finding Brands That Fit Your Audience | StreamerU",
    metaDescription: "Research and score brands that genuinely match your audience, values, and content—not every logo with a budget.",
    faqs: [
      { question: "What does this Brand Partnerships lesson teach?", answer: "Finding Brands That Fit Your Audience teaches practical partnership readiness with dated artifacts and a LIVE Mission graded on professional evidence, not deal closure." },
      { question: "Is this legal or contract advice?", answer: "No. It is general creator education. Binding contract, tax, and compliance questions belong with qualified professionals." },
      { question: "Does this replace TikTok Shop or Professional Creator Mastery?", answer: "No. TikTok Shop covers shop mechanics; Professional Creator covers business accounting; this path covers brand partnership readiness and EPK building." },
      { question: "How is the mission graded?", answer: "By completed artifacts and one implemented improvement. Deals closed, gifts, viewers, and rank are not grading targets." },
      { question: "What evidence do I leave with?", answer: "You leave with brand-fit-scorecard, sponsorship-tracker, target-brand-research-sheet and evidence for the Professional Brand Partnership Portfolio." },
    ],
    relatedGuideSlugs: ["creator-support", "brand-deals", "monetization"],
    internalLinks: [
      { label: "Previous: Creating an Electronic Press Kit (EPK)", href: "/streameru/creating-an-electronic-press-kit" },
      { label: "Next: Professional Outreach & Communication", href: "/streameru/professional-outreach-and-communication" },
      { label: "Professional Creator Mastery", href: "/streameru/programs/professional" },
    ],
    suggestedGlossaryTerms: [
      { title: "Electronic press kit (EPK)", intent: "A structured creator media kit brands use to evaluate fit, stats, and samples." },
      { title: "Brand fit", intent: "How well a brand's audience, values, and category match your content and community." },
    ],
    suggestedDownloads: [
      { title: "brand-fit-scorecard", intent: "Primary partnership artifact." },
      { title: "sponsorship-tracker", intent: "Planning artifact." },
      { title: "target-brand-research-sheet", intent: "Evidence and review artifact." },
    ],
    suggestedBlogSupport: [{ title: "Professional brand partnerships for live creators", intent: "Support sponsorship readiness without hype or hidden ads." }],
  },
  {
    slug: "professional-outreach-and-communication",
    primaryKeyword: "professional outreach & communication for creators",
    secondaryKeywords: ["brand partnerships", "creator sponsorship", "EPK", "Professional Brand Partnership Portfolio"],
    metaTitle: "Professional Outreach & Communication | StreamerU",
    metaDescription: "Write clear outreach, planned follow-ups, and professional intros that respect brand time and your reputation.",
    faqs: [
      { question: "What does this Brand Partnerships lesson teach?", answer: "Professional Outreach & Communication teaches practical partnership readiness with dated artifacts and a LIVE Mission graded on professional evidence, not deal closure." },
      { question: "Is this legal or contract advice?", answer: "No. It is general creator education. Binding contract, tax, and compliance questions belong with qualified professionals." },
      { question: "Does this replace TikTok Shop or Professional Creator Mastery?", answer: "No. TikTok Shop covers shop mechanics; Professional Creator covers business accounting; this path covers brand partnership readiness and EPK building." },
      { question: "How is the mission graded?", answer: "By completed artifacts and one implemented improvement. Deals closed, gifts, viewers, and rank are not grading targets." },
      { question: "What evidence do I leave with?", answer: "You leave with outreach-email-templates, follow-up-cadence-card, linkedin-intro-checklist and evidence for the Professional Brand Partnership Portfolio." },
    ],
    relatedGuideSlugs: ["creator-support", "brand-deals", "monetization"],
    internalLinks: [
      { label: "Previous: Finding Brands That Fit Your Audience", href: "/streameru/finding-brands-that-fit-your-audience" },
      { label: "Next: Negotiating Sponsorships Professionally", href: "/streameru/negotiating-sponsorships-professionally" },
      { label: "Professional Creator Mastery", href: "/streameru/programs/professional" },
    ],
    suggestedGlossaryTerms: [
      { title: "Electronic press kit (EPK)", intent: "A structured creator media kit brands use to evaluate fit, stats, and samples." },
      { title: "Brand fit", intent: "How well a brand's audience, values, and category match your content and community." },
    ],
    suggestedDownloads: [
      { title: "outreach-email-templates", intent: "Primary partnership artifact." },
      { title: "follow-up-cadence-card", intent: "Planning artifact." },
      { title: "linkedin-intro-checklist", intent: "Evidence and review artifact." },
    ],
    suggestedBlogSupport: [{ title: "Professional brand partnerships for live creators", intent: "Support sponsorship readiness without hype or hidden ads." }],
  },
  {
    slug: "negotiating-sponsorships-professionally",
    primaryKeyword: "negotiating sponsorships professionally for creators",
    secondaryKeywords: ["brand partnerships", "creator sponsorship", "EPK", "Professional Brand Partnership Portfolio"],
    metaTitle: "Negotiating Sponsorships Professionally | StreamerU",
    metaDescription: "Define scope, rate packages, and high-level deal terms—with clear boundaries on legal advice.",
    faqs: [
      { question: "What does this Brand Partnerships lesson teach?", answer: "Negotiating Sponsorships Professionally teaches practical partnership readiness with dated artifacts and a LIVE Mission graded on professional evidence, not deal closure." },
      { question: "Is this legal or contract advice?", answer: "No. It is general creator education. Binding contract, tax, and compliance questions belong with qualified professionals." },
      { question: "Does this replace TikTok Shop or Professional Creator Mastery?", answer: "No. TikTok Shop covers shop mechanics; Professional Creator covers business accounting; this path covers brand partnership readiness and EPK building." },
      { question: "How is the mission graded?", answer: "By completed artifacts and one implemented improvement. Deals closed, gifts, viewers, and rank are not grading targets." },
      { question: "What evidence do I leave with?", answer: "You leave with negotiation-scope-worksheet, rate-card-planner, deal-terms-checklist and evidence for the Professional Brand Partnership Portfolio." },
    ],
    relatedGuideSlugs: ["creator-support", "brand-deals", "monetization"],
    internalLinks: [
      { label: "Previous: Professional Outreach & Communication", href: "/streameru/professional-outreach-and-communication" },
      { label: "Next: Delivering Outstanding Campaigns", href: "/streameru/delivering-outstanding-campaigns" },
      { label: "Professional Creator Mastery", href: "/streameru/programs/professional" },
    ],
    suggestedGlossaryTerms: [
      { title: "Electronic press kit (EPK)", intent: "A structured creator media kit brands use to evaluate fit, stats, and samples." },
      { title: "Brand fit", intent: "How well a brand's audience, values, and category match your content and community." },
    ],
    suggestedDownloads: [
      { title: "negotiation-scope-worksheet", intent: "Primary partnership artifact." },
      { title: "rate-card-planner", intent: "Planning artifact." },
      { title: "deal-terms-checklist", intent: "Evidence and review artifact." },
    ],
    suggestedBlogSupport: [{ title: "Professional brand partnerships for live creators", intent: "Support sponsorship readiness without hype or hidden ads." }],
  },
  {
    slug: "delivering-outstanding-campaigns",
    primaryKeyword: "delivering outstanding campaigns for creators",
    secondaryKeywords: ["brand partnerships", "creator sponsorship", "EPK", "Professional Brand Partnership Portfolio"],
    metaTitle: "Delivering Outstanding Campaigns | StreamerU",
    metaDescription: "Plan campaigns, hit deliverables, disclose sponsorships clearly, and capture proof without cutting corners.",
    faqs: [
      { question: "What does this Brand Partnerships lesson teach?", answer: "Delivering Outstanding Campaigns teaches practical partnership readiness with dated artifacts and a LIVE Mission graded on professional evidence, not deal closure." },
      { question: "Is this legal or contract advice?", answer: "No. It is general creator education. Binding contract, tax, and compliance questions belong with qualified professionals." },
      { question: "Does this replace TikTok Shop or Professional Creator Mastery?", answer: "No. TikTok Shop covers shop mechanics; Professional Creator covers business accounting; this path covers brand partnership readiness and EPK building." },
      { question: "How is the mission graded?", answer: "By completed artifacts and one implemented improvement. Deals closed, gifts, viewers, and rank are not grading targets." },
      { question: "What evidence do I leave with?", answer: "You leave with campaign-planner, deliverables-checklist, ftc-disclosure-reminder-card and evidence for the Professional Brand Partnership Portfolio." },
    ],
    relatedGuideSlugs: ["creator-support", "brand-deals", "monetization"],
    internalLinks: [
      { label: "Previous: Negotiating Sponsorships Professionally", href: "/streameru/negotiating-sponsorships-professionally" },
      { label: "Next: Reporting Results & Building Repeat Business", href: "/streameru/reporting-results-and-building-repeat-business" },
      { label: "Professional Creator Mastery", href: "/streameru/programs/professional" },
    ],
    suggestedGlossaryTerms: [
      { title: "Electronic press kit (EPK)", intent: "A structured creator media kit brands use to evaluate fit, stats, and samples." },
      { title: "Brand fit", intent: "How well a brand's audience, values, and category match your content and community." },
    ],
    suggestedDownloads: [
      { title: "campaign-planner", intent: "Primary partnership artifact." },
      { title: "deliverables-checklist", intent: "Planning artifact." },
      { title: "ftc-disclosure-reminder-card", intent: "Evidence and review artifact." },
    ],
    suggestedBlogSupport: [{ title: "Professional brand partnerships for live creators", intent: "Support sponsorship readiness without hype or hidden ads." }],
  },
  {
    slug: "reporting-results-and-building-repeat-business",
    primaryKeyword: "reporting results & building repeat business for creators",
    secondaryKeywords: ["brand partnerships", "creator sponsorship", "EPK", "Professional Brand Partnership Portfolio"],
    metaTitle: "Reporting Results & Building Repeat Business | StreamerU",
    metaDescription: "Write honest campaign reports, plan renewal conversations, and document proof metrics brands can trust.",
    faqs: [
      { question: "What does this Brand Partnerships lesson teach?", answer: "Reporting Results & Building Repeat Business teaches practical partnership readiness with dated artifacts and a LIVE Mission graded on professional evidence, not deal closure." },
      { question: "Is this legal or contract advice?", answer: "No. It is general creator education. Binding contract, tax, and compliance questions belong with qualified professionals." },
      { question: "Does this replace TikTok Shop or Professional Creator Mastery?", answer: "No. TikTok Shop covers shop mechanics; Professional Creator covers business accounting; this path covers brand partnership readiness and EPK building." },
      { question: "How is the mission graded?", answer: "By completed artifacts and one implemented improvement. Deals closed, gifts, viewers, and rank are not grading targets." },
      { question: "What evidence do I leave with?", answer: "You leave with campaign-report-template, renewal-conversation-checklist, proof-metrics-worksheet and evidence for the Professional Brand Partnership Portfolio." },
    ],
    relatedGuideSlugs: ["creator-support", "brand-deals", "monetization"],
    internalLinks: [
      { label: "Previous: Delivering Outstanding Campaigns", href: "/streameru/delivering-outstanding-campaigns" },
      { label: "Next: Becoming a Long-Term Brand Partner", href: "/streameru/becoming-a-long-term-brand-partner" },
      { label: "Professional Creator Mastery", href: "/streameru/programs/professional" },
    ],
    suggestedGlossaryTerms: [
      { title: "Electronic press kit (EPK)", intent: "A structured creator media kit brands use to evaluate fit, stats, and samples." },
      { title: "Brand fit", intent: "How well a brand's audience, values, and category match your content and community." },
    ],
    suggestedDownloads: [
      { title: "campaign-report-template", intent: "Primary partnership artifact." },
      { title: "renewal-conversation-checklist", intent: "Planning artifact." },
      { title: "proof-metrics-worksheet", intent: "Evidence and review artifact." },
    ],
    suggestedBlogSupport: [{ title: "Professional brand partnerships for live creators", intent: "Support sponsorship readiness without hype or hidden ads." }],
  },
  {
    slug: "becoming-a-long-term-brand-partner",
    primaryKeyword: "becoming a long-term brand partner for creators",
    secondaryKeywords: ["brand partnerships", "creator sponsorship", "EPK", "Professional Brand Partnership Portfolio"],
    metaTitle: "Becoming a Long-Term Brand Partner | StreamerU",
    metaDescription: "Maintain relationships between campaigns, protect reputation, and plan multi-month partnership roadmaps.",
    faqs: [
      { question: "What does this Brand Partnerships lesson teach?", answer: "Becoming a Long-Term Brand Partner teaches practical partnership readiness with dated artifacts and a LIVE Mission graded on professional evidence, not deal closure." },
      { question: "Is this legal or contract advice?", answer: "No. It is general creator education. Binding contract, tax, and compliance questions belong with qualified professionals." },
      { question: "Does this replace TikTok Shop or Professional Creator Mastery?", answer: "No. TikTok Shop covers shop mechanics; Professional Creator covers business accounting; this path covers brand partnership readiness and EPK building." },
      { question: "How is the mission graded?", answer: "By completed artifacts and one implemented improvement. Deals closed, gifts, viewers, and rank are not grading targets." },
      { question: "What evidence do I leave with?", answer: "You leave with brand-relationship-planner, reputation-scorecard, partnership-renewal-roadmap and evidence for the Professional Brand Partnership Portfolio." },
    ],
    relatedGuideSlugs: ["creator-support", "brand-deals", "monetization"],
    internalLinks: [
      { label: "Previous: Reporting Results & Building Repeat Business", href: "/streameru/reporting-results-and-building-repeat-business" },
      { label: "Next: Brand Partnerships Capstone: Professional Portfolio", href: "/streameru/brand-partnerships-capstone-professional-portfolio" },
      { label: "Professional Creator Mastery", href: "/streameru/programs/professional" },
    ],
    suggestedGlossaryTerms: [
      { title: "Electronic press kit (EPK)", intent: "A structured creator media kit brands use to evaluate fit, stats, and samples." },
      { title: "Brand fit", intent: "How well a brand's audience, values, and category match your content and community." },
    ],
    suggestedDownloads: [
      { title: "brand-relationship-planner", intent: "Primary partnership artifact." },
      { title: "reputation-scorecard", intent: "Planning artifact." },
      { title: "partnership-renewal-roadmap", intent: "Evidence and review artifact." },
    ],
    suggestedBlogSupport: [{ title: "Professional brand partnerships for live creators", intent: "Support sponsorship readiness without hype or hidden ads." }],
  },
  {
    slug: "brand-partnerships-capstone-professional-portfolio",
    primaryKeyword: "brand partnerships capstone: professional portfolio for creators",
    secondaryKeywords: ["brand partnerships", "creator sponsorship", "EPK", "Professional Brand Partnership Portfolio"],
    metaTitle: "Brand Partnerships Capstone: Professional Portfolio | StreamerU",
    metaDescription: "Assemble every partnership artifact and EPK field into one reviewable Professional Brand Partnership Portfolio.",
    faqs: [
      { question: "What does this Brand Partnerships lesson teach?", answer: "Brand Partnerships Capstone: Professional Portfolio teaches practical partnership readiness with dated artifacts and a LIVE Mission graded on professional evidence, not deal closure." },
      { question: "Is this legal or contract advice?", answer: "No. It is general creator education. Binding contract, tax, and compliance questions belong with qualified professionals." },
      { question: "Does this replace TikTok Shop or Professional Creator Mastery?", answer: "No. TikTok Shop covers shop mechanics; Professional Creator covers business accounting; this path covers brand partnership readiness and EPK building." },
      { question: "How is the mission graded?", answer: "By completed artifacts and one implemented improvement. Deals closed, gifts, viewers, and rank are not grading targets." },
      { question: "What evidence do I leave with?", answer: "You leave with professional-brand-partnership-portfolio, epk-evidence-checklist, ninety-day-partnership-improvement-plan and evidence for the Professional Brand Partnership Portfolio." },
    ],
    relatedGuideSlugs: ["creator-support", "brand-deals", "monetization"],
    internalLinks: [
      { label: "Previous: Becoming a Long-Term Brand Partner", href: "/streameru/becoming-a-long-term-brand-partner" },
      { label: "Brand Partnerships Program Final", href: "/streameru/programs/partnerships/final" },
      { label: "Professional Creator Mastery", href: "/streameru/programs/professional" },
    ],
    suggestedGlossaryTerms: [
      { title: "Electronic press kit (EPK)", intent: "A structured creator media kit brands use to evaluate fit, stats, and samples." },
      { title: "Brand fit", intent: "How well a brand's audience, values, and category match your content and community." },
    ],
    suggestedDownloads: [
      { title: "professional-brand-partnership-portfolio", intent: "Primary partnership artifact." },
      { title: "epk-evidence-checklist", intent: "Planning artifact." },
      { title: "ninety-day-partnership-improvement-plan", intent: "Evidence and review artifact." },
    ],
    suggestedBlogSupport: [{ title: "Professional brand partnerships for live creators", intent: "Support sponsorship readiness without hype or hidden ads." }],
  }
];
