import type { LessonSeoPack } from "@/lib/resources/lesson-seo/types";

export const CREATOR_WELLNESS_LONGEVITY_MASTERY_LESSON_SEO: LessonSeoPack[] = [
  {
    slug: "building-a-career-that-lasts",
    primaryKeyword: "building a career that lasts for creators",
    secondaryKeywords: ["creator burnout", "streamer wellness", "healthy streaming habits", "Personal Creator Longevity Plan"],
    metaTitle: "Building a Career That Lasts | StreamerU",
    metaDescription: "Define a decade-minded creator career built on consistency, recovery, and sustainable ambition.",
    faqs: [
      { question: "What does this Creator Wellness lesson teach?", answer: "Building a Career That Lasts teaches practical longevity habits with dated artifacts and a LIVE Mission graded on implementation, not hours streamed." },
      { question: "Is this medical or therapy advice?", answer: "No. It is general creator education. Clinical, mental health, and personalized financial questions belong with licensed professionals." },
      { question: "Does this replace Professional Creator Mastery?", answer: "No. Professional Creator owns business accounting and contracts; this path owns personal financial wellness and broader longevity habits." },
      { question: "How is the mission graded?", answer: "By completed artifacts and one implemented change. Hours streamed, gifts, viewers, and rank are not grading targets." },
      { question: "What evidence do I leave with?", answer: "You leave with longevity-career-map, decade-definition-worksheet, consistency-over-intensity-card and evidence for the Personal Creator Longevity Plan." },
    ],
    relatedGuideSlugs: ["creator-support", "creator-community", "tiktok-live-tips"],
    internalLinks: [
      { label: "StreamerU hub", href: "/streameru" },
      { label: "Next: Preventing Creator Burnout", href: "/streameru/preventing-creator-burnout" },
      { label: "Professional Creator Mastery", href: "/streameru/programs/professional" },
    ],
    suggestedGlossaryTerms: [
      { title: "Creator burnout", intent: "A load and recovery failure pattern that can include exhaustion, cynicism, and reduced efficacy." },
      { title: "Longevity floor", intent: "The weekly creator schedule and habits you can still keep on a hard ordinary week." },
    ],
    suggestedDownloads: [
      { title: "longevity-career-map", intent: "Primary wellness system artifact." },
      { title: "decade-definition-worksheet", intent: "Planning artifact." },
      { title: "consistency-over-intensity-card", intent: "Evidence and review artifact." },
    ],
    suggestedBlogSupport: [{ title: "Healthy streaming habits for long careers", intent: "Support creator sustainability without hustle culture." }],
  },
  {
    slug: "preventing-creator-burnout",
    primaryKeyword: "preventing creator burnout for creators",
    secondaryKeywords: ["creator burnout", "streamer wellness", "healthy streaming habits", "Personal Creator Longevity Plan"],
    metaTitle: "Preventing Creator Burnout | StreamerU",
    metaDescription: "Detect burnout early, reduce load on purpose, and run a recovery week before quitting feels inevitable.",
    faqs: [
      { question: "What does this Creator Wellness lesson teach?", answer: "Preventing Creator Burnout teaches practical longevity habits with dated artifacts and a LIVE Mission graded on implementation, not hours streamed." },
      { question: "Is this medical or therapy advice?", answer: "No. It is general creator education. Clinical, mental health, and personalized financial questions belong with licensed professionals." },
      { question: "Does this replace Professional Creator Mastery?", answer: "No. Professional Creator owns business accounting and contracts; this path owns personal financial wellness and broader longevity habits." },
      { question: "How is the mission graded?", answer: "By completed artifacts and one implemented change. Hours streamed, gifts, viewers, and rank are not grading targets." },
      { question: "What evidence do I leave with?", answer: "You leave with burnout-early-warning-dashboard, recovery-week-plan, streaming-fatigue-audit and evidence for the Personal Creator Longevity Plan." },
    ],
    relatedGuideSlugs: ["creator-support", "creator-community", "tiktok-live-tips"],
    internalLinks: [
      { label: "Previous: Building a Career That Lasts", href: "/streameru/building-a-career-that-lasts" },
      { label: "Next: Physical Health for Long Streaming Sessions", href: "/streameru/physical-health-for-long-streaming-sessions" },
      { label: "Professional Creator Mastery", href: "/streameru/programs/professional" },
    ],
    suggestedGlossaryTerms: [
      { title: "Creator burnout", intent: "A load and recovery failure pattern that can include exhaustion, cynicism, and reduced efficacy." },
      { title: "Longevity floor", intent: "The weekly creator schedule and habits you can still keep on a hard ordinary week." },
    ],
    suggestedDownloads: [
      { title: "burnout-early-warning-dashboard", intent: "Primary wellness system artifact." },
      { title: "recovery-week-plan", intent: "Planning artifact." },
      { title: "streaming-fatigue-audit", intent: "Evidence and review artifact." },
    ],
    suggestedBlogSupport: [{ title: "Healthy streaming habits for long careers", intent: "Support creator sustainability without hustle culture." }],
  },
  {
    slug: "physical-health-for-long-streaming-sessions",
    primaryKeyword: "physical health for long streaming sessions for creators",
    secondaryKeywords: ["creator burnout", "streamer wellness", "healthy streaming habits", "Personal Creator Longevity Plan"],
    metaTitle: "Physical Health for Long Streaming Sessions | StreamerU",
    metaDescription: "Build an ergonomic setup, voice care routine, movement breaks, and hydration habits for long LIVE days.",
    faqs: [
      { question: "What does this Creator Wellness lesson teach?", answer: "Physical Health for Long Streaming Sessions teaches practical longevity habits with dated artifacts and a LIVE Mission graded on implementation, not hours streamed." },
      { question: "Is this medical or therapy advice?", answer: "No. It is general creator education. Clinical, mental health, and personalized financial questions belong with licensed professionals." },
      { question: "Does this replace Professional Creator Mastery?", answer: "No. Professional Creator owns business accounting and contracts; this path owns personal financial wellness and broader longevity habits." },
      { question: "How is the mission graded?", answer: "By completed artifacts and one implemented change. Hours streamed, gifts, viewers, and rank are not grading targets." },
      { question: "What evidence do I leave with?", answer: "You leave with ergonomic-workstation-guide, voice-care-checklist, stretch-and-hydration-routine and evidence for the Personal Creator Longevity Plan." },
    ],
    relatedGuideSlugs: ["creator-support", "creator-community", "tiktok-live-tips"],
    internalLinks: [
      { label: "Previous: Preventing Creator Burnout", href: "/streameru/preventing-creator-burnout" },
      { label: "Next: Mental Resilience & Handling Online Pressure", href: "/streameru/mental-resilience-and-handling-online-pressure" },
      { label: "Professional Creator Mastery", href: "/streameru/programs/professional" },
    ],
    suggestedGlossaryTerms: [
      { title: "Creator burnout", intent: "A load and recovery failure pattern that can include exhaustion, cynicism, and reduced efficacy." },
      { title: "Longevity floor", intent: "The weekly creator schedule and habits you can still keep on a hard ordinary week." },
    ],
    suggestedDownloads: [
      { title: "ergonomic-workstation-guide", intent: "Primary wellness system artifact." },
      { title: "voice-care-checklist", intent: "Planning artifact." },
      { title: "stretch-and-hydration-routine", intent: "Evidence and review artifact." },
    ],
    suggestedBlogSupport: [{ title: "Healthy streaming habits for long careers", intent: "Support creator sustainability without hustle culture." }],
  },
  {
    slug: "mental-resilience-and-handling-online-pressure",
    primaryKeyword: "mental resilience & handling online pressure for creators",
    secondaryKeywords: ["creator burnout", "streamer wellness", "healthy streaming habits", "Personal Creator Longevity Plan"],
    metaTitle: "Mental Resilience & Handling Online Pressure | StreamerU",
    metaDescription: "Install criticism triage, comparison rules, and post-LIVE emotional hygiene without turning into a therapist.",
    faqs: [
      { question: "What does this Creator Wellness lesson teach?", answer: "Mental Resilience & Handling Online Pressure teaches practical longevity habits with dated artifacts and a LIVE Mission graded on implementation, not hours streamed." },
      { question: "Is this medical or therapy advice?", answer: "No. It is general creator education. Clinical, mental health, and personalized financial questions belong with licensed professionals." },
      { question: "Does this replace Professional Creator Mastery?", answer: "No. Professional Creator owns business accounting and contracts; this path owns personal financial wellness and broader longevity habits." },
      { question: "How is the mission graded?", answer: "By completed artifacts and one implemented change. Hours streamed, gifts, viewers, and rank are not grading targets." },
      { question: "What evidence do I leave with?", answer: "You leave with aftercare-routine-card, comparison-rules-worksheet, criticism-response-framework and evidence for the Personal Creator Longevity Plan." },
    ],
    relatedGuideSlugs: ["creator-support", "creator-community", "tiktok-live-tips"],
    internalLinks: [
      { label: "Previous: Physical Health for Long Streaming Sessions", href: "/streameru/physical-health-for-long-streaming-sessions" },
      { label: "Next: Time Management & Sustainable Schedules", href: "/streameru/time-management-and-sustainable-schedules" },
      { label: "Professional Creator Mastery", href: "/streameru/programs/professional" },
    ],
    suggestedGlossaryTerms: [
      { title: "Creator burnout", intent: "A load and recovery failure pattern that can include exhaustion, cynicism, and reduced efficacy." },
      { title: "Longevity floor", intent: "The weekly creator schedule and habits you can still keep on a hard ordinary week." },
    ],
    suggestedDownloads: [
      { title: "aftercare-routine-card", intent: "Primary wellness system artifact." },
      { title: "comparison-rules-worksheet", intent: "Planning artifact." },
      { title: "criticism-response-framework", intent: "Evidence and review artifact." },
    ],
    suggestedBlogSupport: [{ title: "Healthy streaming habits for long careers", intent: "Support creator sustainability without hustle culture." }],
  },
  {
    slug: "time-management-and-sustainable-schedules",
    primaryKeyword: "time management & sustainable schedules for creators",
    secondaryKeywords: ["creator burnout", "streamer wellness", "healthy streaming habits", "Personal Creator Longevity Plan"],
    metaTitle: "Time Management & Sustainable Schedules | StreamerU",
    metaDescription: "Build an energy-based week with batching, recovery days, deep work, and protected sleep.",
    faqs: [
      { question: "What does this Creator Wellness lesson teach?", answer: "Time Management & Sustainable Schedules teaches practical longevity habits with dated artifacts and a LIVE Mission graded on implementation, not hours streamed." },
      { question: "Is this medical or therapy advice?", answer: "No. It is general creator education. Clinical, mental health, and personalized financial questions belong with licensed professionals." },
      { question: "Does this replace Professional Creator Mastery?", answer: "No. Professional Creator owns business accounting and contracts; this path owns personal financial wellness and broader longevity habits." },
      { question: "How is the mission graded?", answer: "By completed artifacts and one implemented change. Hours streamed, gifts, viewers, and rank are not grading targets." },
      { question: "What evidence do I leave with?", answer: "You leave with weekly-energy-calendar, recovery-day-planner, sleep-and-batching-planner and evidence for the Personal Creator Longevity Plan." },
    ],
    relatedGuideSlugs: ["creator-support", "creator-community", "tiktok-live-tips"],
    internalLinks: [
      { label: "Previous: Mental Resilience & Handling Online Pressure", href: "/streameru/mental-resilience-and-handling-online-pressure" },
      { label: "Next: Financial Wellness for Variable Income", href: "/streameru/financial-wellness-for-variable-income" },
      { label: "Professional Creator Mastery", href: "/streameru/programs/professional" },
    ],
    suggestedGlossaryTerms: [
      { title: "Creator burnout", intent: "A load and recovery failure pattern that can include exhaustion, cynicism, and reduced efficacy." },
      { title: "Longevity floor", intent: "The weekly creator schedule and habits you can still keep on a hard ordinary week." },
    ],
    suggestedDownloads: [
      { title: "weekly-energy-calendar", intent: "Primary wellness system artifact." },
      { title: "recovery-day-planner", intent: "Planning artifact." },
      { title: "sleep-and-batching-planner", intent: "Evidence and review artifact." },
    ],
    suggestedBlogSupport: [{ title: "Healthy streaming habits for long careers", intent: "Support creator sustainability without hustle culture." }],
  },
  {
    slug: "financial-wellness-for-variable-income",
    primaryKeyword: "financial wellness for variable income for creators",
    secondaryKeywords: ["creator burnout", "streamer wellness", "healthy streaming habits", "Personal Creator Longevity Plan"],
    metaTitle: "Financial Wellness for Variable Income | StreamerU",
    metaDescription: "Stabilize personal finances around variable creator income without turning this into business accounting class.",
    faqs: [
      { question: "What does this Creator Wellness lesson teach?", answer: "Financial Wellness for Variable Income teaches practical longevity habits with dated artifacts and a LIVE Mission graded on implementation, not hours streamed." },
      { question: "Is this medical or therapy advice?", answer: "No. It is general creator education. Clinical, mental health, and personalized financial questions belong with licensed professionals." },
      { question: "Does this replace Professional Creator Mastery?", answer: "No. Professional Creator owns business accounting and contracts; this path owns personal financial wellness and broader longevity habits." },
      { question: "How is the mission graded?", answer: "By completed artifacts and one implemented change. Hours streamed, gifts, viewers, and rank are not grading targets." },
      { question: "What evidence do I leave with?", answer: "You leave with income-variability-buffer-plan, slow-month-playbook, personal-tax-savings-checklist and evidence for the Personal Creator Longevity Plan." },
    ],
    relatedGuideSlugs: ["creator-support", "creator-community", "tiktok-live-tips"],
    internalLinks: [
      { label: "Previous: Time Management & Sustainable Schedules", href: "/streameru/time-management-and-sustainable-schedules" },
      { label: "Next: Healthy Relationships & Personal Boundaries", href: "/streameru/healthy-relationships-and-personal-boundaries" },
      { label: "Professional Creator Mastery", href: "/streameru/programs/professional" },
    ],
    suggestedGlossaryTerms: [
      { title: "Creator burnout", intent: "A load and recovery failure pattern that can include exhaustion, cynicism, and reduced efficacy." },
      { title: "Longevity floor", intent: "The weekly creator schedule and habits you can still keep on a hard ordinary week." },
    ],
    suggestedDownloads: [
      { title: "income-variability-buffer-plan", intent: "Primary wellness system artifact." },
      { title: "slow-month-playbook", intent: "Planning artifact." },
      { title: "personal-tax-savings-checklist", intent: "Evidence and review artifact." },
    ],
    suggestedBlogSupport: [{ title: "Healthy streaming habits for long careers", intent: "Support creator sustainability without hustle culture." }],
  },
  {
    slug: "healthy-relationships-and-personal-boundaries",
    primaryKeyword: "healthy relationships & personal boundaries for creators",
    secondaryKeywords: ["creator burnout", "streamer wellness", "healthy streaming habits", "Personal Creator Longevity Plan"],
    metaTitle: "Healthy Relationships & Personal Boundaries | StreamerU",
    metaDescription: "Write household agreements, parasocial boundaries, privacy rules, and expectations that protect real relationships.",
    faqs: [
      { question: "What does this Creator Wellness lesson teach?", answer: "Healthy Relationships & Personal Boundaries teaches practical longevity habits with dated artifacts and a LIVE Mission graded on implementation, not hours streamed." },
      { question: "Is this medical or therapy advice?", answer: "No. It is general creator education. Clinical, mental health, and personalized financial questions belong with licensed professionals." },
      { question: "Does this replace Professional Creator Mastery?", answer: "No. Professional Creator owns business accounting and contracts; this path owns personal financial wellness and broader longevity habits." },
      { question: "How is the mission graded?", answer: "By completed artifacts and one implemented change. Hours streamed, gifts, viewers, and rank are not grading targets." },
      { question: "What evidence do I leave with?", answer: "You leave with boundary-worksheet, partner-family-communication-card, privacy-expectations-guide and evidence for the Personal Creator Longevity Plan." },
    ],
    relatedGuideSlugs: ["creator-support", "creator-community", "tiktok-live-tips"],
    internalLinks: [
      { label: "Previous: Financial Wellness for Variable Income", href: "/streameru/financial-wellness-for-variable-income" },
      { label: "Next: Maintaining Creativity for Years", href: "/streameru/maintaining-creativity-for-years" },
      { label: "Professional Creator Mastery", href: "/streameru/programs/professional" },
    ],
    suggestedGlossaryTerms: [
      { title: "Creator burnout", intent: "A load and recovery failure pattern that can include exhaustion, cynicism, and reduced efficacy." },
      { title: "Longevity floor", intent: "The weekly creator schedule and habits you can still keep on a hard ordinary week." },
    ],
    suggestedDownloads: [
      { title: "boundary-worksheet", intent: "Primary wellness system artifact." },
      { title: "partner-family-communication-card", intent: "Planning artifact." },
      { title: "privacy-expectations-guide", intent: "Evidence and review artifact." },
    ],
    suggestedBlogSupport: [{ title: "Healthy streaming habits for long careers", intent: "Support creator sustainability without hustle culture." }],
  },
  {
    slug: "maintaining-creativity-for-years",
    primaryKeyword: "maintaining creativity for years for creators",
    secondaryKeywords: ["creator burnout", "streamer wellness", "healthy streaming habits", "Personal Creator Longevity Plan"],
    metaTitle: "Maintaining Creativity for Years | StreamerU",
    metaDescription: "Protect creative capacity with recovery menus, input diets, format rotation, and anti-comparison practice.",
    faqs: [
      { question: "What does this Creator Wellness lesson teach?", answer: "Maintaining Creativity for Years teaches practical longevity habits with dated artifacts and a LIVE Mission graded on implementation, not hours streamed." },
      { question: "Is this medical or therapy advice?", answer: "No. It is general creator education. Clinical, mental health, and personalized financial questions belong with licensed professionals." },
      { question: "Does this replace Professional Creator Mastery?", answer: "No. Professional Creator owns business accounting and contracts; this path owns personal financial wellness and broader longevity habits." },
      { question: "How is the mission graded?", answer: "By completed artifacts and one implemented change. Hours streamed, gifts, viewers, and rank are not grading targets." },
      { question: "What evidence do I leave with?", answer: "You leave with creative-recovery-menu, inspiration-input-diet, creativity-capacity-scorecard and evidence for the Personal Creator Longevity Plan." },
    ],
    relatedGuideSlugs: ["creator-support", "creator-community", "tiktok-live-tips"],
    internalLinks: [
      { label: "Previous: Healthy Relationships & Personal Boundaries", href: "/streameru/healthy-relationships-and-personal-boundaries" },
      { label: "Next: Recovering from Setbacks Without Quitting", href: "/streameru/recovering-from-setbacks-without-quitting" },
      { label: "Professional Creator Mastery", href: "/streameru/programs/professional" },
    ],
    suggestedGlossaryTerms: [
      { title: "Creator burnout", intent: "A load and recovery failure pattern that can include exhaustion, cynicism, and reduced efficacy." },
      { title: "Longevity floor", intent: "The weekly creator schedule and habits you can still keep on a hard ordinary week." },
    ],
    suggestedDownloads: [
      { title: "creative-recovery-menu", intent: "Primary wellness system artifact." },
      { title: "inspiration-input-diet", intent: "Planning artifact." },
      { title: "creativity-capacity-scorecard", intent: "Evidence and review artifact." },
    ],
    suggestedBlogSupport: [{ title: "Healthy streaming habits for long careers", intent: "Support creator sustainability without hustle culture." }],
  },
  {
    slug: "recovering-from-setbacks-without-quitting",
    primaryKeyword: "recovering from setbacks without quitting for creators",
    secondaryKeywords: ["creator burnout", "streamer wellness", "healthy streaming habits", "Personal Creator Longevity Plan"],
    metaTitle: "Recovering from Setbacks Without Quitting | StreamerU",
    metaDescription: "Diagnose setbacks, stabilize for seventy-two hours, and run a staged comeback without panic quitting.",
    faqs: [
      { question: "What does this Creator Wellness lesson teach?", answer: "Recovering from Setbacks Without Quitting teaches practical longevity habits with dated artifacts and a LIVE Mission graded on implementation, not hours streamed." },
      { question: "Is this medical or therapy advice?", answer: "No. It is general creator education. Clinical, mental health, and personalized financial questions belong with licensed professionals." },
      { question: "Does this replace Professional Creator Mastery?", answer: "No. Professional Creator owns business accounting and contracts; this path owns personal financial wellness and broader longevity habits." },
      { question: "How is the mission graded?", answer: "By completed artifacts and one implemented change. Hours streamed, gifts, viewers, and rank are not grading targets." },
      { question: "What evidence do I leave with?", answer: "You leave with setback-diagnosis-worksheet, comeback-14-day-plan, anti-quit-decision-card and evidence for the Personal Creator Longevity Plan." },
    ],
    relatedGuideSlugs: ["creator-support", "creator-community", "tiktok-live-tips"],
    internalLinks: [
      { label: "Previous: Maintaining Creativity for Years", href: "/streameru/maintaining-creativity-for-years" },
      { label: "Next: Creator Wellness Capstone: Personal Longevity Plan", href: "/streameru/creator-wellness-capstone-personal-longevity-plan" },
      { label: "Professional Creator Mastery", href: "/streameru/programs/professional" },
    ],
    suggestedGlossaryTerms: [
      { title: "Creator burnout", intent: "A load and recovery failure pattern that can include exhaustion, cynicism, and reduced efficacy." },
      { title: "Longevity floor", intent: "The weekly creator schedule and habits you can still keep on a hard ordinary week." },
    ],
    suggestedDownloads: [
      { title: "setback-diagnosis-worksheet", intent: "Primary wellness system artifact." },
      { title: "comeback-14-day-plan", intent: "Planning artifact." },
      { title: "anti-quit-decision-card", intent: "Evidence and review artifact." },
    ],
    suggestedBlogSupport: [{ title: "Healthy streaming habits for long careers", intent: "Support creator sustainability without hustle culture." }],
  },
  {
    slug: "creator-wellness-capstone-personal-longevity-plan",
    primaryKeyword: "creator wellness capstone: personal longevity plan for creators",
    secondaryKeywords: ["creator burnout", "streamer wellness", "healthy streaming habits", "Personal Creator Longevity Plan"],
    metaTitle: "Creator Wellness Capstone: Personal Longevity Plan | StreamerU",
    metaDescription: "Assemble workspace, schedule, recovery, boundaries, buffers, and habits into one reviewable longevity plan.",
    faqs: [
      { question: "What does this Creator Wellness lesson teach?", answer: "Creator Wellness Capstone: Personal Longevity Plan teaches practical longevity habits with dated artifacts and a LIVE Mission graded on implementation, not hours streamed." },
      { question: "Is this medical or therapy advice?", answer: "No. It is general creator education. Clinical, mental health, and personalized financial questions belong with licensed professionals." },
      { question: "Does this replace Professional Creator Mastery?", answer: "No. Professional Creator owns business accounting and contracts; this path owns personal financial wellness and broader longevity habits." },
      { question: "How is the mission graded?", answer: "By completed artifacts and one implemented change. Hours streamed, gifts, viewers, and rank are not grading targets." },
      { question: "What evidence do I leave with?", answer: "You leave with personal-creator-longevity-plan, longevity-evidence-checklist, ninety-day-wellness-improvement-plan and evidence for the Personal Creator Longevity Plan." },
    ],
    relatedGuideSlugs: ["creator-support", "creator-community", "tiktok-live-tips"],
    internalLinks: [
      { label: "Previous: Recovering from Setbacks Without Quitting", href: "/streameru/recovering-from-setbacks-without-quitting" },
      { label: "Creator Wellness Program Final", href: "/streameru/programs/wellness/final" },
      { label: "Professional Creator Mastery", href: "/streameru/programs/professional" },
    ],
    suggestedGlossaryTerms: [
      { title: "Creator burnout", intent: "A load and recovery failure pattern that can include exhaustion, cynicism, and reduced efficacy." },
      { title: "Longevity floor", intent: "The weekly creator schedule and habits you can still keep on a hard ordinary week." },
    ],
    suggestedDownloads: [
      { title: "personal-creator-longevity-plan", intent: "Primary wellness system artifact." },
      { title: "longevity-evidence-checklist", intent: "Planning artifact." },
      { title: "ninety-day-wellness-improvement-plan", intent: "Evidence and review artifact." },
    ],
    suggestedBlogSupport: [{ title: "Healthy streaming habits for long careers", intent: "Support creator sustainability without hustle culture." }],
  }
];
