import type { LessonSeoPack } from "@/lib/resources/lesson-seo/types";

export const MOBILE_CREATOR_MASTERY_LESSON_SEO: LessonSeoPack[] = [
  {
    slug: "building-a-mobile-creator-mindset",
    primaryKeyword: "building a mobile creator mindset for creators",
    secondaryKeywords: ["mobile creator setup","phone-only creator","IRL streaming","creator backpack","mobile editing","travel creator"],
    metaTitle: "Building a Mobile Creator Mindset | StreamerU",
    metaDescription: "Build a mobile creator mindset grounded in reliability, simplicity, and prepared systems—not location vibes alone.",
    faqs: [
      { question: "What does this Mobile Creator lesson teach?", answer: "Building a Mobile Creator Mindset teaches practical mobile creator readiness with dated artifacts and a LIVE Mission graded on preparation evidence, not viewer metrics." },
      { question: "Is this legal or travel advice?", answer: "No. It is general creator education. Location permits, aviation rules, privacy law, and insurance questions belong with qualified professionals." },
      { question: "Does this replace Production Mastery?", answer: "No. Production Mastery covers studio-grade craft; this path covers phone-first mobility, travel kits, IRL safety boundaries, and the Complete Mobile Creator System." },
      { question: "How is the mission graded?", answer: "By completed artifacts and one implemented improvement. Viewers, gifts, and rank are not grading targets." },
      { question: "What evidence do I leave with?", answer: "You leave with mobile-mindset-checklist, mobility-vs-studio-scorecard, freedom-operating-principles-card and evidence for the Complete Mobile Creator System." },
    ],
    relatedGuideSlugs: ["creator-support", "tiktok-live-streaming-setup", "streamer-resources"],
    internalLinks: [
      { label: "StreamerU hub", href: "/streameru" },
      { label: "Next: Choosing the Right Mobile Equipment", href: "/streameru/choosing-the-right-mobile-equipment" },
      { label: "Production Mastery", href: "/streameru/programs/production" },
    ],
    suggestedGlossaryTerms: [
      { title: "Mobile creator kit", intent: "Portable gear, power, audio, and redundancy layers for phone-first creation." },
      { title: "IRL streaming safety", intent: "Visibility, consent awareness, exits, and boundaries—not chaos for clips." },
    ],
    suggestedDownloads: [
      { title: "mobile-mindset-checklist", intent: "Primary mobile artifact." },
      { title: "mobility-vs-studio-scorecard", intent: "Planning artifact." },
      { title: "freedom-operating-principles-card", intent: "Evidence and review artifact." },
    ],
    suggestedBlogSupport: [{ title: "Mobile creator setup for live streamers", intent: "Support phone-only creator workflows with reliability and safety—not hype." }],
  },
  {
    slug: "choosing-the-right-mobile-equipment",
    primaryKeyword: "choosing the right mobile equipment for creators",
    secondaryKeywords: ["mobile creator setup","phone-only creator","IRL streaming","creator backpack","mobile editing","travel creator"],
    metaTitle: "Choosing the Right Mobile Equipment | StreamerU",
    metaDescription: "Choose mobile gear by reliability principles—storage, battery health, heat, ports—not yearly phone hype.",
    faqs: [
      { question: "What does this Mobile Creator lesson teach?", answer: "Choosing the Right Mobile Equipment teaches practical mobile creator readiness with dated artifacts and a LIVE Mission graded on preparation evidence, not viewer metrics." },
      { question: "Is this legal or travel advice?", answer: "No. It is general creator education. Location permits, aviation rules, privacy law, and insurance questions belong with qualified professionals." },
      { question: "Does this replace Production Mastery?", answer: "No. Production Mastery covers studio-grade craft; this path covers phone-first mobility, travel kits, IRL safety boundaries, and the Complete Mobile Creator System." },
      { question: "How is the mission graded?", answer: "By completed artifacts and one implemented improvement. Viewers, gifts, and rank are not grading targets." },
      { question: "What evidence do I leave with?", answer: "You leave with mobile-gear-checklist, phone-capability-worksheet, upgrade-priority-matrix and evidence for the Complete Mobile Creator System." },
    ],
    relatedGuideSlugs: ["creator-support", "tiktok-live-streaming-setup", "streamer-resources"],
    internalLinks: [
      { label: "Previous: Building a Mobile Creator Mindset", href: "/streameru/building-a-mobile-creator-mindset" },
      { label: "Next: Mobile Audio & Lighting", href: "/streameru/mobile-audio-and-lighting" },
      { label: "Production Mastery", href: "/streameru/programs/production" },
    ],
    suggestedGlossaryTerms: [
      { title: "Mobile creator kit", intent: "Portable gear, power, audio, and redundancy layers for phone-first creation." },
      { title: "IRL streaming safety", intent: "Visibility, consent awareness, exits, and boundaries—not chaos for clips." },
    ],
    suggestedDownloads: [
      { title: "mobile-gear-checklist", intent: "Primary mobile artifact." },
      { title: "phone-capability-worksheet", intent: "Planning artifact." },
      { title: "upgrade-priority-matrix", intent: "Evidence and review artifact." },
    ],
    suggestedBlogSupport: [{ title: "Mobile creator setup for live streamers", intent: "Support phone-only creator workflows with reliability and safety—not hype." }],
  },
  {
    slug: "mobile-audio-and-lighting",
    primaryKeyword: "mobile audio & lighting for creators",
    secondaryKeywords: ["mobile creator setup","phone-only creator","IRL streaming","creator backpack","mobile editing","travel creator"],
    metaTitle: "Mobile Audio & Lighting | StreamerU",
    metaDescription: "Design portable audio and lighting that stays intelligible and controllable in unpredictable environments.",
    faqs: [
      { question: "What does this Mobile Creator lesson teach?", answer: "Mobile Audio & Lighting teaches practical mobile creator readiness with dated artifacts and a LIVE Mission graded on preparation evidence, not viewer metrics." },
      { question: "Is this legal or travel advice?", answer: "No. It is general creator education. Location permits, aviation rules, privacy law, and insurance questions belong with qualified professionals." },
      { question: "Does this replace Production Mastery?", answer: "No. Production Mastery covers studio-grade craft; this path covers phone-first mobility, travel kits, IRL safety boundaries, and the Complete Mobile Creator System." },
      { question: "How is the mission graded?", answer: "By completed artifacts and one implemented improvement. Viewers, gifts, and rank are not grading targets." },
      { question: "What evidence do I leave with?", answer: "You leave with mobile-audio-setup-card, portable-lighting-checklist, wind-and-noise-plan and evidence for the Complete Mobile Creator System." },
    ],
    relatedGuideSlugs: ["creator-support", "tiktok-live-streaming-setup", "streamer-resources"],
    internalLinks: [
      { label: "Previous: Choosing the Right Mobile Equipment", href: "/streameru/choosing-the-right-mobile-equipment" },
      { label: "Next: Streaming Anywhere Professionally", href: "/streameru/streaming-anywhere-professionally" },
      { label: "Production Mastery", href: "/streameru/programs/production" },
    ],
    suggestedGlossaryTerms: [
      { title: "Mobile creator kit", intent: "Portable gear, power, audio, and redundancy layers for phone-first creation." },
      { title: "IRL streaming safety", intent: "Visibility, consent awareness, exits, and boundaries—not chaos for clips." },
    ],
    suggestedDownloads: [
      { title: "mobile-audio-setup-card", intent: "Primary mobile artifact." },
      { title: "portable-lighting-checklist", intent: "Planning artifact." },
      { title: "wind-and-noise-plan", intent: "Evidence and review artifact." },
    ],
    suggestedBlogSupport: [{ title: "Mobile creator setup for live streamers", intent: "Support phone-only creator workflows with reliability and safety—not hype." }],
  },
  {
    slug: "streaming-anywhere-professionally",
    primaryKeyword: "streaming anywhere professionally for creators",
    secondaryKeywords: ["mobile creator setup","phone-only creator","IRL streaming","creator backpack","mobile editing","travel creator"],
    metaTitle: "Streaming Anywhere Professionally | StreamerU",
    metaDescription: "Stream anywhere with heat, power, bandwidth, and setup discipline—not improvisation alone.",
    faqs: [
      { question: "What does this Mobile Creator lesson teach?", answer: "Streaming Anywhere Professionally teaches practical mobile creator readiness with dated artifacts and a LIVE Mission graded on preparation evidence, not viewer metrics." },
      { question: "Is this legal or travel advice?", answer: "No. It is general creator education. Location permits, aviation rules, privacy law, and insurance questions belong with qualified professionals." },
      { question: "Does this replace Production Mastery?", answer: "No. Production Mastery covers studio-grade craft; this path covers phone-first mobility, travel kits, IRL safety boundaries, and the Complete Mobile Creator System." },
      { question: "How is the mission graded?", answer: "By completed artifacts and one implemented improvement. Viewers, gifts, and rank are not grading targets." },
      { question: "What evidence do I leave with?", answer: "You leave with mobile-streaming-checklist, anywhere-setup-runbook, heat-and-power-checklist and evidence for the Complete Mobile Creator System." },
    ],
    relatedGuideSlugs: ["creator-support", "tiktok-live-streaming-setup", "streamer-resources"],
    internalLinks: [
      { label: "Previous: Mobile Audio & Lighting", href: "/streameru/mobile-audio-and-lighting" },
      { label: "Next: Creating High-Quality Videos on Your Phone", href: "/streameru/creating-high-quality-videos-on-your-phone" },
      { label: "Production Mastery", href: "/streameru/programs/production" },
    ],
    suggestedGlossaryTerms: [
      { title: "Mobile creator kit", intent: "Portable gear, power, audio, and redundancy layers for phone-first creation." },
      { title: "IRL streaming safety", intent: "Visibility, consent awareness, exits, and boundaries—not chaos for clips." },
    ],
    suggestedDownloads: [
      { title: "mobile-streaming-checklist", intent: "Primary mobile artifact." },
      { title: "anywhere-setup-runbook", intent: "Planning artifact." },
      { title: "heat-and-power-checklist", intent: "Evidence and review artifact." },
    ],
    suggestedBlogSupport: [{ title: "Mobile creator setup for live streamers", intent: "Support phone-only creator workflows with reliability and safety—not hype." }],
  },
  {
    slug: "creating-high-quality-videos-on-your-phone",
    primaryKeyword: "creating high-quality videos on your phone for creators",
    secondaryKeywords: ["mobile creator setup","phone-only creator","IRL streaming","creator backpack","mobile editing","travel creator"],
    metaTitle: "Creating High-Quality Videos on Your Phone | StreamerU",
    metaDescription: "Build repeatable phone editing, caption, and thumbnail workflows without desktop dependency.",
    faqs: [
      { question: "What does this Mobile Creator lesson teach?", answer: "Creating High-Quality Videos on Your Phone teaches practical mobile creator readiness with dated artifacts and a LIVE Mission graded on preparation evidence, not viewer metrics." },
      { question: "Is this legal or travel advice?", answer: "No. It is general creator education. Location permits, aviation rules, privacy law, and insurance questions belong with qualified professionals." },
      { question: "Does this replace Production Mastery?", answer: "No. Production Mastery covers studio-grade craft; this path covers phone-first mobility, travel kits, IRL safety boundaries, and the Complete Mobile Creator System." },
      { question: "How is the mission graded?", answer: "By completed artifacts and one implemented improvement. Viewers, gifts, and rank are not grading targets." },
      { question: "What evidence do I leave with?", answer: "You leave with phone-edit-workflow, mobile-caption-checklist, thumbnail-on-phone-guide and evidence for the Complete Mobile Creator System." },
    ],
    relatedGuideSlugs: ["creator-support", "tiktok-live-streaming-setup", "streamer-resources"],
    internalLinks: [
      { label: "Previous: Streaming Anywhere Professionally", href: "/streameru/streaming-anywhere-professionally" },
      { label: "Next: Traveling as a Creator", href: "/streameru/traveling-as-a-creator" },
      { label: "Production Mastery", href: "/streameru/programs/production" },
    ],
    suggestedGlossaryTerms: [
      { title: "Mobile creator kit", intent: "Portable gear, power, audio, and redundancy layers for phone-first creation." },
      { title: "IRL streaming safety", intent: "Visibility, consent awareness, exits, and boundaries—not chaos for clips." },
    ],
    suggestedDownloads: [
      { title: "phone-edit-workflow", intent: "Primary mobile artifact." },
      { title: "mobile-caption-checklist", intent: "Planning artifact." },
      { title: "thumbnail-on-phone-guide", intent: "Evidence and review artifact." },
    ],
    suggestedBlogSupport: [{ title: "Mobile creator setup for live streamers", intent: "Support phone-only creator workflows with reliability and safety—not hype." }],
  },
  {
    slug: "traveling-as-a-creator",
    primaryKeyword: "traveling as a creator for creators",
    secondaryKeywords: ["mobile creator setup","phone-only creator","IRL streaming","creator backpack","mobile editing","travel creator"],
    metaTitle: "Traveling as a Creator | StreamerU",
    metaDescription: "Pack, transit, and hotel stream with weight limits, redundancy, and general travel awareness—not legal advice.",
    faqs: [
      { question: "What does this Mobile Creator lesson teach?", answer: "Traveling as a Creator teaches practical mobile creator readiness with dated artifacts and a LIVE Mission graded on preparation evidence, not viewer metrics." },
      { question: "Is this legal or travel advice?", answer: "No. It is general creator education. Location permits, aviation rules, privacy law, and insurance questions belong with qualified professionals." },
      { question: "Does this replace Production Mastery?", answer: "No. Production Mastery covers studio-grade craft; this path covers phone-first mobility, travel kits, IRL safety boundaries, and the Complete Mobile Creator System." },
      { question: "How is the mission graded?", answer: "By completed artifacts and one implemented improvement. Viewers, gifts, and rank are not grading targets." },
      { question: "What evidence do I leave with?", answer: "You leave with travel-packing-guide, airport-creator-checklist, hotel-stream-runbook and evidence for the Complete Mobile Creator System." },
    ],
    relatedGuideSlugs: ["creator-support", "tiktok-live-streaming-setup", "streamer-resources"],
    internalLinks: [
      { label: "Previous: Creating High-Quality Videos on Your Phone", href: "/streameru/creating-high-quality-videos-on-your-phone" },
      { label: "Next: Mobile Productivity & Cloud Workflows", href: "/streameru/mobile-productivity-and-cloud-workflows" },
      { label: "Production Mastery", href: "/streameru/programs/production" },
    ],
    suggestedGlossaryTerms: [
      { title: "Mobile creator kit", intent: "Portable gear, power, audio, and redundancy layers for phone-first creation." },
      { title: "IRL streaming safety", intent: "Visibility, consent awareness, exits, and boundaries—not chaos for clips." },
    ],
    suggestedDownloads: [
      { title: "travel-packing-guide", intent: "Primary mobile artifact." },
      { title: "airport-creator-checklist", intent: "Planning artifact." },
      { title: "hotel-stream-runbook", intent: "Evidence and review artifact." },
    ],
    suggestedBlogSupport: [{ title: "Mobile creator setup for live streamers", intent: "Support phone-only creator workflows with reliability and safety—not hype." }],
  },
  {
    slug: "mobile-productivity-and-cloud-workflows",
    primaryKeyword: "mobile productivity & cloud workflows for creators",
    secondaryKeywords: ["mobile creator setup","phone-only creator","IRL streaming","creator backpack","mobile editing","travel creator"],
    metaTitle: "Mobile Productivity & Cloud Workflows | StreamerU",
    metaDescription: "Organize cloud assets, plan battery use, and keep offline fallbacks for dead zones and failed sync.",
    faqs: [
      { question: "What does this Mobile Creator lesson teach?", answer: "Mobile Productivity & Cloud Workflows teaches practical mobile creator readiness with dated artifacts and a LIVE Mission graded on preparation evidence, not viewer metrics." },
      { question: "Is this legal or travel advice?", answer: "No. It is general creator education. Location permits, aviation rules, privacy law, and insurance questions belong with qualified professionals." },
      { question: "Does this replace Production Mastery?", answer: "No. Production Mastery covers studio-grade craft; this path covers phone-first mobility, travel kits, IRL safety boundaries, and the Complete Mobile Creator System." },
      { question: "How is the mission graded?", answer: "By completed artifacts and one implemented improvement. Viewers, gifts, and rank are not grading targets." },
      { question: "What evidence do I leave with?", answer: "You leave with cloud-organization-system, battery-planner, offline-workflow-card and evidence for the Complete Mobile Creator System." },
    ],
    relatedGuideSlugs: ["creator-support", "tiktok-live-streaming-setup", "streamer-resources"],
    internalLinks: [
      { label: "Previous: Traveling as a Creator", href: "/streameru/traveling-as-a-creator" },
      { label: "Next: IRL Streaming Safely & Responsibly", href: "/streameru/irl-streaming-safely-and-responsibly" },
      { label: "Production Mastery", href: "/streameru/programs/production" },
    ],
    suggestedGlossaryTerms: [
      { title: "Mobile creator kit", intent: "Portable gear, power, audio, and redundancy layers for phone-first creation." },
      { title: "IRL streaming safety", intent: "Visibility, consent awareness, exits, and boundaries—not chaos for clips." },
    ],
    suggestedDownloads: [
      { title: "cloud-organization-system", intent: "Primary mobile artifact." },
      { title: "battery-planner", intent: "Planning artifact." },
      { title: "offline-workflow-card", intent: "Evidence and review artifact." },
    ],
    suggestedBlogSupport: [{ title: "Mobile creator setup for live streamers", intent: "Support phone-only creator workflows with reliability and safety—not hype." }],
  },
  {
    slug: "irl-streaming-safely-and-responsibly",
    primaryKeyword: "irl streaming safely & responsibly for creators",
    secondaryKeywords: ["mobile creator setup","phone-only creator","IRL streaming","creator backpack","mobile editing","travel creator"],
    metaTitle: "IRL Streaming Safely & Responsibly | StreamerU",
    metaDescription: "IRL stream with safety, privacy, consent awareness, and emergency exits—never chaos for clips.",
    faqs: [
      { question: "What does this Mobile Creator lesson teach?", answer: "IRL Streaming Safely & Responsibly teaches practical mobile creator readiness with dated artifacts and a LIVE Mission graded on preparation evidence, not viewer metrics." },
      { question: "Is this legal or travel advice?", answer: "No. It is general creator education. Location permits, aviation rules, privacy law, and insurance questions belong with qualified professionals." },
      { question: "Does this replace Production Mastery?", answer: "No. Production Mastery covers studio-grade craft; this path covers phone-first mobility, travel kits, IRL safety boundaries, and the Complete Mobile Creator System." },
      { question: "How is the mission graded?", answer: "By completed artifacts and one implemented improvement. Viewers, gifts, and rank are not grading targets." },
      { question: "What evidence do I leave with?", answer: "You leave with irl-safety-checklist, public-privacy-checklist, emergency-backup-plan and evidence for the Complete Mobile Creator System." },
    ],
    relatedGuideSlugs: ["creator-support", "tiktok-live-streaming-setup", "streamer-resources"],
    internalLinks: [
      { label: "Previous: Mobile Productivity & Cloud Workflows", href: "/streameru/mobile-productivity-and-cloud-workflows" },
      { label: "Next: Building a Complete Mobile Creator Kit", href: "/streameru/building-a-complete-mobile-creator-kit" },
      { label: "Production Mastery", href: "/streameru/programs/production" },
    ],
    suggestedGlossaryTerms: [
      { title: "Mobile creator kit", intent: "Portable gear, power, audio, and redundancy layers for phone-first creation." },
      { title: "IRL streaming safety", intent: "Visibility, consent awareness, exits, and boundaries—not chaos for clips." },
    ],
    suggestedDownloads: [
      { title: "irl-safety-checklist", intent: "Primary mobile artifact." },
      { title: "public-privacy-checklist", intent: "Planning artifact." },
      { title: "emergency-backup-plan", intent: "Evidence and review artifact." },
    ],
    suggestedBlogSupport: [{ title: "Mobile creator setup for live streamers", intent: "Support phone-only creator workflows with reliability and safety—not hype." }],
  },
  {
    slug: "building-a-complete-mobile-creator-kit",
    primaryKeyword: "building a complete mobile creator kit for creators",
    secondaryKeywords: ["mobile creator setup","phone-only creator","IRL streaming","creator backpack","mobile editing","travel creator"],
    metaTitle: "Building a Complete Mobile Creator Kit | StreamerU",
    metaDescription: "Assemble a complete mobile kit with redundancy layers—not the most expensive backpack.",
    faqs: [
      { question: "What does this Mobile Creator lesson teach?", answer: "Building a Complete Mobile Creator Kit teaches practical mobile creator readiness with dated artifacts and a LIVE Mission graded on preparation evidence, not viewer metrics." },
      { question: "Is this legal or travel advice?", answer: "No. It is general creator education. Location permits, aviation rules, privacy law, and insurance questions belong with qualified professionals." },
      { question: "Does this replace Production Mastery?", answer: "No. Production Mastery covers studio-grade craft; this path covers phone-first mobility, travel kits, IRL safety boundaries, and the Complete Mobile Creator System." },
      { question: "How is the mission graded?", answer: "By completed artifacts and one implemented improvement. Viewers, gifts, and rank are not grading targets." },
      { question: "What evidence do I leave with?", answer: "You leave with creator-backpack-inventory, kit-redundancy-map, ninety-day-kit-upgrade-plan and evidence for the Complete Mobile Creator System." },
    ],
    relatedGuideSlugs: ["creator-support", "tiktok-live-streaming-setup", "streamer-resources"],
    internalLinks: [
      { label: "Previous: IRL Streaming Safely & Responsibly", href: "/streameru/irl-streaming-safely-and-responsibly" },
      { label: "Next: Mobile Creator Capstone: Complete Mobile Creator System", href: "/streameru/mobile-creator-capstone-complete-system" },
      { label: "Production Mastery", href: "/streameru/programs/production" },
    ],
    suggestedGlossaryTerms: [
      { title: "Mobile creator kit", intent: "Portable gear, power, audio, and redundancy layers for phone-first creation." },
      { title: "IRL streaming safety", intent: "Visibility, consent awareness, exits, and boundaries—not chaos for clips." },
    ],
    suggestedDownloads: [
      { title: "creator-backpack-inventory", intent: "Primary mobile artifact." },
      { title: "kit-redundancy-map", intent: "Planning artifact." },
      { title: "ninety-day-kit-upgrade-plan", intent: "Evidence and review artifact." },
    ],
    suggestedBlogSupport: [{ title: "Mobile creator setup for live streamers", intent: "Support phone-only creator workflows with reliability and safety—not hype." }],
  },
  {
    slug: "mobile-creator-capstone-complete-system",
    primaryKeyword: "mobile creator capstone: complete mobile creator system for creators",
    secondaryKeywords: ["mobile creator setup","phone-only creator","IRL streaming","creator backpack","mobile editing","travel creator"],
    metaTitle: "Mobile Creator Capstone: Complete Mobile Creator System | StreamerU",
    metaDescription: "Assemble every mobile artifact into one reviewable Complete Mobile Creator System and close the public StreamerU curriculum.",
    faqs: [
      { question: "What does this Mobile Creator lesson teach?", answer: "Mobile Creator Capstone: Complete Mobile Creator System teaches practical mobile creator readiness with dated artifacts and a LIVE Mission graded on preparation evidence, not viewer metrics." },
      { question: "Is this legal or travel advice?", answer: "No. It is general creator education. Location permits, aviation rules, privacy law, and insurance questions belong with qualified professionals." },
      { question: "Does this replace Production Mastery?", answer: "No. Production Mastery covers studio-grade craft; this path covers phone-first mobility, travel kits, IRL safety boundaries, and the Complete Mobile Creator System." },
      { question: "How is the mission graded?", answer: "By completed artifacts and one implemented improvement. Viewers, gifts, and rank are not grading targets." },
      { question: "What evidence do I leave with?", answer: "You leave with complete-mobile-creator-system, mobile-system-evidence-checklist, ninety-day-mobile-improvement-plan and evidence for the Complete Mobile Creator System." },
    ],
    relatedGuideSlugs: ["creator-support", "tiktok-live-streaming-setup", "streamer-resources"],
    internalLinks: [
      { label: "Previous: Building a Complete Mobile Creator Kit", href: "/streameru/building-a-complete-mobile-creator-kit" },
      { label: "Mobile Creator Program Final", href: "/streameru/programs/mobile/final" },
      { label: "Production Mastery", href: "/streameru/programs/production" },
    ],
    suggestedGlossaryTerms: [
      { title: "Mobile creator kit", intent: "Portable gear, power, audio, and redundancy layers for phone-first creation." },
      { title: "IRL streaming safety", intent: "Visibility, consent awareness, exits, and boundaries—not chaos for clips." },
    ],
    suggestedDownloads: [
      { title: "complete-mobile-creator-system", intent: "Primary mobile artifact." },
      { title: "mobile-system-evidence-checklist", intent: "Planning artifact." },
      { title: "ninety-day-mobile-improvement-plan", intent: "Evidence and review artifact." },
    ],
    suggestedBlogSupport: [{ title: "Mobile creator setup for live streamers", intent: "Support phone-only creator workflows with reliability and safety—not hype." }],
  }
];
