import type { LessonSeoPack } from "@/lib/resources/lesson-seo/types";

export const SELLING_INFLUENCE_MASTERY_LESSON_SEO: LessonSeoPack[] = [
  {
    slug: "trust-is-your-greatest-asset",
    primaryKeyword: "trust is your greatest asset for TikTok LIVE creators",
    secondaryKeywords: [
      "ethical selling for creators",
      "influence without manipulation",
      "pressure-free creator offers",
      "StreamerU Selling Influence Mastery",
      "Ethical Creator Offer",
    ],
    metaTitle: "Trust Is Your Greatest Asset | StreamerU",
    metaDescription: "Audit the authenticity, reliability, and listening signals that make an audience willing to consider what you offer.",
    faqs: [
      { question: "What does this Selling & Influence lesson teach?", answer: "Trust is accumulated evidence of alignment, reliability, and listening. It lowers risk because people can compare what you said with what you consistently do. It focuses on communication and execution, never revenue or rank." },
      { question: "Does this lesson teach manipulation or false urgency?", answer: "No. Manipulation, false scarcity, fake urgency, guilt gifting, fabricated proof, and dark patterns are explicitly refused." },
      { question: "Does this lesson teach TikTok Shop setup?", answer: "No. TikTok Shop may be mentioned only as a brief channel example; catalog, setup, pinning, affiliate center, and shop analytics mechanics are outside scope." },
      { question: "What do I leave with after this lesson?", answer: "You leave with Trust Audit Worksheet, Trust Signal Checklist, Relationship Map Starter and the Trust Signal LIVE Review, graded on execution and communication quality." },
      { question: "How does this connect to the Capstone?", answer: "Each artifact feeds the Ethical Creator Offer, which is graded on ethical judgment and reviewable evidence — never revenue, gifts, viewers, or rank." },
    ],
    relatedGuideSlugs: ["creator-coaching", "tiktok-live-tips", "creator-support", "creator-community"],
    internalLinks: [
      { label: "Next: Understanding Why People Buy", href: "/streameru/understanding-why-people-buy" },
      { label: "StreamerU hub", href: "/streameru" },
      { label: "Selling Program Final", href: "/streameru/programs/selling/final" },
      { label: "Meet the founder", href: "/founder" },
      { label: "Editorial standards", href: "/guides/editorial-standards" },
    ],
    suggestedGlossaryTerms: [
      { title: "Ethical Creator Offer", intent: "A reviewable offer system built on trust, clear value, free choice, delivery, and improvement." },
      { title: "Pressure test", intent: "Ask whether you would feel respected if creator and audience roles were reversed." },
      { title: "Decision friction", intent: "Information, effort, or uncertainty that affects a person's ability to make an informed choice." },
    ],
    suggestedDownloads: [
      { title: "Trust Audit Worksheet", intent: "Capstone-ready artifact from this lesson." },
      { title: "Trust Signal Checklist", intent: "Capstone-ready artifact from this lesson." },
      { title: "Relationship Map Starter", intent: "Capstone-ready artifact from this lesson." },
    ],
    suggestedBlogSupport: [
      { title: "How creators sell without damaging audience trust", intent: "Bridge into Selling & Influence Mastery." },
      { title: "Pressure-free calls to action and ethical creator offers", intent: "Teach-first support for clear, reputation-safe selling." },
    ],
  },
  {
    slug: "understanding-why-people-buy",
    primaryKeyword: "understanding why people buy for TikTok LIVE creators",
    secondaryKeywords: [
      "ethical selling for creators",
      "influence without manipulation",
      "pressure-free creator offers",
      "StreamerU Selling Influence Mastery",
      "Ethical Creator Offer",
    ],
    metaTitle: "Understanding Why People Buy | StreamerU",
    metaDescription: "Map needs, motivations, risk, and decision friction so you can help people decide without pushing them.",
    faqs: [
      { question: "What does this Selling & Influence lesson teach?", answer: "People buy to make progress or improve an experience. Ethical discovery identifies the real need, reduces informational risk, and preserves deliberation. It focuses on communication and execution, never revenue or rank." },
      { question: "Does this lesson teach manipulation or false urgency?", answer: "No. Manipulation, false scarcity, fake urgency, guilt gifting, fabricated proof, and dark patterns are explicitly refused." },
      { question: "Does this lesson teach TikTok Shop setup?", answer: "No. TikTok Shop may be mentioned only as a brief channel example; catalog, setup, pinning, affiliate center, and shop analytics mechanics are outside scope." },
      { question: "What do I leave with after this lesson?", answer: "You leave with Buyer Motivation Map, Needs Discovery Guide, Decision Friction Card and the Needs Discovery Practice, graded on execution and communication quality." },
      { question: "How does this connect to the Capstone?", answer: "Each artifact feeds the Ethical Creator Offer, which is graded on ethical judgment and reviewable evidence — never revenue, gifts, viewers, or rank." },
    ],
    relatedGuideSlugs: ["creator-coaching", "tiktok-live-tips", "creator-support", "creator-community"],
    internalLinks: [
      { label: "Previous: Trust Is Your Greatest Asset", href: "/streameru/trust-is-your-greatest-asset" },
      { label: "Next: Communicating Value Clearly", href: "/streameru/communicating-value-clearly" },
      { label: "StreamerU hub", href: "/streameru" },
      { label: "Selling Program Final", href: "/streameru/programs/selling/final" },
      { label: "Meet the founder", href: "/founder" },
      { label: "Editorial standards", href: "/guides/editorial-standards" },
    ],
    suggestedGlossaryTerms: [
      { title: "Ethical Creator Offer", intent: "A reviewable offer system built on trust, clear value, free choice, delivery, and improvement." },
      { title: "Pressure test", intent: "Ask whether you would feel respected if creator and audience roles were reversed." },
      { title: "Decision friction", intent: "Information, effort, or uncertainty that affects a person's ability to make an informed choice." },
    ],
    suggestedDownloads: [
      { title: "Buyer Motivation Map", intent: "Capstone-ready artifact from this lesson." },
      { title: "Needs Discovery Guide", intent: "Capstone-ready artifact from this lesson." },
      { title: "Decision Friction Card", intent: "Capstone-ready artifact from this lesson." },
    ],
    suggestedBlogSupport: [
      { title: "How creators sell without damaging audience trust", intent: "Bridge into Selling & Influence Mastery." },
      { title: "Pressure-free calls to action and ethical creator offers", intent: "Teach-first support for clear, reputation-safe selling." },
    ],
  },
  {
    slug: "communicating-value-clearly",
    primaryKeyword: "communicating value clearly for TikTok LIVE creators",
    secondaryKeywords: [
      "ethical selling for creators",
      "influence without manipulation",
      "pressure-free creator offers",
      "StreamerU Selling Influence Mastery",
      "Ethical Creator Offer",
    ],
    metaTitle: "Communicating Value Clearly | StreamerU",
    metaDescription: "Translate features into relevant benefits and explain an offer clearly enough for an informed decision.",
    faqs: [
      { question: "What does this Selling & Influence lesson teach?", answer: "Value becomes clear when features connect to relevant benefits, scope is specific, limitations are visible, and a listener can repeat the promise accurately. It focuses on communication and execution, never revenue or rank." },
      { question: "Does this lesson teach manipulation or false urgency?", answer: "No. Manipulation, false scarcity, fake urgency, guilt gifting, fabricated proof, and dark patterns are explicitly refused." },
      { question: "Does this lesson teach TikTok Shop setup?", answer: "No. TikTok Shop may be mentioned only as a brief channel example; catalog, setup, pinning, affiliate center, and shop analytics mechanics are outside scope." },
      { question: "What do I leave with after this lesson?", answer: "You leave with Value Statement Worksheet, Offer Clarity Framework, Benefit Translation Card and the Value Explanation Drill, graded on execution and communication quality." },
      { question: "How does this connect to the Capstone?", answer: "Each artifact feeds the Ethical Creator Offer, which is graded on ethical judgment and reviewable evidence — never revenue, gifts, viewers, or rank." },
    ],
    relatedGuideSlugs: ["creator-coaching", "tiktok-live-tips", "creator-support", "creator-community"],
    internalLinks: [
      { label: "Previous: Understanding Why People Buy", href: "/streameru/understanding-why-people-buy" },
      { label: "Next: Storytelling That Builds Trust", href: "/streameru/storytelling-that-builds-trust" },
      { label: "StreamerU hub", href: "/streameru" },
      { label: "Selling Program Final", href: "/streameru/programs/selling/final" },
      { label: "Meet the founder", href: "/founder" },
      { label: "Editorial standards", href: "/guides/editorial-standards" },
    ],
    suggestedGlossaryTerms: [
      { title: "Ethical Creator Offer", intent: "A reviewable offer system built on trust, clear value, free choice, delivery, and improvement." },
      { title: "Pressure test", intent: "Ask whether you would feel respected if creator and audience roles were reversed." },
      { title: "Decision friction", intent: "Information, effort, or uncertainty that affects a person's ability to make an informed choice." },
    ],
    suggestedDownloads: [
      { title: "Value Statement Worksheet", intent: "Capstone-ready artifact from this lesson." },
      { title: "Offer Clarity Framework", intent: "Capstone-ready artifact from this lesson." },
      { title: "Benefit Translation Card", intent: "Capstone-ready artifact from this lesson." },
    ],
    suggestedBlogSupport: [
      { title: "How creators sell without damaging audience trust", intent: "Bridge into Selling & Influence Mastery." },
      { title: "Pressure-free calls to action and ethical creator offers", intent: "Teach-first support for clear, reputation-safe selling." },
    ],
  },
  {
    slug: "storytelling-that-builds-trust",
    primaryKeyword: "storytelling that builds trust for TikTok LIVE creators",
    secondaryKeywords: [
      "ethical selling for creators",
      "influence without manipulation",
      "pressure-free creator offers",
      "StreamerU Selling Influence Mastery",
      "Ethical Creator Offer",
    ],
    metaTitle: "Storytelling That Builds Trust | StreamerU",
    metaDescription: "Tell honest, relevant stories that provide context and proof without manufactured drama or fake testimonials.",
    faqs: [
      { question: "What does this Selling & Influence lesson teach?", answer: "Trust stories make value memorable while preserving factual accuracy, consent, proportion, and clear offer information. It focuses on communication and execution, never revenue or rank." },
      { question: "Does this lesson teach manipulation or false urgency?", answer: "No. Manipulation, false scarcity, fake urgency, guilt gifting, fabricated proof, and dark patterns are explicitly refused." },
      { question: "Does this lesson teach TikTok Shop setup?", answer: "No. TikTok Shop may be mentioned only as a brief channel example; catalog, setup, pinning, affiliate center, and shop analytics mechanics are outside scope." },
      { question: "What do I leave with after this lesson?", answer: "You leave with Trust Story Planner, Customer Journey Story Card, Proof Without Hype Checklist and the Trust Story LIVE Tell, graded on execution and communication quality." },
      { question: "How does this connect to the Capstone?", answer: "Each artifact feeds the Ethical Creator Offer, which is graded on ethical judgment and reviewable evidence — never revenue, gifts, viewers, or rank." },
    ],
    relatedGuideSlugs: ["creator-coaching", "tiktok-live-tips", "creator-support", "creator-community"],
    internalLinks: [
      { label: "Previous: Communicating Value Clearly", href: "/streameru/communicating-value-clearly" },
      { label: "Next: Handling Questions and Objections", href: "/streameru/handling-questions-and-objections" },
      { label: "StreamerU hub", href: "/streameru" },
      { label: "Selling Program Final", href: "/streameru/programs/selling/final" },
      { label: "Meet the founder", href: "/founder" },
      { label: "Editorial standards", href: "/guides/editorial-standards" },
    ],
    suggestedGlossaryTerms: [
      { title: "Ethical Creator Offer", intent: "A reviewable offer system built on trust, clear value, free choice, delivery, and improvement." },
      { title: "Pressure test", intent: "Ask whether you would feel respected if creator and audience roles were reversed." },
      { title: "Decision friction", intent: "Information, effort, or uncertainty that affects a person's ability to make an informed choice." },
    ],
    suggestedDownloads: [
      { title: "Trust Story Planner", intent: "Capstone-ready artifact from this lesson." },
      { title: "Customer Journey Story Card", intent: "Capstone-ready artifact from this lesson." },
      { title: "Proof Without Hype Checklist", intent: "Capstone-ready artifact from this lesson." },
    ],
    suggestedBlogSupport: [
      { title: "How creators sell without damaging audience trust", intent: "Bridge into Selling & Influence Mastery." },
      { title: "Pressure-free calls to action and ethical creator offers", intent: "Teach-first support for clear, reputation-safe selling." },
    ],
  },
  {
    slug: "handling-questions-and-objections",
    primaryKeyword: "handling questions and objections for TikTok LIVE creators",
    secondaryKeywords: [
      "ethical selling for creators",
      "influence without manipulation",
      "pressure-free creator offers",
      "StreamerU Selling Influence Mastery",
      "Ethical Creator Offer",
    ],
    metaTitle: "Handling Questions and Objections | StreamerU",
    metaDescription: "Treat objections as information, answer pricing and hesitation calmly, and let uncertainty remain a valid outcome.",
    faqs: [
      { question: "What does this Selling & Influence lesson teach?", answer: "Questions and objections reveal missing clarity, risk, fit, or boundaries. Listen, reflect, answer what is relevant, and release pressure. It focuses on communication and execution, never revenue or rank." },
      { question: "Does this lesson teach manipulation or false urgency?", answer: "No. Manipulation, false scarcity, fake urgency, guilt gifting, fabricated proof, and dark patterns are explicitly refused." },
      { question: "Does this lesson teach TikTok Shop setup?", answer: "No. TikTok Shop may be mentioned only as a brief channel example; catalog, setup, pinning, affiliate center, and shop analytics mechanics are outside scope." },
      { question: "What do I leave with after this lesson?", answer: "You leave with Objection Response Guide, Question Bank for Creators, Hesitation Response Card and the Objection Handling Rehearsal, graded on execution and communication quality." },
      { question: "How does this connect to the Capstone?", answer: "Each artifact feeds the Ethical Creator Offer, which is graded on ethical judgment and reviewable evidence — never revenue, gifts, viewers, or rank." },
    ],
    relatedGuideSlugs: ["creator-coaching", "tiktok-live-tips", "creator-support", "creator-community"],
    internalLinks: [
      { label: "Previous: Storytelling That Builds Trust", href: "/streameru/storytelling-that-builds-trust" },
      { label: "Next: Calls to Action That Feel Natural", href: "/streameru/calls-to-action-that-feel-natural" },
      { label: "StreamerU hub", href: "/streameru" },
      { label: "Selling Program Final", href: "/streameru/programs/selling/final" },
      { label: "Meet the founder", href: "/founder" },
      { label: "Editorial standards", href: "/guides/editorial-standards" },
    ],
    suggestedGlossaryTerms: [
      { title: "Ethical Creator Offer", intent: "A reviewable offer system built on trust, clear value, free choice, delivery, and improvement." },
      { title: "Pressure test", intent: "Ask whether you would feel respected if creator and audience roles were reversed." },
      { title: "Decision friction", intent: "Information, effort, or uncertainty that affects a person's ability to make an informed choice." },
    ],
    suggestedDownloads: [
      { title: "Objection Response Guide", intent: "Capstone-ready artifact from this lesson." },
      { title: "Question Bank for Creators", intent: "Capstone-ready artifact from this lesson." },
      { title: "Hesitation Response Card", intent: "Capstone-ready artifact from this lesson." },
    ],
    suggestedBlogSupport: [
      { title: "How creators sell without damaging audience trust", intent: "Bridge into Selling & Influence Mastery." },
      { title: "Pressure-free calls to action and ethical creator offers", intent: "Teach-first support for clear, reputation-safe selling." },
    ],
  },
  {
    slug: "calls-to-action-that-feel-natural",
    primaryKeyword: "calls to action that feel natural for TikTok LIVE creators",
    secondaryKeywords: [
      "ethical selling for creators",
      "influence without manipulation",
      "pressure-free creator offers",
      "StreamerU Selling Influence Mastery",
      "Ethical Creator Offer",
    ],
    metaTitle: "Calls to Action That Feel Natural | StreamerU",
    metaDescription: "Deliver clear, permission-based calls to action that fit the conversation and avoid false urgency.",
    faqs: [
      { question: "What does this Selling & Influence lesson teach?", answer: "Natural CTAs connect relevant value to one clear action, use permission, state only real constraints, and make declining socially safe. It focuses on communication and execution, never revenue or rank." },
      { question: "Does this lesson teach manipulation or false urgency?", answer: "No. Manipulation, false scarcity, fake urgency, guilt gifting, fabricated proof, and dark patterns are explicitly refused." },
      { question: "Does this lesson teach TikTok Shop setup?", answer: "No. TikTok Shop may be mentioned only as a brief channel example; catalog, setup, pinning, affiliate center, and shop analytics mechanics are outside scope." },
      { question: "What do I leave with after this lesson?", answer: "You leave with CTA Planner, Natural Ask Scripts, Pressure-Free Offer Checklist and the Natural CTA Delivery, graded on execution and communication quality." },
      { question: "How does this connect to the Capstone?", answer: "Each artifact feeds the Ethical Creator Offer, which is graded on ethical judgment and reviewable evidence — never revenue, gifts, viewers, or rank." },
    ],
    relatedGuideSlugs: ["creator-coaching", "tiktok-live-tips", "creator-support", "creator-community"],
    internalLinks: [
      { label: "Previous: Handling Questions and Objections", href: "/streameru/handling-questions-and-objections" },
      { label: "Next: Selling Without Damaging Community", href: "/streameru/selling-without-damaging-community" },
      { label: "StreamerU hub", href: "/streameru" },
      { label: "Selling Program Final", href: "/streameru/programs/selling/final" },
      { label: "Meet the founder", href: "/founder" },
      { label: "Editorial standards", href: "/guides/editorial-standards" },
    ],
    suggestedGlossaryTerms: [
      { title: "Ethical Creator Offer", intent: "A reviewable offer system built on trust, clear value, free choice, delivery, and improvement." },
      { title: "Pressure test", intent: "Ask whether you would feel respected if creator and audience roles were reversed." },
      { title: "Decision friction", intent: "Information, effort, or uncertainty that affects a person's ability to make an informed choice." },
    ],
    suggestedDownloads: [
      { title: "CTA Planner", intent: "Capstone-ready artifact from this lesson." },
      { title: "Natural Ask Scripts", intent: "Capstone-ready artifact from this lesson." },
      { title: "Pressure-Free Offer Checklist", intent: "Capstone-ready artifact from this lesson." },
    ],
    suggestedBlogSupport: [
      { title: "How creators sell without damaging audience trust", intent: "Bridge into Selling & Influence Mastery." },
      { title: "Pressure-free calls to action and ethical creator offers", intent: "Teach-first support for clear, reputation-safe selling." },
    ],
  },
  {
    slug: "selling-without-damaging-community",
    primaryKeyword: "selling without damaging community for TikTok LIVE creators",
    secondaryKeywords: [
      "ethical selling for creators",
      "influence without manipulation",
      "pressure-free creator offers",
      "StreamerU Selling Influence Mastery",
      "Ethical Creator Offer",
    ],
    metaTitle: "Selling Without Damaging Community | StreamerU",
    metaDescription: "Balance service and offers so spending never becomes the price of belonging.",
    faqs: [
      { question: "What does this Selling & Influence lesson teach?", answer: "Selling can coexist with community when commercial moments are bounded, paid benefits are clear, free participation remains respected, and feedback changes behavior. It focuses on communication and execution, never revenue or rank." },
      { question: "Does this lesson teach manipulation or false urgency?", answer: "No. Manipulation, false scarcity, fake urgency, guilt gifting, fabricated proof, and dark patterns are explicitly refused." },
      { question: "Does this lesson teach TikTok Shop setup?", answer: "No. TikTok Shop may be mentioned only as a brief channel example; catalog, setup, pinning, affiliate center, and shop analytics mechanics are outside scope." },
      { question: "What do I leave with after this lesson?", answer: "You leave with Community Trust Scorecard, Offer Cadence Planner, Sell-vs-Serve Balance Card and the Community-Safe Offer Pass, graded on execution and communication quality." },
      { question: "How does this connect to the Capstone?", answer: "Each artifact feeds the Ethical Creator Offer, which is graded on ethical judgment and reviewable evidence — never revenue, gifts, viewers, or rank." },
    ],
    relatedGuideSlugs: ["creator-coaching", "tiktok-live-tips", "creator-support", "creator-community"],
    internalLinks: [
      { label: "Previous: Calls to Action That Feel Natural", href: "/streameru/calls-to-action-that-feel-natural" },
      { label: "Next: Long-Term Customer Relationships", href: "/streameru/long-term-customer-relationships" },
      { label: "StreamerU hub", href: "/streameru" },
      { label: "Selling Program Final", href: "/streameru/programs/selling/final" },
      { label: "Meet the founder", href: "/founder" },
      { label: "Editorial standards", href: "/guides/editorial-standards" },
    ],
    suggestedGlossaryTerms: [
      { title: "Ethical Creator Offer", intent: "A reviewable offer system built on trust, clear value, free choice, delivery, and improvement." },
      { title: "Pressure test", intent: "Ask whether you would feel respected if creator and audience roles were reversed." },
      { title: "Decision friction", intent: "Information, effort, or uncertainty that affects a person's ability to make an informed choice." },
    ],
    suggestedDownloads: [
      { title: "Community Trust Scorecard", intent: "Capstone-ready artifact from this lesson." },
      { title: "Offer Cadence Planner", intent: "Capstone-ready artifact from this lesson." },
      { title: "Sell-vs-Serve Balance Card", intent: "Capstone-ready artifact from this lesson." },
    ],
    suggestedBlogSupport: [
      { title: "How creators sell without damaging audience trust", intent: "Bridge into Selling & Influence Mastery." },
      { title: "Pressure-free calls to action and ethical creator offers", intent: "Teach-first support for clear, reputation-safe selling." },
    ],
  },
  {
    slug: "long-term-customer-relationships",
    primaryKeyword: "long-term customer relationships for TikTok LIVE creators",
    secondaryKeywords: [
      "ethical selling for creators",
      "influence without manipulation",
      "pressure-free creator offers",
      "StreamerU Selling Influence Mastery",
      "Ethical Creator Offer",
    ],
    metaTitle: "Long-Term Customer Relationships | StreamerU",
    metaDescription: "Keep promises after the transaction through useful follow-up, honest remedies, and relationship-centered service.",
    faqs: [
      { question: "What does this Selling & Influence lesson teach?", answer: "Long-term relationships depend on translating claims into obligations, delivering reliably, following up usefully, and handling problems without defensiveness. It focuses on communication and execution, never revenue or rank." },
      { question: "Does this lesson teach manipulation or false urgency?", answer: "No. Manipulation, false scarcity, fake urgency, guilt gifting, fabricated proof, and dark patterns are explicitly refused." },
      { question: "Does this lesson teach TikTok Shop setup?", answer: "No. TikTok Shop may be mentioned only as a brief channel example; catalog, setup, pinning, affiliate center, and shop analytics mechanics are outside scope." },
      { question: "What do I leave with after this lesson?", answer: "You leave with Customer Follow-Up Checklist, Lifetime Value Thinking Card, Promise Keeper Log and the Relationship Follow-Through Drill, graded on execution and communication quality." },
      { question: "How does this connect to the Capstone?", answer: "Each artifact feeds the Ethical Creator Offer, which is graded on ethical judgment and reviewable evidence — never revenue, gifts, viewers, or rank." },
    ],
    relatedGuideSlugs: ["creator-coaching", "tiktok-live-tips", "creator-support", "creator-community"],
    internalLinks: [
      { label: "Previous: Selling Without Damaging Community", href: "/streameru/selling-without-damaging-community" },
      { label: "Next: Ethical Influence & Reputation", href: "/streameru/ethical-influence-and-reputation" },
      { label: "StreamerU hub", href: "/streameru" },
      { label: "Selling Program Final", href: "/streameru/programs/selling/final" },
      { label: "Meet the founder", href: "/founder" },
      { label: "Editorial standards", href: "/guides/editorial-standards" },
    ],
    suggestedGlossaryTerms: [
      { title: "Ethical Creator Offer", intent: "A reviewable offer system built on trust, clear value, free choice, delivery, and improvement." },
      { title: "Pressure test", intent: "Ask whether you would feel respected if creator and audience roles were reversed." },
      { title: "Decision friction", intent: "Information, effort, or uncertainty that affects a person's ability to make an informed choice." },
    ],
    suggestedDownloads: [
      { title: "Customer Follow-Up Checklist", intent: "Capstone-ready artifact from this lesson." },
      { title: "Lifetime Value Thinking Card", intent: "Capstone-ready artifact from this lesson." },
      { title: "Promise Keeper Log", intent: "Capstone-ready artifact from this lesson." },
    ],
    suggestedBlogSupport: [
      { title: "How creators sell without damaging audience trust", intent: "Bridge into Selling & Influence Mastery." },
      { title: "Pressure-free calls to action and ethical creator offers", intent: "Teach-first support for clear, reputation-safe selling." },
    ],
  },
  {
    slug: "ethical-influence-and-reputation",
    primaryKeyword: "ethical influence & reputation for TikTok LIVE creators",
    secondaryKeywords: [
      "ethical selling for creators",
      "influence without manipulation",
      "pressure-free creator offers",
      "StreamerU Selling Influence Mastery",
      "Ethical Creator Offer",
    ],
    metaTitle: "Ethical Influence & Reputation | StreamerU",
    metaDescription: "Apply influence principles with transparency, real proof, free choice, and current disclosure checks.",
    faqs: [
      { question: "What does this Selling & Influence lesson teach?", answer: "Ethical influence uses real proof, transparent relationships, factual constraints, easy exits, and refusal protocols that protect reputation under pressure. It focuses on communication and execution, never revenue or rank." },
      { question: "Does this lesson teach manipulation or false urgency?", answer: "No. Manipulation, false scarcity, fake urgency, guilt gifting, fabricated proof, and dark patterns are explicitly refused." },
      { question: "Does this lesson teach TikTok Shop setup?", answer: "No. TikTok Shop may be mentioned only as a brief channel example; catalog, setup, pinning, affiliate center, and shop analytics mechanics are outside scope." },
      { question: "What do I leave with after this lesson?", answer: "You leave with Ethical Influence Checklist, Disclosure Script Bank, Reputation Risk Scorecard and the Ethics & Reputation Install, graded on execution and communication quality." },
      { question: "How does this connect to the Capstone?", answer: "Each artifact feeds the Ethical Creator Offer, which is graded on ethical judgment and reviewable evidence — never revenue, gifts, viewers, or rank." },
    ],
    relatedGuideSlugs: ["creator-coaching", "tiktok-live-tips", "creator-support", "creator-community"],
    internalLinks: [
      { label: "Previous: Long-Term Customer Relationships", href: "/streameru/long-term-customer-relationships" },
      { label: "Next: Selling & Influence Capstone: Ethical Creator Offer", href: "/streameru/selling-influence-capstone-ethical-offer" },
      { label: "StreamerU hub", href: "/streameru" },
      { label: "Selling Program Final", href: "/streameru/programs/selling/final" },
      { label: "Meet the founder", href: "/founder" },
      { label: "Editorial standards", href: "/guides/editorial-standards" },
    ],
    suggestedGlossaryTerms: [
      { title: "Ethical Creator Offer", intent: "A reviewable offer system built on trust, clear value, free choice, delivery, and improvement." },
      { title: "Pressure test", intent: "Ask whether you would feel respected if creator and audience roles were reversed." },
      { title: "Decision friction", intent: "Information, effort, or uncertainty that affects a person's ability to make an informed choice." },
    ],
    suggestedDownloads: [
      { title: "Ethical Influence Checklist", intent: "Capstone-ready artifact from this lesson." },
      { title: "Disclosure Script Bank", intent: "Capstone-ready artifact from this lesson." },
      { title: "Reputation Risk Scorecard", intent: "Capstone-ready artifact from this lesson." },
    ],
    suggestedBlogSupport: [
      { title: "How creators sell without damaging audience trust", intent: "Bridge into Selling & Influence Mastery." },
      { title: "Pressure-free calls to action and ethical creator offers", intent: "Teach-first support for clear, reputation-safe selling." },
    ],
  },
  {
    slug: "selling-influence-capstone-ethical-offer",
    primaryKeyword: "selling & influence capstone: ethical creator offer for TikTok LIVE creators",
    secondaryKeywords: [
      "ethical selling for creators",
      "influence without manipulation",
      "pressure-free creator offers",
      "StreamerU Selling Influence Mastery",
      "Ethical Creator Offer",
    ],
    metaTitle: "Selling & Influence Capstone: Ethical Creator Offer | StreamerU",
    metaDescription: "Assemble, rehearse, stress-test, and improve a complete Ethical Creator Offer with reviewable evidence.",
    faqs: [
      { question: "What does this Selling & Influence lesson teach?", answer: "The Capstone integrates every lesson into a living Ethical Creator Offer whose need, proof, language, CTA, community impact, fulfillment, and governance can be reviewed. It focuses on communication and execution, never revenue or rank." },
      { question: "Does this lesson teach manipulation or false urgency?", answer: "No. Manipulation, false scarcity, fake urgency, guilt gifting, fabricated proof, and dark patterns are explicitly refused." },
      { question: "Does this lesson teach TikTok Shop setup?", answer: "No. TikTok Shop may be mentioned only as a brief channel example; catalog, setup, pinning, affiliate center, and shop analytics mechanics are outside scope." },
      { question: "What do I leave with after this lesson?", answer: "You leave with Ethical Creator Offer Dossier, Capstone Evidence Checklist Selling Influence, Improvement Report Template and the Ethical Creator Offer Capstone, graded on execution and communication quality." },
      { question: "How does this connect to the Capstone?", answer: "Each artifact feeds the Ethical Creator Offer, which is graded on ethical judgment and reviewable evidence — never revenue, gifts, viewers, or rank." },
    ],
    relatedGuideSlugs: ["creator-coaching", "tiktok-live-tips", "creator-support", "creator-community"],
    internalLinks: [
      { label: "Previous: Ethical Influence & Reputation", href: "/streameru/ethical-influence-and-reputation" },
      { label: "StreamerU hub", href: "/streameru" },
      { label: "Selling Program Final", href: "/streameru/programs/selling/final" },
      { label: "Meet the founder", href: "/founder" },
      { label: "Editorial standards", href: "/guides/editorial-standards" },
    ],
    suggestedGlossaryTerms: [
      { title: "Ethical Creator Offer", intent: "A reviewable offer system built on trust, clear value, free choice, delivery, and improvement." },
      { title: "Pressure test", intent: "Ask whether you would feel respected if creator and audience roles were reversed." },
      { title: "Decision friction", intent: "Information, effort, or uncertainty that affects a person's ability to make an informed choice." },
    ],
    suggestedDownloads: [
      { title: "Ethical Creator Offer Dossier", intent: "Capstone-ready artifact from this lesson." },
      { title: "Capstone Evidence Checklist Selling Influence", intent: "Capstone-ready artifact from this lesson." },
      { title: "Improvement Report Template", intent: "Capstone-ready artifact from this lesson." },
    ],
    suggestedBlogSupport: [
      { title: "How creators sell without damaging audience trust", intent: "Bridge into Selling & Influence Mastery." },
      { title: "Pressure-free calls to action and ethical creator offers", intent: "Teach-first support for clear, reputation-safe selling." },
    ],
  },
];
