import type { LessonSeoPack } from "@/lib/resources/lesson-seo/types";

export const TIKTOK_SHOP_MASTERY_LESSON_SEO: LessonSeoPack[] = [
  {
    slug: "understanding-the-tiktok-shop-ecosystem",
    primaryKeyword: "understanding the tiktok shop ecosystem for TikTok Shop creators",
    secondaryKeywords: ["TikTok Shop systems", "trustworthy Shop execution", "TikTok Shop creator workflow", "Signature Shop Campaign"],
    metaTitle: "Understanding the TikTok Shop Ecosystem | StreamerU",
    metaDescription: "Map Shop roles, operating boundaries, and a trustworthy creator path.",
    faqs: [
      { question: "What does this TikTok Shop Mastery lesson teach?", answer: "Understanding the TikTok Shop Ecosystem establishes a repeatable, trustworthy Shop workflow grounded in current verification, customer information, and reviewable execution. It is graded on execution and evidence, never GMV, commissions, orders, viewers, or rank." },
      { question: "Does this teach Selling & Influence communication craft?", answer: "No, that is a different path; this path teaches Shop systems." },
      { question: "How current are eligibility and policy details?", answer: "They were last reviewed July 2026; verify in your tools and current official TikTok Shop docs." },
      { question: "Does this permit misleading claims, fake reviews, or hidden sponsorships?", answer: "No. The curriculum explicitly refuses deceptive practices, unsafe claims, review manipulation, and unclear material connections." },
      { question: "What evidence do I leave with?", answer: "You leave with shop-ecosystem-map, role-boundary-checklist, creator-path-decision-card and a reviewable Understanding the TikTok Shop Ecosystem Review." },
    ],
    relatedGuideSlugs: ["tiktok-live-tips", "creator-support", "creator-community"],
    internalLinks: [
      { label: "StreamerU hub", href: "/streameru" },
      { label: "Next: Becoming a Trusted Shop Creator", href: "/streameru/becoming-a-trusted-shop-creator" },
      { label: "Selling & Influence Mastery", href: "/streameru/programs/selling" },
    ],
    suggestedGlossaryTerms: [
      { title: "Material connection", intent: "A relationship such as an affiliate commission or free product that can affect how a recommendation is understood." },
      { title: "Shop workflow", intent: "A documented, current process for product research, demonstrations, disclosures, support routing, and review." },
    ],
    suggestedDownloads: [
      { title: "shop-ecosystem-map", intent: "Lesson system artifact." },
      { title: "role-boundary-checklist", intent: "Execution preparation artifact." },
      { title: "creator-path-decision-card", intent: "Evidence and improvement artifact." },
    ],
    suggestedBlogSupport: [{ title: "Trustworthy TikTok Shop systems for creators", intent: "Teach current verification and customer-safe execution." }],
  },
  {
    slug: "becoming-a-trusted-shop-creator",
    primaryKeyword: "becoming a trusted shop creator for TikTok Shop creators",
    secondaryKeywords: ["TikTok Shop systems", "trustworthy Shop execution", "TikTok Shop creator workflow", "Signature Shop Campaign"],
    metaTitle: "Becoming a Trusted Shop Creator | StreamerU",
    metaDescription: "Prepare a verified, transparent Shop creator profile and onboarding workflow.",
    faqs: [
      { question: "What does this TikTok Shop Mastery lesson teach?", answer: "Becoming a Trusted Shop Creator establishes a repeatable, trustworthy Shop workflow grounded in current verification, customer information, and reviewable execution. It is graded on execution and evidence, never GMV, commissions, orders, viewers, or rank." },
      { question: "Does this teach Selling & Influence communication craft?", answer: "No, that is a different path; this path teaches Shop systems." },
      { question: "How current are eligibility and policy details?", answer: "They were last reviewed July 2026; verify in your tools and current official TikTok Shop docs." },
      { question: "Does this permit misleading claims, fake reviews, or hidden sponsorships?", answer: "No. The curriculum explicitly refuses deceptive practices, unsafe claims, review manipulation, and unclear material connections." },
      { question: "What evidence do I leave with?", answer: "You leave with shop-readiness-checklist, creator-onboarding-worksheet, profile-optimization-scorecard and a reviewable Becoming a Trusted Shop Creator Review." },
    ],
    relatedGuideSlugs: ["tiktok-live-tips", "creator-support", "creator-community"],
    internalLinks: [
      { label: "Previous: Understanding the TikTok Shop Ecosystem", href: "/streameru/understanding-the-tiktok-shop-ecosystem" },
      { label: "Next: Product Selection, Research & Affiliate Strategy", href: "/streameru/product-selection-research-and-affiliate-strategy" },
      { label: "Selling & Influence Mastery", href: "/streameru/programs/selling" },
    ],
    suggestedGlossaryTerms: [
      { title: "Material connection", intent: "A relationship such as an affiliate commission or free product that can affect how a recommendation is understood." },
      { title: "Shop workflow", intent: "A documented, current process for product research, demonstrations, disclosures, support routing, and review." },
    ],
    suggestedDownloads: [
      { title: "shop-readiness-checklist", intent: "Lesson system artifact." },
      { title: "creator-onboarding-worksheet", intent: "Execution preparation artifact." },
      { title: "profile-optimization-scorecard", intent: "Evidence and improvement artifact." },
    ],
    suggestedBlogSupport: [{ title: "Trustworthy TikTok Shop systems for creators", intent: "Teach current verification and customer-safe execution." }],
  },
  {
    slug: "product-selection-research-and-affiliate-strategy",
    primaryKeyword: "product selection, research & affiliate strategy for TikTok Shop creators",
    secondaryKeywords: ["TikTok Shop systems", "trustworthy Shop execution", "TikTok Shop creator workflow", "Signature Shop Campaign"],
    metaTitle: "Product Selection, Research & Affiliate Strategy | StreamerU",
    metaDescription: "Evaluate product fit, merchant quality, and sampling decisions before promotion.",
    faqs: [
      { question: "What does this TikTok Shop Mastery lesson teach?", answer: "Product Selection, Research & Affiliate Strategy establishes a repeatable, trustworthy Shop workflow grounded in current verification, customer information, and reviewable execution. It is graded on execution and evidence, never GMV, commissions, orders, viewers, or rank." },
      { question: "Does this teach Selling & Influence communication craft?", answer: "No, that is a different path; this path teaches Shop systems." },
      { question: "How current are eligibility and policy details?", answer: "They were last reviewed July 2026; verify in your tools and current official TikTok Shop docs." },
      { question: "Does this permit misleading claims, fake reviews, or hidden sponsorships?", answer: "No. The curriculum explicitly refuses deceptive practices, unsafe claims, review manipulation, and unclear material connections." },
      { question: "What evidence do I leave with?", answer: "You leave with affiliate-evaluation-worksheet, product-research-scorecard, sample-request-planner and a reviewable Product Selection, Research & Affiliate Strategy Review." },
    ],
    relatedGuideSlugs: ["tiktok-live-tips", "creator-support", "creator-community"],
    internalLinks: [
      { label: "Previous: Becoming a Trusted Shop Creator", href: "/streameru/becoming-a-trusted-shop-creator" },
      { label: "Next: Creating Product Videos People Actually Watch", href: "/streameru/creating-product-videos-people-actually-watch" },
      { label: "Selling & Influence Mastery", href: "/streameru/programs/selling" },
    ],
    suggestedGlossaryTerms: [
      { title: "Material connection", intent: "A relationship such as an affiliate commission or free product that can affect how a recommendation is understood." },
      { title: "Shop workflow", intent: "A documented, current process for product research, demonstrations, disclosures, support routing, and review." },
    ],
    suggestedDownloads: [
      { title: "affiliate-evaluation-worksheet", intent: "Lesson system artifact." },
      { title: "product-research-scorecard", intent: "Execution preparation artifact." },
      { title: "sample-request-planner", intent: "Evidence and improvement artifact." },
    ],
    suggestedBlogSupport: [{ title: "Trustworthy TikTok Shop systems for creators", intent: "Teach current verification and customer-safe execution." }],
  },
  {
    slug: "creating-product-videos-people-actually-watch",
    primaryKeyword: "creating product videos people actually watch for TikTok Shop creators",
    secondaryKeywords: ["TikTok Shop systems", "trustworthy Shop execution", "TikTok Shop creator workflow", "Signature Shop Campaign"],
    metaTitle: "Creating Product Videos People Actually Watch | StreamerU",
    metaDescription: "Build useful product-video systems based on clear hooks and honest demonstrations.",
    faqs: [
      { question: "What does this TikTok Shop Mastery lesson teach?", answer: "Creating Product Videos People Actually Watch establishes a repeatable, trustworthy Shop workflow grounded in current verification, customer information, and reviewable execution. It is graded on execution and evidence, never GMV, commissions, orders, viewers, or rank." },
      { question: "Does this teach Selling & Influence communication craft?", answer: "No, that is a different path; this path teaches Shop systems." },
      { question: "How current are eligibility and policy details?", answer: "They were last reviewed July 2026; verify in your tools and current official TikTok Shop docs." },
      { question: "Does this permit misleading claims, fake reviews, or hidden sponsorships?", answer: "No. The curriculum explicitly refuses deceptive practices, unsafe claims, review manipulation, and unclear material connections." },
      { question: "What evidence do I leave with?", answer: "You leave with product-video-brief, review-comparison-planner, evergreen-product-series-map and a reviewable Creating Product Videos People Actually Watch Review." },
    ],
    relatedGuideSlugs: ["tiktok-live-tips", "creator-support", "creator-community"],
    internalLinks: [
      { label: "Previous: Product Selection, Research & Affiliate Strategy", href: "/streameru/product-selection-research-and-affiliate-strategy" },
      { label: "Next: LIVE Shopping That Educates and Converts", href: "/streameru/live-shopping-that-educates-and-converts" },
      { label: "Selling & Influence Mastery", href: "/streameru/programs/selling" },
    ],
    suggestedGlossaryTerms: [
      { title: "Material connection", intent: "A relationship such as an affiliate commission or free product that can affect how a recommendation is understood." },
      { title: "Shop workflow", intent: "A documented, current process for product research, demonstrations, disclosures, support routing, and review." },
    ],
    suggestedDownloads: [
      { title: "product-video-brief", intent: "Lesson system artifact." },
      { title: "review-comparison-planner", intent: "Execution preparation artifact." },
      { title: "evergreen-product-series-map", intent: "Evidence and improvement artifact." },
    ],
    suggestedBlogSupport: [{ title: "Trustworthy TikTok Shop systems for creators", intent: "Teach current verification and customer-safe execution." }],
  },
  {
    slug: "live-shopping-that-educates-and-converts",
    primaryKeyword: "live shopping that educates and converts for TikTok Shop creators",
    secondaryKeywords: ["TikTok Shop systems", "trustworthy Shop execution", "TikTok Shop creator workflow", "Signature Shop Campaign"],
    metaTitle: "LIVE Shopping That Educates and Converts | StreamerU",
    metaDescription: "Operate a LIVE shopping run sheet that teaches before it promotes.",
    faqs: [
      { question: "What does this TikTok Shop Mastery lesson teach?", answer: "LIVE Shopping That Educates and Converts establishes a repeatable, trustworthy Shop workflow grounded in current verification, customer information, and reviewable execution. It is graded on execution and evidence, never GMV, commissions, orders, viewers, or rank." },
      { question: "Does this teach Selling & Influence communication craft?", answer: "No, that is a different path; this path teaches Shop systems." },
      { question: "How current are eligibility and policy details?", answer: "They were last reviewed July 2026; verify in your tools and current official TikTok Shop docs." },
      { question: "Does this permit misleading claims, fake reviews, or hidden sponsorships?", answer: "No. The curriculum explicitly refuses deceptive practices, unsafe claims, review manipulation, and unclear material connections." },
      { question: "What evidence do I leave with?", answer: "You leave with live-shopping-run-sheet, product-pin-rotation-planner, live-offer-education-card and a reviewable LIVE Shopping That Educates and Converts Review." },
    ],
    relatedGuideSlugs: ["tiktok-live-tips", "creator-support", "creator-community"],
    internalLinks: [
      { label: "Previous: Creating Product Videos People Actually Watch", href: "/streameru/creating-product-videos-people-actually-watch" },
      { label: "Next: Professional Product Demonstrations & Studio Setup", href: "/streameru/professional-product-demonstrations-and-studio-setup" },
      { label: "Selling & Influence Mastery", href: "/streameru/programs/selling" },
    ],
    suggestedGlossaryTerms: [
      { title: "Material connection", intent: "A relationship such as an affiliate commission or free product that can affect how a recommendation is understood." },
      { title: "Shop workflow", intent: "A documented, current process for product research, demonstrations, disclosures, support routing, and review." },
    ],
    suggestedDownloads: [
      { title: "live-shopping-run-sheet", intent: "Lesson system artifact." },
      { title: "product-pin-rotation-planner", intent: "Execution preparation artifact." },
      { title: "live-offer-education-card", intent: "Evidence and improvement artifact." },
    ],
    suggestedBlogSupport: [{ title: "Trustworthy TikTok Shop systems for creators", intent: "Teach current verification and customer-safe execution." }],
  },
  {
    slug: "professional-product-demonstrations-and-studio-setup",
    primaryKeyword: "professional product demonstrations & studio setup for TikTok Shop creators",
    secondaryKeywords: ["TikTok Shop systems", "trustworthy Shop execution", "TikTok Shop creator workflow", "Signature Shop Campaign"],
    metaTitle: "Professional Product Demonstrations & Studio Setup | StreamerU",
    metaDescription: "Create repeatable product demonstrations with an appropriate studio setup.",
    faqs: [
      { question: "What does this TikTok Shop Mastery lesson teach?", answer: "Professional Product Demonstrations & Studio Setup establishes a repeatable, trustworthy Shop workflow grounded in current verification, customer information, and reviewable execution. It is graded on execution and evidence, never GMV, commissions, orders, viewers, or rank." },
      { question: "Does this teach Selling & Influence communication craft?", answer: "No, that is a different path; this path teaches Shop systems." },
      { question: "How current are eligibility and policy details?", answer: "They were last reviewed July 2026; verify in your tools and current official TikTok Shop docs." },
      { question: "Does this permit misleading claims, fake reviews, or hidden sponsorships?", answer: "No. The curriculum explicitly refuses deceptive practices, unsafe claims, review manipulation, and unclear material connections." },
      { question: "What evidence do I leave with?", answer: "You leave with product-demo-planner, tabletop-studio-checklist, multi-angle-demo-card and a reviewable Professional Product Demonstrations & Studio Setup Review." },
    ],
    relatedGuideSlugs: ["tiktok-live-tips", "creator-support", "creator-community"],
    internalLinks: [
      { label: "Previous: LIVE Shopping That Educates and Converts", href: "/streameru/live-shopping-that-educates-and-converts" },
      { label: "Next: Analytics, Optimization & Campaign Decisions", href: "/streameru/shop-analytics-optimization-and-campaign-decisions" },
      { label: "Selling & Influence Mastery", href: "/streameru/programs/selling" },
    ],
    suggestedGlossaryTerms: [
      { title: "Material connection", intent: "A relationship such as an affiliate commission or free product that can affect how a recommendation is understood." },
      { title: "Shop workflow", intent: "A documented, current process for product research, demonstrations, disclosures, support routing, and review." },
    ],
    suggestedDownloads: [
      { title: "product-demo-planner", intent: "Lesson system artifact." },
      { title: "tabletop-studio-checklist", intent: "Execution preparation artifact." },
      { title: "multi-angle-demo-card", intent: "Evidence and improvement artifact." },
    ],
    suggestedBlogSupport: [{ title: "Trustworthy TikTok Shop systems for creators", intent: "Teach current verification and customer-safe execution." }],
  },
  {
    slug: "shop-analytics-optimization-and-campaign-decisions",
    primaryKeyword: "analytics, optimization & campaign decisions for TikTok Shop creators",
    secondaryKeywords: ["TikTok Shop systems", "trustworthy Shop execution", "TikTok Shop creator workflow", "Signature Shop Campaign"],
    metaTitle: "Analytics, Optimization & Campaign Decisions | StreamerU",
    metaDescription: "Use Shop analytics to select one evidence-based optimization at a time.",
    faqs: [
      { question: "What does this TikTok Shop Mastery lesson teach?", answer: "Analytics, Optimization & Campaign Decisions establishes a repeatable, trustworthy Shop workflow grounded in current verification, customer information, and reviewable execution. It is graded on execution and evidence, never GMV, commissions, orders, viewers, or rank." },
      { question: "Does this teach Selling & Influence communication craft?", answer: "No, that is a different path; this path teaches Shop systems." },
      { question: "How current are eligibility and policy details?", answer: "They were last reviewed July 2026; verify in your tools and current official TikTok Shop docs." },
      { question: "Does this permit misleading claims, fake reviews, or hidden sponsorships?", answer: "No. The curriculum explicitly refuses deceptive practices, unsafe claims, review manipulation, and unclear material connections." },
      { question: "What evidence do I leave with?", answer: "You leave with shop-analytics-worksheet, campaign-decision-log, optimization-priority-card and a reviewable Analytics, Optimization & Campaign Decisions Review." },
    ],
    relatedGuideSlugs: ["tiktok-live-tips", "creator-support", "creator-community"],
    internalLinks: [
      { label: "Previous: Professional Product Demonstrations & Studio Setup", href: "/streameru/professional-product-demonstrations-and-studio-setup" },
      { label: "Next: Compliance, Ethics & Customer Trust", href: "/streameru/shop-compliance-ethics-and-customer-trust" },
      { label: "Selling & Influence Mastery", href: "/streameru/programs/selling" },
    ],
    suggestedGlossaryTerms: [
      { title: "Material connection", intent: "A relationship such as an affiliate commission or free product that can affect how a recommendation is understood." },
      { title: "Shop workflow", intent: "A documented, current process for product research, demonstrations, disclosures, support routing, and review." },
    ],
    suggestedDownloads: [
      { title: "shop-analytics-worksheet", intent: "Lesson system artifact." },
      { title: "campaign-decision-log", intent: "Execution preparation artifact." },
      { title: "optimization-priority-card", intent: "Evidence and improvement artifact." },
    ],
    suggestedBlogSupport: [{ title: "Trustworthy TikTok Shop systems for creators", intent: "Teach current verification and customer-safe execution." }],
  },
  {
    slug: "shop-compliance-ethics-and-customer-trust",
    primaryKeyword: "compliance, ethics & customer trust for TikTok Shop creators",
    secondaryKeywords: ["TikTok Shop systems", "trustworthy Shop execution", "TikTok Shop creator workflow", "Signature Shop Campaign"],
    metaTitle: "Compliance, Ethics & Customer Trust | StreamerU",
    metaDescription: "Apply disclosure, claim, product, and IP safeguards to Shop content.",
    faqs: [
      { question: "What does this TikTok Shop Mastery lesson teach?", answer: "Compliance, Ethics & Customer Trust establishes a repeatable, trustworthy Shop workflow grounded in current verification, customer information, and reviewable execution. It is graded on execution and evidence, never GMV, commissions, orders, viewers, or rank." },
      { question: "Does this teach Selling & Influence communication craft?", answer: "No, that is a different path; this path teaches Shop systems." },
      { question: "How current are eligibility and policy details?", answer: "They were last reviewed July 2026; verify in your tools and current official TikTok Shop docs." },
      { question: "Does this permit misleading claims, fake reviews, or hidden sponsorships?", answer: "No. The curriculum explicitly refuses deceptive practices, unsafe claims, review manipulation, and unclear material connections." },
      { question: "What evidence do I leave with?", answer: "You leave with shop-compliance-checklist, disclosure-script-bank-shop, claim-safety-scorecard and a reviewable Compliance, Ethics & Customer Trust Review." },
    ],
    relatedGuideSlugs: ["tiktok-live-tips", "creator-support", "creator-community"],
    internalLinks: [
      { label: "Previous: Analytics, Optimization & Campaign Decisions", href: "/streameru/shop-analytics-optimization-and-campaign-decisions" },
      { label: "Next: Scaling Your TikTok Shop Business", href: "/streameru/scaling-your-tiktok-shop-business" },
      { label: "Selling & Influence Mastery", href: "/streameru/programs/selling" },
    ],
    suggestedGlossaryTerms: [
      { title: "Material connection", intent: "A relationship such as an affiliate commission or free product that can affect how a recommendation is understood." },
      { title: "Shop workflow", intent: "A documented, current process for product research, demonstrations, disclosures, support routing, and review." },
    ],
    suggestedDownloads: [
      { title: "shop-compliance-checklist", intent: "Lesson system artifact." },
      { title: "disclosure-script-bank-shop", intent: "Execution preparation artifact." },
      { title: "claim-safety-scorecard", intent: "Evidence and improvement artifact." },
    ],
    suggestedBlogSupport: [{ title: "Trustworthy TikTok Shop systems for creators", intent: "Teach current verification and customer-safe execution." }],
  },
  {
    slug: "scaling-your-tiktok-shop-business",
    primaryKeyword: "scaling your tiktok shop business for TikTok Shop creators",
    secondaryKeywords: ["TikTok Shop systems", "trustworthy Shop execution", "TikTok Shop creator workflow", "Signature Shop Campaign"],
    metaTitle: "Scaling Your TikTok Shop Business | StreamerU",
    metaDescription: "Scale Shop operations through repeatable campaigns and customer-safe systems.",
    faqs: [
      { question: "What does this TikTok Shop Mastery lesson teach?", answer: "Scaling Your TikTok Shop Business establishes a repeatable, trustworthy Shop workflow grounded in current verification, customer information, and reviewable execution. It is graded on execution and evidence, never GMV, commissions, orders, viewers, or rank." },
      { question: "Does this teach Selling & Influence communication craft?", answer: "No, that is a different path; this path teaches Shop systems." },
      { question: "How current are eligibility and policy details?", answer: "They were last reviewed July 2026; verify in your tools and current official TikTok Shop docs." },
      { question: "Does this permit misleading claims, fake reviews, or hidden sponsorships?", answer: "No. The curriculum explicitly refuses deceptive practices, unsafe claims, review manipulation, and unclear material connections." },
      { question: "What evidence do I leave with?", answer: "You leave with seasonal-campaign-planner, customer-follow-up-guide-shop, shop-scale-system-card and a reviewable Scaling Your TikTok Shop Business Review." },
    ],
    relatedGuideSlugs: ["tiktok-live-tips", "creator-support", "creator-community"],
    internalLinks: [
      { label: "Previous: Compliance, Ethics & Customer Trust", href: "/streameru/shop-compliance-ethics-and-customer-trust" },
      { label: "Next: TikTok Shop Capstone: Signature Shop Campaign", href: "/streameru/tiktok-shop-capstone-signature-shop-campaign" },
      { label: "Selling & Influence Mastery", href: "/streameru/programs/selling" },
    ],
    suggestedGlossaryTerms: [
      { title: "Material connection", intent: "A relationship such as an affiliate commission or free product that can affect how a recommendation is understood." },
      { title: "Shop workflow", intent: "A documented, current process for product research, demonstrations, disclosures, support routing, and review." },
    ],
    suggestedDownloads: [
      { title: "seasonal-campaign-planner", intent: "Lesson system artifact." },
      { title: "customer-follow-up-guide-shop", intent: "Execution preparation artifact." },
      { title: "shop-scale-system-card", intent: "Evidence and improvement artifact." },
    ],
    suggestedBlogSupport: [{ title: "Trustworthy TikTok Shop systems for creators", intent: "Teach current verification and customer-safe execution." }],
  },
  {
    slug: "tiktok-shop-capstone-signature-shop-campaign",
    primaryKeyword: "tiktok shop capstone: signature shop campaign for TikTok Shop creators",
    secondaryKeywords: ["TikTok Shop systems", "trustworthy Shop execution", "TikTok Shop creator workflow", "Signature Shop Campaign"],
    metaTitle: "TikTok Shop Capstone: Signature Shop Campaign | StreamerU",
    metaDescription: "Assemble a reviewable, compliant Shop campaign from research through improvement.",
    faqs: [
      { question: "What does this TikTok Shop Mastery lesson teach?", answer: "TikTok Shop Capstone: Signature Shop Campaign establishes a repeatable, trustworthy Shop workflow grounded in current verification, customer information, and reviewable execution. It is graded on execution and evidence, never GMV, commissions, orders, viewers, or rank." },
      { question: "Does this teach Selling & Influence communication craft?", answer: "No, that is a different path; this path teaches Shop systems." },
      { question: "How current are eligibility and policy details?", answer: "They were last reviewed July 2026; verify in your tools and current official TikTok Shop docs." },
      { question: "Does this permit misleading claims, fake reviews, or hidden sponsorships?", answer: "No. The curriculum explicitly refuses deceptive practices, unsafe claims, review manipulation, and unclear material connections." },
      { question: "What evidence do I leave with?", answer: "You leave with signature-shop-campaign-dossier, capstone-evidence-checklist-tiktok-shop, improvement-report-template-shop and a reviewable TikTok Shop Capstone: Signature Shop Campaign Review." },
    ],
    relatedGuideSlugs: ["tiktok-live-tips", "creator-support", "creator-community"],
    internalLinks: [
      { label: "Previous: Scaling Your TikTok Shop Business", href: "/streameru/scaling-your-tiktok-shop-business" },
      { label: "TikTok Shop Program Final", href: "/streameru/programs/tts/final" },
      { label: "Selling & Influence Mastery", href: "/streameru/programs/selling" },
    ],
    suggestedGlossaryTerms: [
      { title: "Material connection", intent: "A relationship such as an affiliate commission or free product that can affect how a recommendation is understood." },
      { title: "Shop workflow", intent: "A documented, current process for product research, demonstrations, disclosures, support routing, and review." },
    ],
    suggestedDownloads: [
      { title: "signature-shop-campaign-dossier", intent: "Lesson system artifact." },
      { title: "capstone-evidence-checklist-tiktok-shop", intent: "Execution preparation artifact." },
      { title: "improvement-report-template-shop", intent: "Evidence and improvement artifact." },
    ],
    suggestedBlogSupport: [{ title: "Trustworthy TikTok Shop systems for creators", intent: "Teach current verification and customer-safe execution." }],
  }
];
