import { PARSER_VERSION } from "../version";
import { parseActivityIncentivePage } from "../parsers/activityIncentive";
import { parseRankUpIncentivePage } from "../parsers/rankUpIncentive";
import { parseIncrementalIncentivePage } from "../parsers/incrementalIncentive";
import { parseCreatorRosterPage } from "../parsers/creatorRoster";
import { parseLiveNowPage } from "../parsers/liveNow";
import { parseWorkspacePage } from "../parsers/workspace";
import type { PageSpec } from "./types";

/**
 * Single source of truth for supported TikTok Backstage pages (Phase 1A).
 * Do not collapse different incentive pages into one generic parser.
 */
export const PAGE_SPECS: PageSpec[] = [
  {
    id: "live_now",
    displayName: "LIVE Now",
    pathPatterns: [/\/anchor\/live/, /\/live-now/, /livenow/, /\/live(?!.*relation)/],
    titlePatterns: [/live\s*now/i],
    bodyPatterns: [/creators who are live now/i, /promote their live/i],
    requiredHeadings: [],
    optionalHeadings: [],
    uniqueBodyText: [/creators who are live now/i, /live\s*now/i],
    syncEnabled: true,
    previewOnly: false,
    syncMode: "live",
    minConfidence: 0.55,
    expectedMinColumns: 0,
    creatorCountBehavior: "expect_live_subset",
    supportedMetrics: ["live_presence", "viewer_count", "live_started"],
    parserVersion: PARSER_VERSION,
    parse: parseLiveNowPage,
  },
  {
    id: "activity_incentive",
    displayName: "Activeness Incentive",
    pathPatterns: [
      /activeness/,
      /activity.*incentive/,
      /\/incentive/,
      /\/performance/,
      /\/contribution/,
      /\/revenue/,
      /\/analytics/,
      /\/data\//,
    ],
    titlePatterns: [/activeness\s*incentive/i, /activity\s*incentive/i, /incentives?/i, /creator\s*performance/i],
    bodyPatterns: [/activeness\s*incentive/i, /valid\s*go\s*live/i, /estimated\s*bonus/i, /contribution\s*details/i],
    requiredHeadings: [/valid\s*go\s*live|live\s*days?/i, /live\s*duration|stream\s*duration|\bhours?\b/i],
    optionalHeadings: [/diamonds?/i, /activeness|activity\s*level/i, /engagements?/i],
    uniqueBodyText: [/activeness\s*incentive/i, /valid\s*go\s*live/i],
    syncEnabled: true,
    previewOnly: false,
    syncMode: "stats",
    minConfidence: 0.55,
    expectedMinColumns: 3,
    creatorCountBehavior: "expect_network_size",
    supportedMetrics: ["diamonds", "valid_live_days", "live_duration", "activeness_level"],
    parserVersion: PARSER_VERSION,
    parse: parseActivityIncentivePage,
  },
  {
    id: "rank_up_incentive",
    displayName: "Rank-up Incentive",
    pathPatterns: [/rank[\s_-]?up/, /rankup/, /tier.*incentive/],
    titlePatterns: [/rank[\s-]?up\s*incentive/i, /rank\s*incentive/i],
    bodyPatterns: [/rank[\s-]?up/i, /tier\s*last\s*month/i, /maintain\s*tier/i],
    requiredHeadings: [/tier/i],
    optionalHeadings: [/rank[\s-]?up/i, /maintain/i, /diamonds?/i, /valid\s*go\s*live/i, /live\s*duration/i],
    uniqueBodyText: [/rank[\s-]?up\s*incentive/i, /tier\s*last\s*month/i],
    syncEnabled: true,
    previewOnly: false,
    syncMode: "stats",
    minConfidence: 0.65,
    expectedMinColumns: 2,
    creatorCountBehavior: "expect_network_size",
    supportedMetrics: [
      "tier",
      "rank_up_status",
      "maintain_tier_status",
      "diamonds",
      "valid_live_days",
      "live_duration",
      "estimated_contribution",
    ],
    parserVersion: PARSER_VERSION,
    parse: parseRankUpIncentivePage,
  },
  {
    id: "incremental_incentive",
    displayName: "Incremental Revenue Incentive",
    pathPatterns: [/incremental/, /revenue.*incentive/],
    titlePatterns: [/incremental/i, /revenue\s*incentive/i],
    bodyPatterns: [/incremental\s*(revenue|incentive)/i],
    requiredHeadings: [/creator|username/i],
    optionalHeadings: [/diamonds?/i, /revenue/i, /contribution/i],
    uniqueBodyText: [/incremental\s*(revenue|incentive)/i],
    syncEnabled: true,
    previewOnly: false,
    syncMode: "stats",
    minConfidence: 0.65,
    expectedMinColumns: 2,
    creatorCountBehavior: "expect_network_size",
    supportedMetrics: ["diamonds", "estimated_contribution"],
    parserVersion: PARSER_VERSION,
    parse: parseIncrementalIncentivePage,
  },
  {
    id: "creator_roster",
    displayName: "Manage Creators / Roster",
    pathPatterns: [
      /\/relation/,
      /\/relationship/,
      /manage.*creator/,
      /\/creator\/manage/,
      /\/anchor\/creator/,
      /\/creators?$/,
    ],
    titlePatterns: [/manage\s*relationship/i, /manage\s*creators?/i],
    bodyPatterns: [
      /manage\s*relationship/i,
      /manage\s*creators?/i,
      /relationship\s*status/i,
      /diamonds\s*in\s*l30d/i,
    ],
    requiredHeadings: [],
    optionalHeadings: [
      /creator|username/i,
      /relationship\s*status/i,
      /joined/i,
      /followers?/i,
      /likes?/i,
      /diamonds?/i,
      /date/i,
      /reason/i,
    ],
    uniqueBodyText: [
      /manage\s*creators?/i,
      /manage\s*relationship/i,
      /relationship\s*status/i,
      /transfer\s*creators?/i,
    ],
    syncEnabled: true,
    previewOnly: false,
    syncMode: "roster",
    minConfidence: 0.5,
    expectedMinColumns: 1,
    creatorCountBehavior: "expect_network_size",
    supportedMetrics: ["roster_presence", "network_status"],
    parserVersion: PARSER_VERSION,
    parse: parseCreatorRosterPage,
  },
  {
    id: "workspace_metrics",
    displayName: "Workspace overview",
    pathPatterns: [/\/workspace/, /\/portal\/?$/],
    titlePatterns: [/workspace/i],
    bodyPatterns: [/workspace\s*overview/i, /creator\s*network\s*workspace/i],
    requiredHeadings: [],
    optionalHeadings: [],
    uniqueBodyText: [/workspace/i],
    syncEnabled: false,
    previewOnly: true,
    syncMode: "preview_only",
    minConfidence: 0.5,
    expectedMinColumns: 0,
    creatorCountBehavior: "none",
    supportedMetrics: [],
    parserVersion: PARSER_VERSION,
    parse: parseWorkspacePage,
  },
];

export function getPageSpec(id: string): PageSpec | undefined {
  return PAGE_SPECS.find((s) => s.id === id);
}

export const SAFE_CONFIDENCE_THRESHOLD = 0.55;
